### ISSUE TITLE
[auditd_manager] audit_rule_files variable needs `multi: true`

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#10000]
The `audit_rules_files` variable is apparently expected to a be an array if you look at the description (says “A list”) and the way it’s used in the handlebar file (with a loop). So the variable declaration is missing [`multi: true`](https://github.com/elastic/package-spec/blob/a895b110b5a86b6ae5410c8bd3834539e27a1b92/spec/integration/data_stream/manifest.spec.yml#L73-L78). 

When I view the rendered Agent policy, mine has a `audit_rule_files: null`.

```yaml
inputs:
  - id: audit/auditd-auditd-616b2972-663e-48fc-88a5-4abed592931e
    name: auditd_manager-1
    revision: 1
    type: audit/auditd
    use_output: default
    meta:
      package:
        name: auditd_manager
        version: 1.16.3
    data_stream:
      namespace: default
    package_policy_id: 616b2972-663e-48fc-88a5-4abed592931e
    streams:
      - id: >-
          audit/auditd-auditd_manager.auditd-616b2972-663e-48fc-88a5-4abed592931e
        type: audit/auditd
        data_stream:
          dataset: auditd_manager.auditd
          type: logs
        condition: '${host.platform} == ''linux'''
        include_raw_message: true
        socket_type: ''
        immutable: false
        resolve_ids: true
        failure_mode: silent
        audit_rules: '-a always,exit -F arch=b64 -S execve,execveat -k exec'
        audit_rule_files: null
        backlog_limit: 8192
        rate_limit: 0
        include_warnings: false
        backpressure_strategy: auto
        tags:
          - auditd_manager-auditd
```

Despite having used:

<img width="386" alt="Screenshot 2024-05-28 at 10 38 14" src="https://github.com/elastic/integrations/assets/4565752/31c2668d-433b-4ae0-87d0-02492b8a624d">

References

- https://github.com/elastic/integrations/blob/a19f4a5632b0a5ce609b285c3fc57dff336b8ed9/packages/auditd_manager/data_stream/auditd/agent/stream/auditd.yml.hbs#L13-L18
- https://github.com/elastic/integrations/blob/a19f4a5632b0a5ce609b285c3fc57dff336b8ed9/packages/auditd_manager/data_stream/auditd/manifest.yml#L84-L92
