### ISSUE TITLE
[Check Point] Improve normalisation of user.name field

### ISSUE THREAD

**Issue by dan21san** [elastic/integrations#10191]
## Use Case

I am analysing and working with Checkpoint Firewall logs collected via Check Point integration .

I noticed that in some cases the ECS field `user.name` is not filled. 

In the default pipeline the user.name is setting by this processor:
```
- set:
      field: user.name
      value: '{{{ source.user.name }}}'
      override: false
      ignore_empty_value: true
```

and the source.user.name is setting by the renaming processors:

```
- rename:
      field: checkpoint.administrator
      target_field: source.user.name
      ignore_missing: true
  - rename:
      field: checkpoint.src_user_name
      target_field: source.user.name
      if: ctx.source?.user?.name == null
      ignore_missing: true
```

So I suggest to consider also the standardization in ECS schema of the field `checkpoint.user` . The above processors will be changed to :

```
- rename:
      field: checkpoint.user
      target_field: source.user.name
      ignore_missing: true
- rename:
      field: checkpoint.administrator
      target_field: source.user.name
      if: ctx.source?.user?.name == null
      ignore_missing: true
  - rename:
      field: checkpoint.src_user_name
      target_field: source.user.name
      if: ctx.source?.user?.name == null
      ignore_missing: true
```

Here a screenshot from Kibana's Discover in which you can see that the **source.user.name** is not filled in and consequently the **user.name** field is not filled in either. Instead, the **checkpoint.user** field exists.

![PyDGglD74W](https://github.com/elastic/integrations/assets/98960305/6deb669a-cb91-417a-add6-a006e6a92fe7)
