### ISSUE TITLE
[CiscoIOS] Incorrect Parsing of IPACCESSLOGSP events, integration tests not running in CI?

### ISSUE THREAD

**Issue by DylanRJohnston** [elastic/integrations#10253]
The Cisco IOS module has the following [log line](https://github.com/elastic/integrations/blob/4d81bd6c7e03924f7e86842da79c3b890359e5d9/packages/cisco_ios/data_stream/log/_dev/test/pipeline/test-asr920.log#L8) in its test data.

```
<166>352133: ASR920: Aug 3 08:04:47.140: %SEC-6-IPACCESSLOGNP: list ACL_CE-SECURITY denied 112 89.160.20.112 -> 224.0.0.18, 295 packets
```

However the [corresponding dissect](https://github.com/elastic/integrations/blob/4d81bd6c7e03924f7e86842da79c3b890359e5d9/packages/cisco_ios/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L209) doesn't handle the pluralization of the word `packet(s)`. Dissections must match the entire string, and so the trailing `s` causes the dissection to fail the whole pipeline.

```yml
  - dissect:
      field: message
      tag: dissect_gnp
      pattern: "list %{cisco.ios.access_list} %{_temp_.event.action} %{network.iana_number} %{source.address} %{} %{destination.address}, %{source.packets} packet"
      if: "['IPACCESSLOGNP', 'ACCESSLOGNP'].contains(ctx.event?.code)"
 ```
 
 Given this counter example is in the test data, are the tests being properly evaluated? As far as I can tell, the problem in the dissection pattern has existed for over 3 years and the counter example has been in the test data for at least 2 years.
