### ISSUE TITLE
[entityanalytics_okta]: Support retention of custom user profile attributes 

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#10566]
### Integration Name

Okta Entity Analytics [entityanalytics_okta]

### Integration Version

1.1.0

### Agent Version

8.13.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.1

### OS Version and Architecture

Unknown

### Anything else?

I believe the integration is working as intended so consider this a feature request. Okta supports adding additional attributes to the user profile, and as a user I was to retain that data in the document that is sent to Elasticsearch.

For example, if I have added [custom attributes](https://developer.okta.com/docs/reference/api/users/#custom-profile-properties) like

- employeeStatus
- incorrectOTPCount

then I would like to have those fields pass through in the event to Elasticsearch.

Another field that I would like to retain is the `credentials.recovery_question.question`.

**Comment by andrewkroh** [comment]
As a workaround, my suggestion is to create your own `event.original` then create an `@custom` pipeline in Elasticsearch to handle retention of the custom fields.

Using an edge (beats) processor of:

```yaml
- script:
    lang: javascript
    source: |
      function process(evt) {
        evt.Put('event.original', JSON.stringify(evt.Get('okta')));
      }
```

Create a custom pipeline for Fleet that does:

```yaml
processors:
  - json:
      if: ctx.event?.original != null
      field: event.original
      target_field: _tmp
  - rename:
      field: _tmp.profile.employeeStatus
      target_field: entityanalytics_okta.user.profile.employeeStatus
      ignore_missing: true
  - rename:
      field: _tmp.profile.incorrectOTPCount
      target_field: entityanalytics_okta.user.profile.incorrectOTPCount
      ignore_missing: true
  - rename:
      field: _tmp.credentials.recovery_question.question
      target_field: entityanalytics_okta.user.credentials.recovery_question.question
      ignore_missing: true
  - remove:
      field: _tmp
      ignore_missing: true
```
