### ISSUE TITLE
[aws-cloudwatch] 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#10564]
Env: running Elastic Agent on Ubuntu 24 on a T4 (ARM) EC2 instance
Error: 
```
[elastic_agent.filebeat][error] getLogEventsFromCloudWatch failed: error FilterLogEvents with Paginator: operation error CloudWatch Logs: FilterLogEvents, https response error StatusCode: 400, RequestID: c53b8645-2bda-475e-8d96-437c68f004ce, InvalidParameterException: 1 validation error detected: Value '-6795364578871' at 'startTime' failed to satisfy constraint: Member must have value greater than or equal to 0
```

agent config:
```
inputs:
    - data_stream:
        namespace: default
      id: aws-cloudwatch-aws_bedrock-b61ba78b-e8d2-49f0-a053-2ffd04310622
      meta:
        package:
            name: aws_bedrock
            version: 0.3.0
      name: aws_bedrock-3
      package_policy_id: b61ba78b-e8d2-49f0-a053-2ffd04310622
      revision: 17
      streams:
        - access_key_id: <REDACTED>
          api_sleep: 200ms
          data_stream:
            dataset: aws_bedrock.invocation
            type: logs
          default_region: eu-west-2
          id: aws-cloudwatch-aws_bedrock.invocation-b61ba78b-e8d2-49f0-a053-2ffd04310622
          log_group_arn: arn:aws:logs:eu-west-2:123456:log-group:shared-london-bedrock-log-group
          publisher_pipeline.disable_host: true
          scan_frequency: 1m
          secret_access_key: <REDACTED>
          start_position: beginning
          tags:
            - preserve_original_event
            - forwarded
      type: aws-cloudwatch
      use_output: default
    - data_stream:
        namespace: default
```

beat-rendered-config.yml:
```
inputs:
    - access_key_id: <REDACTED>
      api_sleep: 200ms
      data_stream:
        dataset: aws_bedrock.invocation
        type: logs
      default_region: eu-west-2
      id: aws-cloudwatch-aws_bedrock.invocation-b61ba78b-e8d2-49f0-a053-2ffd04310622
      index: logs-aws_bedrock.invocation-default
      log_group_arn: arn:aws:logs:eu-west-2:123456:log-group:shared-london-bedrock-log-group
      processors:
        - add_fields:
            fields:
                input_id: aws-cloudwatch-aws_bedrock-b61ba78b-e8d2-49f0-a053-2ffd04310622
            target: '@metadata'
        - add_fields:
            fields:
                dataset: aws_bedrock.invocation
                namespace: default
                type: logs
            target: data_stream
        - add_fields:
            fields:
                dataset: aws_bedrock.invocation
            target: event
        - add_fields:
            fields:
                stream_id: aws-cloudwatch-aws_bedrock.invocation-b61ba78b-e8d2-49f0-a053-2ffd04310622
            target: '@metadata'
        - add_fields:
            fields:
                id: b6a844ef-80c9-4cb1-918f-1c93023bb370
                snapshot: false
                version: 8.14.3
            target: elastic_agent
        - add_fields:
            fields:
                id: b6a844ef-80c9-4cb1-918f-1c93023bb370
            target: agent
      publisher_pipeline:
        disable_host: true
      scan_frequency: 1m
      secret_access_key:<REDACTED>
      start_position: beginning
      tags:
        - preserve_original_event
        - forwarded
      type: aws-cloudwatch
```
