### ISSUE TITLE
[M365 Defender]: Event dataset pipeline sets `host.os.type` to windows for MacOS devices

### ISSUE THREAD

**Issue by jvalente-salemstate** [elastic/integrations#10680]
### Integration Name

Microsoft M365 Defender [m365_defender]

### Dataset Name

m365_defender.event

### Integration Version

2.14.2

### Agent Version

8.14.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.14.3

### OS Version and Architecture

Windows Server 2019 Datacenter

### What did you do?

I've found that my laptop, running MacOS, is generating alerts for anomalous processes on Windows. 

This is because `pipeline-device.yml` is setting `host.os.type` to `windows` with a wider range of conditions, to catch when the OS platform is not set.

```yml

  - set:
      field: host.os.type
      value: windows
      if: ctx.m365_defender?.event?.os?.platform != null && ctx.m365_defender.event.os.platform.toLowerCase().contains('windows')
  - set:
      field: host.os.type
      value: linux
      if: ctx.m365_defender?.event?.os?.platform != null && ctx.m365_defender.event.os.platform.toLowerCase().contains('linux')
  - set:
      field: host.os.type
      value: macos
      if: ctx.m365_defender?.event?.os?.platform != null && ctx.m365_defender.event.os.platform.toLowerCase().contains('macos')
  # host.os.type can also be derived for Windows based on event.category
  - set:
      field: host.os.type
      value: windows
      if: >- 
        ctx.event?.category != null && (
            ctx.event.category.contains('api') || 
            ctx.event.category.contains('registry') || 
            ctx.event.category.contains('library') || 
            ctx.event.category.contains('driver')
        )
  - set:
      field: host.os.type
      value: windows
      if: >- 
        ctx.event?.category != null && ctx.event.category.contains('file') && (
            ctx.m365_defender?.event?.initiating_process?.account_sid != null || 
            ctx.m365_defender?.event?.request?.account_sid != null
        )
  - set:
      field: host.os.type
      value: windows
      if: >- 
        ctx.event?.category != null && ctx.event.category.contains('process') && (
            ctx.m365_defender?.event?.initiating_process?.account_sid != null
        )
  - set:
      field: host.os.type
      value: windows
      if: >- 
        ctx.event?.category != null && ctx.event.category.contains('authentication') && (
            ctx.m365_defender?.event?.initiating_process?.account_sid != null ||
            ctx.m365_defender?.event?.account?.sid != null
        )
  - set:
      field: host.os.type
      value: windows
      if: >- 
        ctx.event?.category != null && ctx.event.category.contains('network') && (
            ctx.m365_defender?.event?.initiating_process?.account_sid != null
        )

```

In the case of the below sample event, it's seeing a process event where MDE comes up with an account SID, then sets the os type to windows. 

```json
    "m365_defender-azure-eventhub": {
      "enabled": true,
      "streams": {
        "m365_defender.event": {
          "enabled": true,
          "vars": {
            "eventhub": "advancedhuntinghub",
            "consumer_group": "$Default",
            "connection_string": "Endpoint=<>",
            "storage_account": "<>",
            "storage_account_key": {
              "id": "<>",
              "isSecretRef": true
            },
            "tags": [
              "forwarded",
              "m365_defender-event"
            ],
            "preserve_original_event": false,
            "preserve_duplicate_custom_fields": false
          }
        }
      }
    }

```

### What did you see?

```json
{
  "_index": ".ds-logs-m365_defender.event-default-2024.07.26-000034",
  "_id": "<>",
  "_version": 1,
  "_score": 0,
  "_source": {
    "agent": {
      "name": "<>",
      "id": "<>",
      "ephemeral_id": "<>",
      "type": "filebeat",
      "version": "8.14.3"
    },
    "process": {
      "args": [
        "git",
        "clone",
        "git@github.com:microsoftgraph/msgraph-metadata.git"
      ],
      "parent": {
        "args": [
          "-zsh"
        ],
        "group_leader": {
          "start": "2024-07-31T01:51:08.658Z",
          "name": "zsh",
          "pid": 14376
        },
        "code_signature": {
          "status": "Unknown"
        },
        "start": "2024-07-31T04:00:54.277Z",
        "name": "zsh",
        "pid": 16400,
        "args_count": 1,
        "command_line": "-zsh",
        "hash": {
          "sha1": "10902c20ae7fe9628bdef8ea66dad50452c32586",
          "sha256": "93a841e31e44398b7f24629b54e0c1f9037a31586c809cad5d9e869704c7b9a0",
          "md5": "179be5c0866eeb818e4f465e46989af1"
        },
        "executable": "/bin/zsh"
      },
      "name": "git",
      "start": "2024-07-31T04:00:54.292Z",
      "pid": 16400,
      "args_count": 3,
      "executable": "/opt/homebrew/Cellar/git/2.45.2/bin/git",
      "hash": {
        "sha1": "3de9a80345a9b4ab89fab7c4d01ef47277e490c7",
        "sha256": "29ecb8fd7e0740f0ef643c13b7ef723a58f52fba3de329506018adde3d70c137",
        "md5": "e52eb0281206cdfda18b98549d96d73b"
      },
      "command_line": "git clone git@github.com:microsoftgraph/msgraph-metadata.git"
    },
    "elastic_agent": {
      "id": "<>",
      "version": "8.14.3",
      "snapshot": false
    },
    "tags": [
      "forwarded",
      "m365_defender-event"
    ],
    "input": {
      "type": "azure-eventhub"
    },
    "@timestamp": "2024-07-31T04:00:54.292Z",
    "ecs": {
      "version": "8.11.0"
    },
    "related": {
      "hosts": [
        "<>",
        "jamess-macbook-pro"
      ],
      "user": [
        "<>"
      ],
      "hash": [
        "e52eb0281206cdfda18b98549d96d73b",
        "3de9a80345a9b4ab89fab7c4d01ef47277e490c7",
        "29ecb8fd7e0740f0ef643c13b7ef723a58f52fba3de329506018adde3d70c137",
        "179be5c0866eeb818e4f465e46989af1",
        "10902c20ae7fe9628bdef8ea66dad50452c32586",
        "93a841e31e44398b7f24629b54e0c1f9037a31586c809cad5d9e869704c7b9a0"
      ]
    },
    "data_stream": {
      "namespace": "default",
      "type": "logs",
      "dataset": "m365_defender.event"
    },
    "host": {
      "os": {
        "type": "windows"
      },
      "name": "jamess-macbook-pro",
      "id": "<>"
    },
    "event": {
      "agent_id_status": "verified",
      "ingested": "2024-07-31T05:07:11Z",
      "kind": "event",
      "action": "start",
      "category": [
        "process"
      ],
      "type": [
        "start"
      ],
      "dataset": "m365_defender.event"
    },
    "m365_defender": {
      "event": {
        "logon": {
          "id": "0"
        },
        "additional_fields": {
          "InitiatingProcessPosixSessionId": 14375,
          "ProcessPosixEffectiveGroup": {
            "PosixGroupId": 20,
            "Name": "staff"
          },
          "InitiatingProcessPosixEffectiveUser": {
            "DomainName": "Jamess-MacBook-Pro",
            "PrimaryPosixGroup": {
              "PosixGroupId": 20,
              "Name": "staff"
            },
            "AadUserUpn": "<>",
            "PosixUserId": 501,
            "LogonId": 0,
            "Sid": "S-1-5-21-<>",
            "Name": "<>"
          },
          "InitiatingProcessPosixEffectiveGroup": {
            "PosixGroupId": 20,
            "Name": "staff"
          },
          "ProcessCurrentWorkingDirectory": "/Users/<>/Git/docs-clone",
          "ProcessPosixSessionId": 14375,
          "ProcessPosixFilePermissions": [
            "None"
          ],
          "InitiatingProcessPosixAttachedTerminal": "/dev/ttys003",
          "InitiatingProcessPosixProcessGroupId": 14375,
          "InitiatingProcessPosixFilePermissions": [
            "None"
          ],
          "ProcessPosixAttachedTerminal": "/dev/ttys003",
          "InitiatingProcessCurrentWorkingDirectory": "/Users/<>",
          "ProcessPosixEffectiveUser": {
            "DomainName": "Jamess-MacBook-Pro",
            "PrimaryPosixGroup": {
              "PosixGroupId": 20,
              "Name": "staff"
            },
            "AadUserUpn": "<>",
            "PosixUserId": 501,
            "LogonId": 0,
            "Sid": "S-1-5-21-<>",
            "Name": "<>"
          },
          "InitiatingProcessPosixRealUser": {
            "DomainName": "Jamess-MacBook-Pro",
            "PrimaryPosixGroup": {
              "PosixGroupId": 20,
              "Name": "staff"
            },
            "AadUserUpn": "<>",
            "PosixUserId": 501,
            "LogonId": 0,
            "Sid": "S-1-5-21-<>",
            "Name": "<>"
          },
          "ProcessPosixProcessGroupId": 16400
        },
        "tenant": {
          "name": "DefaultTenant",
          "id": "<>"
        },
        "timestamp": "2024-07-31T04:00:54.292Z",
        "process": {
          "creation_time": "2024-07-31T04:00:54.292Z",
          "token_elevation": "None",
          "id": 16400,
          "command_line": "git clone git@github.com:microsoftgraph/msgraph-metadata.git"
        },
        "operation_name": "Publish",
        "initiating_process": {
          "creation_time": "2024-07-31T04:00:54.277Z",
          "account_upn": "<>",
          "logon_id": "0",
          "account_name": "<>",
          "account_sid": "S-1-5-21-<>",
          "signer_type": "Unknown",
          "account_domain": "jamess-macbook-pro",
          "token_elevation": "None"
        },
        "report_id": "<>",
        "time": "2024-07-31T04:06:10.444Z",
        "category": "AdvancedHunting-DeviceProcessEvents",
        "account": {
          "upn": "<>"
        }
      }
    },
    "user": {
      "domain": "jamess-macbook-pro",
      "name": "<>",
      "id": "S-1-5-21-<>"
    },
    "azure": {
      "sequence_number": 1111,
      "consumer_group": "$Default",
      "offset": 1111,
      "eventhub": "advancedhuntinghub",
      "enqueued_time": "2024-07-31T05:07:06.246Z"
    }
  },
  "fields": {
    "process.hash.md5": [
      "e52eb0281206cdfda18b98549d96d73b"
    ],
    "elastic_agent.version": [
      "8.14.3"
    ],
    "event.category": [
      "process"
    ],
    "m365_defender.event.process.id": [
      16400
    ],
    "process.name.text": [
      "git"
    ],
    "m365_defender.event.additional_fields": [
      {
        "InitiatingProcessPosixSessionId": 14375,
        "ProcessPosixEffectiveGroup": {
          "PosixGroupId": 20,
          "Name": "staff"
        },
        "InitiatingProcessPosixEffectiveUser": {
          "DomainName": "Jamess-MacBook-Pro",
          "PrimaryPosixGroup": {
            "PosixGroupId": 20,
            "Name": "staff"
          },
          "AadUserUpn": "<>",
          "PosixUserId": 501,
          "LogonId": 0,
          "Sid": "S-1-5-21-<>",
          "Name": "<>"
        },
        "InitiatingProcessPosixEffectiveGroup": {
          "PosixGroupId": 20,
          "Name": "staff"
        },
        "ProcessCurrentWorkingDirectory": "/Users/<>/Git/docs-clone",
        "ProcessPosixSessionId": 14375,
        "ProcessPosixFilePermissions": [
          "None"
        ],
        "InitiatingProcessPosixAttachedTerminal": "/dev/ttys003",
        "InitiatingProcessPosixProcessGroupId": 14375,
        "InitiatingProcessPosixFilePermissions": [
          "None"
        ],
        "ProcessPosixAttachedTerminal": "/dev/ttys003",
        "InitiatingProcessCurrentWorkingDirectory": "/Users/<>",
        "ProcessPosixEffectiveUser": {
          "DomainName": "Jamess-MacBook-Pro",
          "PrimaryPosixGroup": {
            "PosixGroupId": 20,
            "Name": "staff"
          },
          "AadUserUpn": "<>",
          "PosixUserId": 501,
          "LogonId": 0,
          "Sid": "S-1-5-21-<>",
          "Name": "<>"
        },
        "InitiatingProcessPosixRealUser": {
          "DomainName": "Jamess-MacBook-Pro",
          "PrimaryPosixGroup": {
            "PosixGroupId": 20,
            "Name": "staff"
          },
          "AadUserUpn": "<>",
          "PosixUserId": 501,
          "LogonId": 0,
          "Sid": "S-1-5-21-<>",
          "Name": "<>"
        },
        "ProcessPosixProcessGroupId": 16400
      }
    ],
    "host.name.text": [
      "jamess-macbook-pro"
    ],
    "m365_defender.event.initiating_process.signer_type": [
      "Unknown"
    ],
    "process.parent.command_line": [
      "-zsh"
    ],
    "process.parent.name": [
      "zsh"
    ],
    "process.hash.sha256": [
      "29ecb8fd7e0740f0ef643c13b7ef723a58f52fba3de329506018adde3d70c137"
    ],
    "process.parent.pid": [
      16400
    ],
    "related.hash": [
      "e52eb0281206cdfda18b98549d96d73b",
      "3de9a80345a9b4ab89fab7c4d01ef47277e490c7",
      "29ecb8fd7e0740f0ef643c13b7ef723a58f52fba3de329506018adde3d70c137",
      "179be5c0866eeb818e4f465e46989af1",
      "10902c20ae7fe9628bdef8ea66dad50452c32586",
      "93a841e31e44398b7f24629b54e0c1f9037a31586c809cad5d9e869704c7b9a0"
    ],
    "process.pid": [
      16400
    ],
    "azure.offset": [
      "<>"
    ],
    "m365_defender.event.initiating_process.logon_id": [
      "0"
    ],
    "m365_defender.event.report_id": [
      "21051"
    ],
    "agent.name.text": [
      "<>"
    ],
    "agent.name": [
      "<>"
    ],
    "host.name": [
      "jamess-macbook-pro"
    ],
    "m365_defender.event.initiating_process.account_domain": [
      "jamess-macbook-pro"
    ],
    "event.agent_id_status": [
      "verified"
    ],
    "event.kind": [
      "event"
    ],
    "m365_defender.event.process.creation_time": [
      "2024-07-31T04:00:54.292Z"
    ],
    "host.os.type": [
      "windows"
    ],
    "user.id": [
      "S-1-5-21-<>"
    ],
    "process.parent.start": [
      "2024-07-31T04:00:54.277Z"
    ],
    "input.type": [
      "azure-eventhub"
    ],
    "data_stream.type": [
      "logs"
    ],
    "process.parent.args_count": [
      1
    ],
    "related.user": [
      "<>"
    ],
    "tags": [
      "forwarded",
      "m365_defender-event"
    ],
    "azure.consumer_group": [
      "$Default"
    ],
    "process.name": [
      "git"
    ],
    "agent.id": [
      "<>"
    ],
    "azure.sequence_number": [
      11111111
    ],
    "ecs.version": [
      "8.11.0"
    ],
    "process.parent.executable.text": [
      "/bin/zsh"
    ],
    "agent.version": [
      "8.14.3"
    ],
    "m365_defender.event.logon.id": [
      "0"
    ],
    "related.hosts": [
      "<>",
      "jamess-macbook-pro"
    ],
    "process.start": [
      "2024-07-31T04:00:54.292Z"
    ],
    "process.command_line.text": [
      "git clone git@github.com:microsoftgraph/msgraph-metadata.git"
    ],
    "azure.enqueued_time": [
      "2024-07-31T05:07:06.246Z"
    ],
    "azure.eventhub": [
      "advancedhuntinghub"
    ],
    "m365_defender.event.process.command_line": [
      "git clone git@github.com:microsoftgraph/msgraph-metadata.git"
    ],
    "m365_defender.event.initiating_process.account_upn": [
      "<>"
    ],
    "user.name": [
      "<>"
    ],
    "m365_defender.event.category": [
      "AdvancedHunting-DeviceProcessEvents"
    ],
    "m365_defender.event.initiating_process.creation_time": [
      "2024-07-31T04:00:54.277Z"
    ],
    "m365_defender.event.initiating_process.token_elevation": [
      "None"
    ],
    "process.parent.code_signature.status": [
      "Unknown"
    ],
    "process.parent.name.text": [
      "zsh"
    ],
    "m365_defender.event.tenant.name": [
      "DefaultTenant"
    ],
    "agent.type": [
      "filebeat"
    ],
    "process.executable.text": [
      "/opt/homebrew/Cellar/git/2.45.2/bin/git"
    ],
    "event.module": [
      "m365_defender"
    ],
    "m365_defender.event.account.upn": [
      "<>"
    ],
    "elastic_agent.snapshot": [
      false
    ],
    "user.domain": [
      "jamess-macbook-pro"
    ],
    "host.id": [
      "94c86e62444c44f2433692e26b96c5d51224a25f"
    ],
    "process.parent.hash.sha256": [
      "93a841e31e44398b7f24629b54e0c1f9037a31586c809cad5d9e869704c7b9a0"
    ],
    "process.executable": [
      "/opt/homebrew/Cellar/git/2.45.2/bin/git"
    ],
    "process.parent.group_leader.start": [
      "2024-07-31T01:51:08.658Z"
    ],
    "process.parent.group_leader.pid": [
      14376
    ],
    "m365_defender.event.operation_name": [
      "Publish"
    ],
    "process.parent.executable": [
      "/bin/zsh"
    ],
    "process.parent.hash.md5": [
      "179be5c0866eeb818e4f465e46989af1"
    ],
    "process.parent.command_line.text": [
      "-zsh"
    ],
    "elastic_agent.id": [
      "11df786a-f8cd-4109-bfa9-1b2ec9ec9885"
    ],
    "process.args_count": [
      3
    ],
    "data_stream.namespace": [
      "default"
    ],
    "process.parent.group_leader.name": [
      "zsh"
    ],
    "m365_defender.event.tenant.id": [
      "<>"
    ],
    "m365_defender.event.time": [
      "2024-07-31T04:06:10.444Z"
    ],
    "m365_defender.event.initiating_process.account_name": [
      "<>"
    ],
    "m365_defender.event.process.token_elevation": [
      "None"
    ],
    "process.args": [
      "git",
      "clone",
      "git@github.com:microsoftgraph/msgraph-metadata.git"
    ],
    "process.parent.hash.sha1": [
      "10902c20ae7fe9628bdef8ea66dad50452c32586"
    ],
    "m365_defender.event.initiating_process.account_sid": [
      "S-1-5-21-<>"
    ],
    "process.parent.args": [
      "-zsh"
    ],
    "event.action": [
      "start"
    ],
    "event.ingested": [
      "2024-07-31T05:07:11.000Z"
    ],
    "@timestamp": [
      "2024-07-31T04:00:54.292Z"
    ],
    "data_stream.dataset": [
      "m365_defender.event"
    ],
    "event.type": [
      "start"
    ],
    "process.command_line": [
      "git clone git@github.com:microsoftgraph/msgraph-metadata.git"
    ],
    "agent.ephemeral_id": [
      "cf942924-37f4-4595-a7fc-4e848099a0c3"
    ],
    "m365_defender.event.timestamp": [
      "2024-07-31T04:00:54.292Z"
    ],
    "process.hash.sha1": [
      "3de9a80345a9b4ab89fab7c4d01ef47277e490c7"
    ],
    "event.dataset": [
      "m365_defender.event"
    ],
    "user.name.text": [
      "<>"
    ]
  }
}

```

### What did you expect to see?

The correct value of `host.os.type`, otherwise null if it cannot be determined.

I am not sure what in the event would explicitly & consistently identify it as a Mac (other than the hostname which could differ) -- and particularly not just linux.
