### ISSUE TITLE
[Elastic-agent] Filebeat sopos-xg module, "Known Devices" values are not transferred to the policy.

### ISSUE THREAD

**Issue by StefanSa** [elastic/integrations#1071]
Although the values for `Known Devices` were entered correctly in the integration settings for the `sophos-xg` module

```
- serial_number: "xxxxxxxxxxxxxxx"
  hostname: "gate01.domain.local"
- serial_number: "yyyyyyyyyyyyyyy"
  hostname: "gate02.domain.local"
```

If these are completely missing in the generated policy.

```
          dataset: sophos.xg
          type: logs
        udp: null
        host: '0.0.0.0:9005'
        processors:
          - add_locale: null
          - add_fields:
              fields:
                default: gate01.feltengroup.local
                mappings: null
              target: _conf
        tags:
          - sophos-xg
          - forwarded
```
