### ISSUE TITLE
[Cloud Security] [Agentless] [Milestone 2] Update integration to include hide_in_deployment modes

### ISSUE THREAD

**Issue by opauloh** [elastic/integrations#10867]
**Motivation**

This ticket aims to add `hide_in_deployment_mode` : `agentless` in the registry vars of the Cloud Security Posture [manifest](https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/manifest.yml) that are not compatible with agentless deployment. Please follow the list described in [this](https://github.com/elastic/security-team/issues/10327) ticket.

**Example: Disabling agentless for CNVM**

```yml
  - name: vuln_mgmt
    title: Cloud Native Vulnerability Management (CNVM)
    description: Scan for cloud workload vulnerabilities
    multiple: true
    deployment_modes:
      agentless:
        enabled: false
# ...other configs below
```

**Definition of done**

- [ ] `hide_in_deployment_mode` is set properly is set on the Cloud Security Posture [manifest](https://github.com/elastic/integrations/blob/main/packages/cloud_security_posture/manifest.yml) according to the fields defined in [this](https://github.com/elastic/security-team/issues/10327) ticket. 

**Out of scope**

- Changes in Kibana are out of scope

**Related tasks/epics**

- https://github.com/elastic/security-team/issues/9366
- https://www.elastic.co/guide/en/integrations-developer/current/define-deployment-modes.html
- https://github.com/elastic/security-team/issues/10327
