### ISSUE TITLE
[Kubernetes] Add top level processor `add_fields` for the cluster name usecase

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#10878]
One of the common processor that might be used is a `add_fields` to add a `orchestrator.cluster.name` field - we mention it in the k8s module doc - https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html#_dashboard_32:
```
processors:
  - add_fields:
      target: orchestrator.cluster
      fields:
        name: clusterName
        url: clusterURL
```

Now we provide an option to set processors on the data_stream level, but it is quite a lot of changes for the such a common scenario.

We should provide a way to set `orchestrator.cluster.name` on the integration level
