### ISSUE TITLE
[Proofpoint TAP]: Requests continue after receiving an empty array

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#11358]
### Integration Name

Proofpoint TAP [proofpoint_tap]

### Dataset Name

proofpoint_tap.clicks_blocked

### Integration Version

1.23.0

### Agent Version

8.15.2

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.2

### OS Version and Architecture

unknown

### Error Message

Server is responding with `429 Too Many Requests` despite using `interval: 1h` on all four data streams.

### What did you do?

<details>

<summary>pre-config.yaml</summary>

```yaml
# yq  '.inputs[12]' pre-config.yaml
data_stream:
  namespace: default
id: httpjson-Proofpoint TAP-9b284dbe-db27-40c8-bbd6-3a6a8ae11dd5
meta:
  package:
    name: proofpoint_tap
    version: 1.23.0
name: TAP-5i
package_policy_id: 9b284dbe-db27-40c8-bbd6-3a6a8ae11dd5
revision: 14
streams:
  - auth.basic.password: REDACTED
    auth.basic.user: REDACTED
    config_version: 2
    cursor:
      last_received_time:
        value: '[[.last_response.body.queryEndTime]]'
    data_stream:
      dataset: proofpoint_tap.clicks_blocked
      type: logs
    id: httpjson-proofpoint_tap.clicks_blocked-9b284dbe-db27-40c8-bbd6-3a6a8ae11dd5
    interval: 1h
    publisher_pipeline.disable_host: true
    request.method: GET
    request.ssl: null
    request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
    request.tracer.maxbackups: 5
    request.transforms:
      - set:
          target: url.params.format
          value: json
      - set:
          default: '[[formatDate (now (parseDuration "-24h"))]]/[[formatDate ((now (parseDuration "-24h")).Add (parseDuration "1h"))]]'
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))]][[else]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate now]][[end]]'
    request.url: https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked
    response:
      split:
        ignore_empty_value: true
        target: body.clicksBlocked
    response.pagination:
      - set:
          fail_on_template_error: true
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .last_response.body.queryEndTime "RFC3339")]]/[[formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))]][[end]]'
    tags:
      - preserve_original_event
      - forwarded
      - proofpoint_tap-clicks_blocked
  - auth.basic.password: REDACTED
    auth.basic.user: REDACTED
    config_version: 2
    cursor:
      last_received_time:
        value: '[[.last_response.body.queryEndTime]]'
    data_stream:
      dataset: proofpoint_tap.clicks_permitted
      type: logs
    id: httpjson-proofpoint_tap.clicks_permitted-9b284dbe-db27-40c8-bbd6-3a6a8ae11dd5
    interval: 1h
    publisher_pipeline.disable_host: true
    request.method: GET
    request.ssl: null
    request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
    request.tracer.maxbackups: 5
    request.transforms:
      - set:
          target: url.params.format
          value: json
      - set:
          default: '[[formatDate (now (parseDuration "-24h"))]]/[[formatDate ((now (parseDuration "-24h")).Add (parseDuration "1h"))]]'
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))]][[else]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate now]][[end]]'
    request.url: https://tap-api-v2.proofpoint.com/v2/siem/clicks/permitted
    response:
      split:
        ignore_empty_value: true
        target: body.clicksPermitted
    response.pagination:
      - set:
          fail_on_template_error: true
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .last_response.body.queryEndTime "RFC3339")]]/[[formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))]][[end]]'
    tags:
      - preserve_original_event
      - forwarded
      - proofpoint_tap-clicks_permitted
  - auth.basic.password: REDACTED
    auth.basic.user: REDACTED
    config_version: 2
    cursor:
      last_received_time:
        value: '[[.last_response.body.queryEndTime]]'
    data_stream:
      dataset: proofpoint_tap.message_blocked
      type: logs
    id: httpjson-proofpoint_tap.message_blocked-9b284dbe-db27-40c8-bbd6-3a6a8ae11dd5
    interval: 1h
    publisher_pipeline.disable_host: true
    request.method: GET
    request.ssl: null
    request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
    request.tracer.maxbackups: 5
    request.transforms:
      - set:
          target: url.params.format
          value: json
      - set:
          default: '[[formatDate (now (parseDuration "-24h"))]]/[[formatDate ((now (parseDuration "-24h")).Add (parseDuration "1h"))]]'
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))]][[else]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate now]][[end]]'
    request.url: https://tap-api-v2.proofpoint.com/v2/siem/messages/blocked
    response:
      split:
        ignore_empty_value: true
        target: body.messagesBlocked
    response.pagination:
      - set:
          fail_on_template_error: true
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .last_response.body.queryEndTime "RFC3339")]]/[[formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))]][[end]]'
    tags:
      - preserve_original_event
      - forwarded
      - proofpoint_tap-message_blocked
  - auth.basic.password: REDACTED
    auth.basic.user: REDACTED
    config_version: 2
    cursor:
      last_received_time:
        value: '[[.last_response.body.queryEndTime]]'
    data_stream:
      dataset: proofpoint_tap.message_delivered
      type: logs
    id: httpjson-proofpoint_tap.message_delivered-9b284dbe-db27-40c8-bbd6-3a6a8ae11dd5
    interval: 1h
    publisher_pipeline.disable_host: true
    request.method: GET
    request.ssl: null
    request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
    request.tracer.maxbackups: 5
    request.transforms:
      - set:
          target: url.params.format
          value: json
      - set:
          default: '[[formatDate (now (parseDuration "-24h"))]]/[[formatDate ((now (parseDuration "-24h")).Add (parseDuration "1h"))]]'
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate ((parseDate .cursor.last_received_time "RFC3339").Add (parseDuration "1h"))]][[else]][[formatDate (parseDate .cursor.last_received_time "RFC3339")]]/[[formatDate now]][[end]]'
    request.url: https://tap-api-v2.proofpoint.com/v2/siem/messages/delivered
    response:
      split:
        ignore_empty_value: true
        target: body.messagesDelivered
    response.pagination:
      - set:
          fail_on_template_error: true
          target: url.params.interval
          value: '[[if (le (formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))) (formatDate (now)))]][[formatDate (parseDate .last_response.body.queryEndTime "RFC3339")]]/[[formatDate ((parseDate .last_response.body.queryEndTime "RFC3339").Add (parseDuration "1h"))]][[end]]'
    tags:
      - preserve_original_event
      - forwarded
      - proofpoint_tap-message_delivered
type: httpjson
use_output: default
```

</details>

### What did you see?

Multiple request being made in quick succession even when the server responds with `"clicksBlocked" : []`.

Retried requests when the server responds with HTTP 429.

<details>

<summary>Request / Response Data</summary>

| @timestamp               | transaction.id    | url.original                                                                                                                      | http.response.status_code | http.response.body.content                                            |
|--------------------------|-------------------|-----------------------------------------------------------------------------------------------------------------------------------|---------------------------|-----------------------------------------------------------------------|
| 2024-10-02T17:44:01.706Z | RHS797NQDRT1E-511 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-01T23%3A43%3A58Z%2F2024-10-02T00%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:02.304Z | RHS797NQDRT1E-511 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T00:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:02.304Z | RHS797NQDRT1E-512 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T00%3A43%3A58Z%2F2024-10-02T01%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:02.850Z | RHS797NQDRT1E-512 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T01:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:02.850Z | RHS797NQDRT1E-513 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T01%3A43%3A58Z%2F2024-10-02T02%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:03.583Z | RHS797NQDRT1E-513 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T02:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:03.584Z | RHS797NQDRT1E-514 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T02%3A43%3A58Z%2F2024-10-02T03%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:04.144Z | RHS797NQDRT1E-514 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T03:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:04.144Z | RHS797NQDRT1E-515 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T03%3A43%3A58Z%2F2024-10-02T04%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:04.814Z | RHS797NQDRT1E-515 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T04:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:04.815Z | RHS797NQDRT1E-516 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T04%3A43%3A58Z%2F2024-10-02T05%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:05.579Z | RHS797NQDRT1E-516 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T05:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:05.580Z | RHS797NQDRT1E-517 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T05%3A43%3A58Z%2F2024-10-02T06%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:06.124Z | RHS797NQDRT1E-517 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T06:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:06.124Z | RHS797NQDRT1E-518 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T06%3A43%3A58Z%2F2024-10-02T07%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:06.853Z | RHS797NQDRT1E-518 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T07:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:06.854Z | RHS797NQDRT1E-519 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T07%3A43%3A58Z%2F2024-10-02T08%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:07.391Z | RHS797NQDRT1E-519 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T08:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:07.392Z | RHS797NQDRT1E-520 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T08%3A43%3A58Z%2F2024-10-02T09%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:07.950Z | RHS797NQDRT1E-520 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T09:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:07.951Z | RHS797NQDRT1E-521 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T09%3A43%3A58Z%2F2024-10-02T10%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:08.520Z | RHS797NQDRT1E-521 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T10:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:08.520Z | RHS797NQDRT1E-522 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T10%3A43%3A58Z%2F2024-10-02T11%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:09.046Z | RHS797NQDRT1E-522 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T11:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:09.047Z | RHS797NQDRT1E-523 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T11%3A43%3A58Z%2F2024-10-02T12%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:09.636Z | RHS797NQDRT1E-523 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T12:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:09.637Z | RHS797NQDRT1E-524 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T12%3A43%3A58Z%2F2024-10-02T13%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:10.240Z | RHS797NQDRT1E-524 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T13:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:10.241Z | RHS797NQDRT1E-525 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T13%3A43%3A58Z%2F2024-10-02T14%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:10.792Z | RHS797NQDRT1E-525 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T14:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:10.793Z | RHS797NQDRT1E-526 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T14%3A43%3A58Z%2F2024-10-02T15%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:11.332Z | RHS797NQDRT1E-526 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T15:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:11.333Z | RHS797NQDRT1E-527 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T15%3A43%3A58Z%2F2024-10-02T16%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:11.865Z | RHS797NQDRT1E-527 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T16:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T17:44:11.866Z | RHS797NQDRT1E-528 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-02T16%3A43%3A58Z%2F2024-10-02T17%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T17:44:12.401Z | RHS797NQDRT1E-528 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-02T17:43:58Z\", \"clicksBlocked\" : []}" |
| 2024-10-02T18:43:58.004Z | RHS797NQDRT1E-529 | https://tap-api-v2.proofpoint.com/v2/siem/clicks/blocked?format=json&interval=2024-10-01T18%3A43%3A58Z%2F2024-10-01T19%3A43%3A58Z |                           |                                                                       |
| 2024-10-02T18:43:58.543Z | RHS797NQDRT1E-529 |                                                                                                                                   | 200                       | {\queryEndTime\" : \"2024-10-01T19:43:58Z\", \"clicksBlocked\" : []}" |

</details>

### What did you expect to see?

When the service response with an empty array then no additional requests should be made until the next interval.

When the service returns `429 Too Many Requests`, the integration should not immediately retry the request. In the absence of a [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header, the integration should continue with its next request at the next regular interval.
