### ISSUE TITLE
xpack fleet agent policy invalid for Azure Logs integration

### ISSUE THREAD

**Issue by d3v3l0p3r** [elastic/integrations#11540]
### Integration Name

Azure Logs [azure]

### Dataset Name

azure.firewall_logs

### Integration Version

1.17.0

### Agent Version

8.15.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.3

### OS Version and Architecture

Ubuntu 22.04 AKS 1.30.5

### Error Message

Hi All

I'm struggling with xpack fleet agent policies and specifically the Azure Firewall logs integration and deployments from Kibana.

I am deploying Elastic Stack using the eck stack helm chart v2.14.0

I have the following config

```
        xpack.fleet.packages:
          - name: system
            version: latest
          - name: elastic_agent
            version: latest           
          - name: azure
            version: latest
        xpack.fleet.agentPolicies:
          - name: Elastic Agent on ECK policy
            id: eck-agent
            namespace: default
            monitoring_enabled:
              - logs
              - metrics
            unenroll_timeout: 900
            package_policies:
              - name: eck_agent-1
                id: eck_agent-1
                package:
                  name: system
              - name: azure_firewall_logs_integration
                package:
                  name: azure
                inputs:
                  - type: azure-eventhub
                    enabled: true
                    streams:
                      - data_stream:
                          dataset: azure.firewall_logs
                          type: logs
                        vars:
                          - name: connection_string
                            value: "Endpoint=sb://redacted"
                          - name: eventhub
                            value: "redacted"
                          - name: consumer_group
                            value: "$Default"
                          - name: storage_account
                            value: "redacted"
                          - name: storage_account_key
                            value: "redacted"
```

When I run the curl command to reset my fleet agent policies:-

`curl -v -k -u elastic:redacted --request POST --url https://localhost:5601/internal/fleet/reset_preconfigured_agent_policies/eck-agent   --header 'content-type: application/json'   --header 'kbn-xsrf: xyz' --header 'elastic-api-version: 1'`

I get a 400 error explaining that the eventhub and storage_account_key is not specified which as you can see above it is specified, are my vars malformed or incorrectly idented?

`{"statusCode":400,"error":"Bad Request","message":"Package policy is invalid: vars.eventhub: Event Hub Name is required\nvars.connection_string: Connection String is required\nvars.storage_account: Storage Account is required\nvars.storage_account_key: Storage Account Key is required"}`

Does anyone have a working example of this integration deployed via helm values for the `eck-kibana` chart.

### What did you do?

Tried lots of combinations of yml formats to pass

### What did you see?

{"statusCode":400,"error":"Bad Request","message":"Package policy is invalid: vars.eventhub: Event Hub Name is required\nvars.connection_string: Connection String is required\nvars.storage_account: Storage Account is required\nvars.storage_account_key: Storage Account Key is required"}

### What did you expect to see?

Correctly configured Azure integration deployed via fleet

**Comment by d3v3l0p3r** [comment]
@andrewkroh any help would be appreciated?

**Comment by andrewkroh** [comment]
> Package policy is invalid: vars.eventhub: Event Hub Name is required
> vars.connection_string: Connection String is required
> vars.storage_account: Storage Account is required
> vars.storage_account_key: Storage Account Key is required

I'm not familiar with this integration or helm chart, but my guess is that the level at which you are specifying the variables is wrong. There are multiple levels/places where variables exists 🤷‍♂ . You can see this if you view package source in this repo, view the variables in Kibana (shown below), or click "Preview API request" on the "Add integration" page.

<img width="1172" alt="Image" src="https://github.com/user-attachments/assets/050dcfe5-b011-4969-b467-02fbd4759960" />

Let's take `connection_string` as an example, in the YAML shared above you have the variable specified under the stream level, but in the screenshot, it is a package level variable. So I think you need to move that variable such that `vars` is a sibling of `inputs`. And make sure the other vars are specified in the right locations.

**Comment by d3v3l0p3r** [comment]
Thanks for the reply @andrewkroh we tried all sorts of combinations and locations of the variables with no luck unfortunately.

**Comment by kpollich** [comment]
The input configuration looks incorrect. I'd recommend checking the "preview API request" button in the policy UI in Fleet to inform the config structure here, or the "configs" tab in the integration overview. 

![Image](https://github.com/user-attachments/assets/9011ce7f-a6bf-4af2-9323-b3bb49def360)

![Image](https://github.com/user-attachments/assets/a4159d64-9ab7-4696-9d25-ef289c952272)

Using the newer key/value syntax I was able to get a `kibana.yml` in this form working:

```yml
- name: Elastic Agent on ECK policy 1
    id: eck-agent-1
    namespace: default
    monitoring_enabled:
      - logs
      - metrics
    unenroll_timeout: 900
    package_policies:
      - name: eck_agent-1
        id: eck_agent-1
        package:
          name: system
      - name: azure_firewall_logs_integration-1
        id: azure_firewall_logs_integration-1
        package:
          name: azure
        vars:
          connection_string: "Endpoint=sb://redacted"
          eventhub: "redacted"
          consumer_group: "$Default"
          storage_account: "redacted"
          storage_account_key: "redacted"
        inputs:
          firewall_logs-azure-eventhub:
            enabled: true
            streams:
              '[azure.firewall_logs]':
                enabled: true
```

![Image](https://github.com/user-attachments/assets/f2aa0e61-250e-42b9-8ca2-69d4427a38ae)

![Image](https://github.com/user-attachments/assets/7903dd59-9494-489a-a778-e8bdd3cf5faf)

I know this isn't the most intuitive thing in the world, but we've got an issue on our backlog to make more improvements here: https://github.com/elastic/kibana/issues/190333. The "configs" tab is probably a good first step, but having some kind of flow where going from config -> preconfiguration skeleton would be nice to make preconfiguration feel much better to use. 

I'm closing this since it seems like a configuration error. Feel free to reopen if there's further issues, or file an issue in Kibana with label `Team:Fleet`.

**Comment by d3v3l0p3r** [comment]
This is awesome, thanks @kpollich we will give it a go and feedback - it was driving us crazy!👍

**Comment by d3v3l0p3r** [comment]
@kpollich still not working unfortunately.. errors in Kibana startup

`FATAL  Error: [config validation of [xpack.fleet].agentPolicies.1.package_policies.1]: types that failed validation: [config validation of [xpack.fleet].agentPolicies.1.package_policies.1.0.inputs]: expected value of type [array] but got [Object]                                                - [config validation of [xpack.fleet].agentPolicies.1.package_policies.1.1.inputs.firewall_logs-azure-eventhub.streams.[azure.firewall_logs]]: definition for this key is missing  `

**Comment by perpective2410** [comment]
@kpollich Can we please re-open the issue, I do have the same problem, and same error message as @d3v3l0p3r 
Even with the preview- API, its not clear how you transform the output from the preview API to the helm chart values

**Comment by perpective2410** [comment]
@kpollich We've narrowed down the issue.
When updating the kibana.yaml with your config above, Kibana starts ok.
However, if we update the Kibana CRD with the config (which is what helm does), its complaining 

 FATAL  Error: [config validation of [xpack.fleet].agentPolicies.1.package_policies.4]: types that failed validation:
- [config validation of [xpack.fleet].agentPolicies.1.package_policies.4.0.inputs]: expected value of type [array] but got [Object]
- [config validation of [xpack.fleet].agentPolicies.1.package_policies.4.1.inputs.firewall_logs-azure-eventhub]: expected a plain object value, but found [Array] instead.

WHen I get inside the pod, I can see that kibana.yaml is malformed (notice `'[azure'` is truncated)

```
            - id: azure_firewall_logs_integration-1
                  inputs:
                    firewall_logs-azure-eventhub:
                        enabled: true
                        streams:
                            '[azure':
                                firewall_logs]:
                                    enabled: true
                  name: azure_firewall_logs_integration-1
                  package:
                    name: azure
                  vars:
                    connection_string: Endpoint=sb://redacted
                    consumer_group: $Default
                    eventhub: redacted
                    storage_account: redacted
                    storage_account_key: redacted
        agents:

```
