### ISSUE TITLE
[nginx]: xpack fleet agent policy configuration

### ISSUE THREAD

**Issue by perpective2410** [elastic/integrations#11629]
### Integration Name

Nginx [nginx]

### Dataset Name

nginx.access

### Integration Version

1.24.0

### Agent Version

8.15.3

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.3

### OS Version and Architecture

Linux (x64)

### Error Message

Hello,

I am trying to configure xpack fleet agent policy with the nginx integration to parse and send nginx logs to elasticsearch.
The following configuration is used (eck-kibana). I am deploying the entire stack using the helm chart **0.12.1**
No error is returned. The integration seem to be properly installed. No traces of logs in elasticsearch. I have been able to configure the nginx module using filebeat (standalone), but i am unable to do is with **fleet**. I dont see any example for this integration on github.

1. Does it seems correct?
2. Any clue what is happening? is there a way to debug the integration (nginx) and understand what's going on?

```
        xpack.fleet.packages:
          - name: system
            version: latest
          - name: elastic_agent
            version: latest
          - name: fleet_server
            version: latest
          - name: nginx
            version: latest
        xpack.fleet.agentPolicies:
          - name: Fleet Server on ECK policy
            id: eck-fleet-server
            namespace: default
            monitoring_enabled:
              - logs
              - metrics
            package_policies:
              - name: fleet_server-1
                id: fleet_server-1
                package:
                  name: fleet_server
          - name: Elastic Agent on ECK policy
            id: eck-agent
            namespace: default
            monitoring_enabled:
              - logs
              - metrics
            unenroll_timeout: 900
            package_policies:
              - name: nginx-logs
                id: nginx-logs
                package:
                  name: nginx
                inputs:
                  - type: logfile
                    enabled: true
                    streams:
                      - data_stream:
                          dataset: nginx.access
                          type: logs
                        enabled: true
                        vars:
                          - name: paths
                            value:
                              - '/var/log/containers/*${kubernetes.container.id}.log'
                      - data_stream:
                          dataset: nginx.error
                          type: logs
                        enabled: true
                        vars:
                          - name: paths
                            value:
                              - '/var/log/containers/*${kubernetes.container.id}.log'
```

Note that the following pod labels have been added:

```
    co.elastic.logs/enabled: "true"
    co.elastic.logs/module: nginx
    co.elastic.logs/fileset.stdout: access
    co.elastic.logs/fileset.stderr: error
```

### What did you do?

N/A

### What did you see?

N/A

### What did you expect to see?

Log entry in elasticsearch
