### ISSUE TITLE
[jamf_pro]: Webhook authentication example is wrong

### ISSUE THREAD

**Issue by buzzdeee** [elastic/integrations#11759]
### Integration Name

Jamf Pro [jamf_pro]

### Dataset Name

jamf_pro.events

### Integration Version

v 0.1.1

### Agent Version

8.15.0

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.15.0

### OS Version and Architecture

Ubuntu

### Error Message

For JamfPro event ingestion, the documentation here: https://www.elastic.co/docs/current/integrations/jamf_pro tells me to configure Jamf Webhook with folloing header authention:

```
{"Authorization":"${Header}", "Token":"${Value}"}
```

using the configured ${Header} and ${Value}

So I did, but in JamfPro and Elastic-Agent logs, I got to see:

```
{"message":"incorrect header or header secret"}
```

Trying curl with correct header/value did "just work". So stopped elastic agent on the host, and started a custom https listener, that logs all requests and headers. With that I've seen that Jamf sends headers alike:

```
Authorization: MySecretHeader
Token: MySecretToken
```

So, then (for each Webhook, sigh) updating the authentication JSON to:

{ "MySecretHeader": "MySecretToken" }

Made it work, and the data flows in like a charm.

### What did you do?

described above

### What did you see?

following documentation, but no data incoming

### What did you expect to see?

it just to work ;)

### Anything else?

please update documentation

**Comment by efd6** [comment]
@buzzdeee Can you show the sanitised relevant portions of the pre-config.yml from a diagnostic bundle and the sanitised JSON you have handed to the Jamf webhook configuration.

**Comment by buzzdeee** [comment]
That's the part of pre-config.yaml:

```
    - data_stream:
        namespace: default
      id: http_endpoint-general_settings-959a88ae-e0be-4ee1-b3dd-556886495f7e
      meta:
        package:
            name: jamf_pro
            version: 0.1.1
      name: jamf-jamf-pro
      package_policy_id: 959a88ae-e0be-4ee1-b3dd-556886495f7e
      revision: 7
      streams:
        - data_stream:
            dataset: jamf_pro.events
            type: logs
          id: http_endpoint-jamf_pro.events-959a88ae-e0be-4ee1-b3dd-556886495f7e
          listen_address: 0.0.0.0
          listen_port: 9202
          prefix: json
          publisher_pipeline.disable_host: true
          secret.header: SECRET_HEADER
          secret.value: SECRET_VALUE
          ssl:
            certificate: /path/to/my/certificate.pem
            enabled: true
            key: /path/to/my/certificate.key
          tags:
            - forwarded
            - jamf_pro-events
          url: /jamf-pro-events
      type: http_endpoint
      use_output: default
```

above done, basically following instructions given in the Elastic docs. Note: how to configure SSL is also not overly well documented, but I took the instructions given for the Auth0 integration, and that seems to have "just worked".

Then on the Jamf side, entered this for the header authentication:
```
{"SECRET_HEADER": "SECRET_VALUE"}
```

instead of from the Elastic integrations doc suggested: 

```
{"Authorization":"SECRET_HEADER", "Token":"SECRET_VALUE"}
```

Which finally made it work.
