### ISSUE TITLE
Bring uniformity in `aws.dimensions.*` fields mapping

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#11806]
## Situation

Elastic offers multiple integrations to collect metrics from CloudWatch in the AWS integration package. 

Some are "specialized" and only collect metrics from one AWS service,  like the EC2, ECS, Redshift, and others. However, one "generic" integration allows users to write the integration configs to collect metrics from any AWS service. The generic integration is excellent for collecting metrics from services we have not supported.

All integrations (specialized and generic), collect metric dimensions as `aws.dimentions.*` fields.

## Problem

Unfortunately, not all metrics integrations use the exact mapping for the `aws.dimentions` field.

| Integration                      | Type        | Mapping for aws.dimentions |
| -------------------------------- | ----------- | ---------------------------- |
| Collect EC2 logs from CloudWatch | Specialized | `object`                     |
| Collect metrics from CloudWatch  | Generic     | `flattened`                  |

With different mappings, it's hard for users to correlate dimensions and build dashboards.

## Solution

Work in progress.

We need to identify:

- What is the best mapping to represent AWS metric dimensions
- Describe a custom mapping to work around the issue in the short term (if it exists).
- Identify a mid-long term solution to bring uniformity to dimensions field mapping.

## References

Related:

- A large migration to flattened: https://github.com/elastic/integrations/pull/8115/files

**Comment by zmoog** [comment]
For a short-term solution for users who want to map `aws.dimensions` as an `object` of `keyword`s, I tried defining a custom dynamic template in the generic integration. 

```yaml
  - name: dimensions.*
    type: object
    object_type: keyword
    object_type_mapping_type: "*"
```

However, the `aws.dimensions` takes precedence.

**Comment by zmoog** [comment]
All `*_metrics` data streams use the `object` mapping. 

For example, here is the `dimensions` definition for EC2 metrics:

```yaml
# packages/aws/data_stream/ec2_metrics/fields/fields.yml
- name: aws
  type: group
  fields:
    - name: dimensions
      type: group
      fields:
        - name: AutoScalingGroupName
          type: keyword
          dimension: true
          description: An Auto Scaling group is a collection of instances you define if you're using Auto Scaling.
        - name: ImageId
          type: keyword
          dimension: true
          description: This dimension filters the data you request for all instances running this Amazon EC2 Amazon Machine Image (AMI)
        - name: InstanceId
          type: keyword
          dimension: true
          description: Amazon EC2 instance ID
        - name: InstanceType
          type: keyword
          dimension: true
          description: This dimension filters the data you request for all instances running with this specified instance type.
```

Since ALL metrics data streams use this mapping, it probably makes sense to use the `object` type in the `cloudwatch_metrics` as well instead of the `flattened` type. We can't do the opposite since TSDB doesn't allow `dimension: true` on `flattened` type.
