### ISSUE TITLE
Remove `max_number_of_messages` for SQS+S3-based inputs

### ISSUE THREAD

**Issue by strawgate** [elastic/integrations#12101]
With https://github.com/elastic/beats/pull/40699 the max_number_of_messages setting is now ignored for SQS inputs as of 8.15. It is still exposed in integration settings. It is still relevant for <8.15.

The new setting is number_of_workers, which the SQS-based input shares with the S3 bucket polling input in integration settings.

Unfortunately, the default value for number_of_workers is just `1`. Users using an SQS-based S3 input upgrading to 8.15 agents will find that they've gone from having five workers (or whatever number they had customized it to) for processing objects to just a single worker processing objects.

We should consider one or more of the following:
1. Using the `max_number_of_messages` setting for the `number_of_workers` value if `queue_url` is present to maintain backwards compatibility while indicating that the setting will be removed in a future version.
2. Indicating that `max_number_of_messages` is no longer applicable for 8.15 and to use `number_of_workers` when using an SQS queue
3. Bumping the `number_of_workers` default value to 5

**Comment by flexitrev** [comment]
@faec What do you think we should do here since you implemented the SQS changes. I think maintaining backwards compatibility is probably the best solution, but it means incurring a little tech debt.

**Comment by faec** [comment]
> Unfortunately, the default value for number_of_workers is just 1

I assume you're referring here to the defaults in the integrations? As far as I know the [default in the input itself](https://github.com/elastic/beats/blob/0807e5b97e7707ff18ab0cc259e9e37a3b707fc0/x-pack/filebeat/input/awss3/config.go#L60) is 5 workers. Does this mean that integrations still set an explicit default of 1 for `number_of_workers` even for SQS queues where the flag was previously unsupported? Or is there a miscommunication somewhere?

> I think maintaining backwards compatibility is probably the best solution, but it means incurring a little tech debt.

I don't think there is anything to be gained by trying to recover backwards compatibility by emulating `max_number_of_messages` or similar. The reason is that the refactor fundamentally changed the meaning of "workers" in a way that makes them no longer analogous to any configuration of the old input. Removing it entirely from the configuration struct was an intentional tradeoff of the design, based on the fact that the concrete behavior of the new worker count has no equivalent in the old model.

In the new model, one "worker" means one actual worker goroutine that continually downloads and processes objects (which is probably how most users intuitively understand "number of workers"), whereas before, it meant a goroutine that would download one object and then halt all activity until the pipeline reported that that object was fully ingested upstream (meaning that "workers" were often idle even when there was still work available).

Because of this, any intentional changes that users _did_ make to `max_number_of_messages` was calibrated around a worker model that no longer exists, and will not get comparable performance with the new code. In particular, it was not uncommon for users with performance issues to set `max_number_of_messages` to 500+, which was a (reasonably effective) workaround for the limitations of the old worker model, but is _never_ advantageous with the new code, and could flood the system with too many parallel downloads.

Since there's no way for us to infer the actual behavior a user was targeting based on the old `max_number_of_messages` flag, I don't think we should try. I think it could make sense to report a warning if configurations try to use it, but I think we should fully adopt the new default of 5 workers, and make sure messaging in the integration configs focuses on appropriate ranges for that flag.

**Comment by flexitrev** [comment]
Thanks for that detail @faec. That makes me think that option 2 is the best solution. 
Our release notes in 8.16 explain that the value is ignored and what to use - https://www.elastic.co/guide/en/beats/libbeat/8.17/release-notes-8.16.0.html.

I think the best way to inform all users bump the versions of all the integrations that use the awss3 input and add a similar note to the changelog. Hopefully the note about the performance increase would encourage users to upgrade their agents. WDYT @strawgate ?

**Comment by strawgate** [comment]
Can you let me know the specific integration you're using?

**Comment by leandrojmp** [comment]
@strawgate I'm using the Cloudflare Logpush integration, the Firewall Events and HTTP Requests dataset.

I have multiple Inputs with the same configuration only the queue change, I'm share one of them here:

```
  - id: aws-s3-cloudflare-f56bb89c-97bd-441e-ae4b-071d5296cd1d
    name: cloudflare-REDACT
    revision: 6
    type: aws-s3
    use_output: c20b778c-0220-40f4-a8ca-03b974ada63b
    meta:
      package:
        name: cloudflare_logpush
        version: 1.35.0
    data_stream:
      namespace: cloudflare
    package_policy_id: f56bb89c-97bd-441e-ae4b-071d5296cd1d
    streams:
      - id: >-
          aws-s3-cloudflare_logpush.firewall_event-f56bb89c-97bd-441e-ae4b-071d5296cd1d
        data_stream:
          dataset: cloudflare_logpush.firewall_event
          type: logs
        queue_url: >-
          https://sqs.us-east-1.amazonaws.com/REDACTED
        visibility_timeout: 300s
        api_timeout: 120s
        max_number_of_messages: 70
        file_selectors:
          - regex: fw/
        access_key_id: '${SECRET_3}'
        secret_access_key: '${SECRET_4}'
        tags:
          - collect_sqs_logs
          - cloudflare-firewall
          - cloudflare-fw-REDACT
        processors:
          - drop_event:
              when:
                or:
                  - contains:
                      message: REDACTED
      - id: >-
          aws-s3-cloudflare_logpush.http_request-f56bb89c-97bd-441e-ae4b-071d5296cd1d
        data_stream:
          dataset: cloudflare_logpush.http_request
          type: logs
        queue_url: >-
          https://sqs.us-east-1.amazonaws.com/REDACTED
        visibility_timeout: 300s
        api_timeout: 120s
        max_number_of_messages: 70
        file_selectors:
          - regex: http/
        access_key_id: '${SECRET_3}'
        secret_access_key: '${SECRET_4}'
        tags:
          - collect_sqs_logs
          - cloudflare-http
          - cloudflare-http-REDACT
```

As you can see, there is the `max_number_of_messages` with the value we set, but not the number of workers, which is set in the integration.

![Image](https://github.com/user-attachments/assets/fbb7f045-a4c4-41f6-b1bb-83b30955ff8c)

Inspect the input of the integration [here](https://github.com/elastic/integrations/blob/main/packages/cloudflare_logpush/data_stream/firewall_event/agent/stream/aws-s3.yml.hbs), it seems that the `number_of_workers` setting will only get the value defined by the user only if the s3 collection of logs is enabled.

```
{{#if collect_s3_logs}}
{{! shared S3 bucket polling options }}
{{#if number_of_workers }}
number_of_workers: {{ number_of_workers }}
{{/if}}
```

Which I assume is populated by this setting in the UI:
![Image](https://github.com/user-attachments/assets/b7c6bdac-65f7-4acc-a16c-191104f3e7bf)

But since I'm using SQS, I cannot enable this setting as it will comply that bucket arn and other settings are missing.

It seems an issue on the integration, not just on the documentation.
