### ISSUE TITLE
[HAProxy] Modify Ingest Pipeline to Handle Malformed URLs

### ISSUE THREAD

**Issue by ritalwar** [elastic/integrations#12199]
The HAProxy pipeline can be updated to handle malformed URLs by adding `ignore_failure: true` to the grok processor responsible for parsing the `haproxy.http.request.raw_request_line`. This modification allows the pipeline to continue processing even when a URL does not match the expected format, preventing failure. The updated pipeline configuration would look like:

```yaml
- grok:
    field: haproxy.http.request.raw_request_line
    patterns:
      - '%{WORD:http.request.method}%{SPACE}%{URIPATHPARAM:url.original}%{SPACE}HTTP/%{NUMBER:http.version}'
    ignore_missing: true
    ignore_failure: true
    if: 'ctx.haproxy?.http?.request?.raw_request_line != null && !ctx.haproxy?.http?.request?.raw_request_line.isEmpty()'
```

While this update ensures that malformed URLs are ignored without failing the pipeline, it’s crucial to assess any potential impacts on data quality to check if ignoring parsing failures may result in incomplete or incorrect log processing.
