### ISSUE TITLE
Cisco FTD Integration missing NAT fields

### ISSUE THREAD

**Issue by paivao** [elastic/integrations#12457]
Hello, observing some Cisco events, I figured out that the NAT fields are missing from security events.

One way I think this will work is adding these parameters to the ingest pipeline, in:
https://github.com/elastic/integrations/blob/main/packages/cisco_ftd/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L1089

```yaml
      params:
        NAT_InitiatorIP:
          target: nat_src_ip
          ecs: [source.nat.ip]
        NAT_InitiatorPort:
          target: nat_src_port
          ecs: [source.nat.port]
        NAT_ResponderIP:
          target: nat_dst_ip
          ecs: [destination.nat.ip]
        NAT_ResponderPort:
          target: nat_dst_port
          ecs: [destination.nat.port]
```
