### ISSUE TITLE
[Elasticsearch]: Ingest pipeline created to process Elasticserver logs truncates log messages

### ISSUE THREAD

**Issue by kvalliyurnatt** [elastic/integrations#12501]
### Integration Name

Elasticsearch [elasticsearch]

### Integration Version

1.16.0

### Agent Version

8.17.0

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.17.0

### OS Version and Architecture

cloud

### Event Original

```
{"@timestamp":"2025-01-22T15:50:04.517Z", "log.level": "INFO", "message":"[co.elastic.elasticsearch.metering.sampling.SampledStorageMetricsProvider] is not ready for collect yet", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es-es-search-c886b6975-9tsbz][metering_reporter][T#1]","log.logger":"co.elastic.elasticsearch.metering.usagereports.UsageReportCollector","elasticsearch.cluster.uuid":"vaYFhXk-Q0WFOdSjyaylnA","elasticsearch.node.id":"fnqA_AXpTFm6uZdtXDNIPA","elasticsearch.node.name":"es-es-search-c886b6975-9tsbz","elasticsearch.cluster.name":"es"}
```

### What did you do?

```
inputs:
  # Logs: Collect audit, deprecation, gc, server and slowlog logs from Elasticsearch instances
  - id: elasticsearch-logfile
    type: logfile
    streams:
      # Audit logs: Collect Elasticsearch audit logs using log input
      - id: logfile-elasticsearch.audit
        data_stream:
          dataset: elasticsearch.audit
          type: logs
        paths:
          - /var/log/elasticsearch/*_audit.json
        exclude_files:
          - .gz$
        processors:
          - add_locale: null
          - add_fields:
              target: ''
              fields:
                ecs.version: 1.10.0
          - decode_json_fields:
              fields:
                - message
              target: _json
          - rename:
              fields:
                - from: _json.request.body
                  to: _request
              ignore_missing: true
          - drop_fields:
              fields:
                - _json
          - detect_mime_type:
              field: _request
              target: http.request.mime_type
          - drop_fields:
              fields:
                - _request
              ignore_missing: true
        # condition: <CONDITION> # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Deprecation logs: Collect Elasticsearch deprecation logs using log input
      - id: logfile-elasticsearch.deprecation
        data_stream:
          dataset: elasticsearch.deprecation
          type: logs
        paths:
          - /var/log/elasticsearch/*_deprecation.json
        exclude_files:
          - .gz$
          - _slowlog.log$
          - _access.log$
        # condition: <CONDITION> # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Garbage Collection logs: Collect Elasticsearch gc logs using log input
      - id: logfile-elasticsearch.gc
        data_stream:
          dataset: elasticsearch.gc
          type: logs
        paths:
          - '/var/log/elasticsearch/gc.log.[0-9]*'
          - /var/log/elasticsearch/gc.log
        exclude_files:
          - .gz$
        exclude_lines:
          - '^(OpenJDK|Java HotSpot).* Server VM '
          - '^CommandLine flags: '
          - '^Memory: '
          - '^{'
        multiline:
          pattern: '^(\[?[0-9]{4}-[0-9]{2}-[0-9]{2}|{)'
          negate: true
          match: after
        processors:
          - add_fields:
              target: ''
              fields:
                ecs.version: 1.10.0
        # condition: <CONDITION> # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Server logs: Collect server logs using log input
      - id: logfile-elasticsearch.server
        data_stream:
          dataset: elasticsearch.server
          type: logs
        paths:
          - /var/log/elasticsearch/*_server.json
        exclude_files:
          - .gz$
          - _slowlog.log$
          - _access.log$
          - _deprecation.log$
        # condition: <CONDITION> # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Slowlog logs: Collect Elasticsearch slowlog logs using log input
      - id: logfile-elasticsearch.slowlog
        data_stream:
          dataset: elasticsearch.slowlog
          type: logs
        paths:
          - /var/log/elasticsearch/*_index_search_slowlog.json
          - /var/log/elasticsearch/*_index_indexing_slowlog.json
        exclude_files:
          - .gz$
        # condition: <CONDITION> # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
  # Metrics (Stack Monitoring): Collect index, CCR, cluster stats, machine learning and node metrics from Elasticsearch instances to power the Stack Monitoring application in Kibana
  - id: elasticsearch-elasticsearch/metrics
    type: elasticsearch/metrics
    streams:
      # CCR metrics: Collect Elasticsearch Cross Cluster Replication metrics
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.ccr
        data_stream:
          dataset: elasticsearch.stack_monitoring.ccr
          type: metrics
        metricsets:
          - ccr
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Cluster stats: Collect Elasticsearch cluster wide metrics
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.cluster_stats
        data_stream:
          dataset: elasticsearch.stack_monitoring.cluster_stats
          type: metrics
        metricsets:
          - cluster_stats
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Enrich policies metrics: Collect Elasticsearch enrich policies stats
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.enrich
        data_stream:
          dataset: elasticsearch.stack_monitoring.enrich
          type: metrics
        metricsets:
          - enrich
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Index metrics: Collect Elasticsearch index metrics
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.index
        data_stream:
          dataset: elasticsearch.stack_monitoring.index
          type: metrics
        metricsets:
          - index
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Index recovery metrics: Returns information about ongoing and completed shard recoveries for one or more indices.
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.index_recovery
        data_stream:
          dataset: elasticsearch.stack_monitoring.index_recovery
          type: metrics
        metricsets:
          - index_recovery
        hosts:
          - 'http://localhost:9200'
        index_recovery.active_only: true
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Index summary metrics: Collect summaries of Elasticsearch index metrics
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.index_summary
        data_stream:
          dataset: elasticsearch.stack_monitoring.index_summary
          type: metrics
        metricsets:
          - index_summary
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Ingest Pipeline metrics: Collect metrics on Ingest Pipelines
      - id: elasticsearch/metrics-elasticsearch.ingest_pipeline
        data_stream:
          dataset: elasticsearch.ingest_pipeline
          type: metrics
        metricsets:
          - ingest_pipeline
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: null
        timeout: 10s
        ssl: null
        ingest_pipeline.processor_sample_rate: 0.25
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Anomaly detection machine learning job metrics: Collect usage information for anomaly detection Machine Learning jobs
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.ml_job
        data_stream:
          dataset: elasticsearch.stack_monitoring.ml_job
          type: metrics
        metricsets:
          - ml_job
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Node metrics: Collect node metrics from Elasticsearch
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.node
        data_stream:
          dataset: elasticsearch.stack_monitoring.node
          type: metrics
        metricsets:
          - node
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Cluster nodes statistics: Collect node stats from Elasticsearch
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.node_stats
        data_stream:
          dataset: elasticsearch.stack_monitoring.node_stats
          type: metrics
        metricsets:
          - node_stats
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Pending tasks metrics: Collect cluster-level changes that have not yet been executed.
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.pending_tasks
        data_stream:
          dataset: elasticsearch.stack_monitoring.pending_tasks
          type: metrics
        metricsets:
          - pending_tasks
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
        # tags:
        #  - <TAGS> # Tags
      # Shards metrics: Collect Elasticsearch shard metrics
      - id: elasticsearch/metrics-elasticsearch.stack_monitoring.shard
        data_stream:
          dataset: elasticsearch.stack_monitoring.shard
          type: metrics
        metricsets:
          - shard
        hosts:
          - 'http://localhost:9200'
        scope: node
        period: 10s
        timeout: 10s
        ssl: null
        # username: <USERNAME> # Username: Use when connecting to elasticsearch
        # password: <PASSWORD> # Password: Use when connecting to elasticsearch
        # api_key: <API_KEY> # API Key: Elasticsearch API Key in Beats format. Use when connecting to elasticsearch in place of username/password.
        # condition: '${kubernetes_leaderelection.leader} == true and <CONDITION>' # Condition: Condition to filter when to collect this input
```

### What did you see?

We are seeing the message field get truncated if it begins with a `[]`. The text in the `[]` is being moved to a field called `elasticsearch.index.name` 

This seems to be because of the grok pattern defined here: https://github.com/elastic/integrations/blob/main/packages/elasticsearch/data_stream/server/elasticsearch/ingest_pipeline/pipeline-json.yml

That moves things inside the [] as an index name

### What did you expect to see?

We expected messages that begin with []  to be retained within the message field.
