### ISSUE TITLE
[Question]: AWS Dynamodb data not generating under Data Streams tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/integrations#1294]
**Description:**
We added AWS dynamodb integration to default policy, however we are not able to see any data related to same under Data Streams tab.
Do we need any AWS setup/credentials to get AWS Dynamodb data?
Please let us know if are missing anything.

**Reference Ticket:**
https://github.com/elastic/kibana/issues/93315

**Build details 7.14.0 Snapshot:**
```
Build: 42333
Commit: d2904ca073e91582a2c5fa6ef6e712491cf3521f
```

**Screenshots:**
![Aws Data](https://user-images.githubusercontent.com/77374876/124751473-4b5ba700-df44-11eb-8e52-7565234a09ff.jpg)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @jen-huang 

CC: @EricDavisX

**Comment by jen-huang** [comment]
> Do we need any AWS setup/credentials to get AWS Dynamodb data?

Yes, @kaiyan-sheng, can you provide guidance on getting AWS data?

**Comment by kaiyan-sheng** [comment]
I created a 7.14 cloud instance and added AWS Dynamodb integration. I was able to see data under data streams:
<img width="1261" alt="Screen Shot 2021-07-08 at 3 01 30 PM" src="https://user-images.githubusercontent.com/14081635/124990562-1ef27880-e073-11eb-9152-0f8efc00df30.png">

Here is the agent policy I used:
```
inputs:
  - id: ad02c2de-86b9-4359-bf99-860e49e37b1f
    name: aws-1
    revision: 2
    type: aws/metrics
    use_output: default
    meta:
      package:
        name: aws
        version: 0.8.0
    data_stream:
      namespace: default
    streams:
      - id: aws/metrics-aws.dynamodb-ad02c2de-86b9-4359-bf99-860e49e37b1f
        data_stream:
          dataset: aws.dynamodb
          type: metrics
        access_key_id: foo
        session_token: >-
          bar
        period: 5m
        tags_filter: null
        metricsets:
          - dynamodb
        secret_access_key: foobar
```
