### ISSUE TITLE
[Azure Firewall]: Unable to config the integration via eck-stack chart

### ISSUE THREAD

**Issue by perpective2410** [elastic/integrations#13430]
### Integration Name

Azure Firewall Logs

### Integration Version

1.23.0

### Agent Version

8.17.4

### Elasticsearch Version

8.17.4

### OS Version and Architecture

Ubuntu

### Error Message

Following https://github.com/elastic/integrations/issues/11540 which is now closed, I am creating a new issue as I believe there is a bug to configure the Kibana CRD.

If we configure the integration like the following

```
- name: Elastic Agent on ECK policy 1
    id: eck-agent-1
    namespace: default
    monitoring_enabled:
      - logs
      - metrics
    unenroll_timeout: 900
    package_policies:
      - name: eck_agent-1
        id: eck_agent-1
        package:
          name: system
      - name: azure_firewall_logs_integration-1
        id: azure_firewall_logs_integration-1
        package:
          name: azure
        vars:
          connection_string: "Endpoint=sb://redacted"
          eventhub: "redacted"
          consumer_group: "$Default"
          storage_account: "redacted"
          storage_account_key: "redacted"
        inputs:
          firewall_logs-azure-eventhub:
            enabled: true
            streams:
              '[azure.firewall_logs]':
                enabled: true
```
The generated kibana.yaml looks like this (notice how the key is truncated where we have the dot)

```
            - id: azure_firewall_logs_integration-1
                  inputs:
                    firewall_logs-azure-eventhub:
                        enabled: true
                        streams:
                            '[azure':
                                firewall_logs]:
                                    enabled: true
                  name: azure_firewall_logs_integration-1
                  package:
                    name: azure
                  vars:
                    connection_string: Endpoint=sb://redacted
                    consumer_group: $Default
                    eventhub: redacted
                    storage_account: redacted
                    storage_account_key: redacted
```

Because of this, kibana fails to starts

Is there a way to escape it?

Might be related to this: https://github.com/elastic/kibana/issues/178114

Many thanks

### Event Original

See above

### What did you do?

 See above

### What did you see?

See above

### What did you expect to see?

See above
