### ISSUE TITLE
[Integration Name]: Chain input not functional, template error?

### ISSUE THREAD

**Issue by cp-elastic** [elastic/integrations#13572]
### Integration Name

Custom API [httpjson]

### Dataset Name

httpjson.generic

### Integration Version

1.22.0

### Agent Version

8.17.4

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.17.4

### OS Version and Architecture

Debian 12.10

### Error Message

```
Error while processing http request: error while getting keys: parsing error: 	 - 1:1 unexpected EOF while scanning extensions
```

### What did you do?

Configured a `Chain` in the integration configuration under Advanced Settings.
When using flat JSON as follows:
```
chain.0.step.request.url: https://api.ui.com/v1/hosts/<redacted>
chain.0.step.request.method: GET
chain.0.step.request.transforms.0.set.target: header.X-API-KEY
chain.0.step.request.transforms.0.set.value: '<redacted>'
```
Or structured JSON as follows:
```
 - step:
    request:
        url: https://api.ui.com/v1/hosts/<redacted>
        method: GET
        transforms:
          set:
              target: header.X-API-KEY
              value: '<redacted>'
```
The error message above is displayed.

However, when omitting the  `-` in ` - step:`, no error is thrown, but the step does not appear to be executed, no request is shown in request traces or logs.

### What did you see?

When using flat JSON or structured JSON, the rendered config is as follows:
```
name: httpjson-1
package_policy_id: 0d14d948-e46d-4f48-a203-db47570ca0b4
revision: 19
streams:
- chain:
  - step:
      request:
        method: GET
        transform:
        - set:
            target: header.X-API-KEY
            value: <redacted>
        url: https://api.ui.com/v1/hosts/<redacted>
  config_version: 2
  data_stream:
    dataset: unifi-console
  id: httpjson-httpjson.generic-0d14d948-e46d-4f48-a203-db47570ca0b4
  interval: 1m
  publisher_pipeline:
    disable_host: true
  request:
    method: GET
    transforms:
    - set:
        target: header.X-API-KEY
        value: <redacted>
    url: https://api.ui.com/v1/devices
  tags:
  - forwarded
type: httpjson
use_output: default
```

I believe the hyphen in `- chain:` may be the issue, as that doesn't appear in the [Filebeat Input](https://www.elastic.co/docs/reference/beats/filebeat/filebeat-input-httpjson#chain-step-replace) docs

When omitting the hyphen in the Chain config, as in using `step:`, the config is rendered as follows:
```
name: httpjson-1
package_policy_id: 0d14d948-e46d-4f48-a203-db47570ca0b4
revision: 54
streams:
- chain: null
  config_version: 2
  data_stream:
    dataset: httpjson.generic
  id: httpjson-httpjson.generic-0d14d948-e46d-4f48-a203-db47570ca0b4
  interval: 1m
  publisher_pipeline:
    disable_host: true
  request:
    method: GET
    transforms:
    - set:
        target: header.X-API-KEY
        value: <redacted>
    url: https://api.ui.com/v1/devices
  step:
    request:
      method: GET
      transforms:
      - set:
          target: header.X-API-KEY
          value: <redacted>
      url: https://api.ui.com/v1/hosts/<redacted>
  tags:
  - forwarded
type: httpjson
use_output: default
```

And this is the version of the config that doesn't throw errors, but also does not appear to be run at all per the logs and request traces.

### What did you expect to see?

I'd expect the Chain setting for the Custom API input to be functional. Also a side note, Custom API with CEL was considered as an alternative, but doesn't appear to support setting header values required for API authentication via the Integration config UI.

### Anything else?

As a point of comparison, the Rapid7 Threat Threat Command integration renders its config as follows, but I cannot confirm if it works or not at this point:
```
name: ti_rapid7_threat_command-1
package_policy_id: 9eef393f-581a-4540-9af6-e7d836d63203
revision: 1
streams:
- chain:
  - step:
      replace: $[:]
      request:
        method: GET
        ssl: null
        timeout: 60s
        transforms:
        - set:
            target: header.Authorization
            value: <REDACTED>
        url: https://api.intsights.com/public/v1/data/alerts/get-complete-alert/$[:]
```
