### ISSUE TITLE
[BUG] Enable Request Tracer Defaults to null causing request tracing to be collected

### ISSUE THREAD

**Issue by btrieger** [elastic/integrations#13710]
With the change to enable request tracer to allow the removal of old trace logs it appears that as no default is set for the variable enable_request_tracer that it is getting set to null. This is causing the request tracer to still be enabled as it has other fields resulting in request tracing to be inadvertently be left on. 

My google workspace integration logs were being flooded with ```write error: write length 1108655 exceeds maximum file size 1048576```. 

The UI shows that request tracing is set to false but an agent diagnostic shows http trace files still being generated. The computed config appears as below:

```
          request:
            tracer:
                enabled: null
                filename: ../../logs/httpjson/http-request-trace-*.ndjson
                maxbackups: 5
```

Upon flipping it to true and then back to false in the UI. A change was detected and I reapplied the agent policy. A subsequent diagnostic showed the tracer logs were removed and the error stopped being generated.

I believe the bug was introduced in this PR #13035
