### ISSUE TITLE
[trend_micro_vision_one]: missing required field accessing 'resource.url'

### ISSUE THREAD

**Issue by ipsec** [elastic/integrations#14094]
### Integration Name

Trend Micro Vision One [trend_micro_vision_one]

### Integration Version

2.2.0

### Agent Version

8.18.1

### Agent Output Type

elasticsearch

### Elasticsearch Version

8.18.1

### OS Version and Architecture

SUSE Linux Enterprise Server 15 SP5

### Error Message

missing required field accessing 'resource.url'

### What did you do?

Upgrade from 2.1.0 to 2.2.0.

### What did you see?

![Image](https://github.com/user-attachments/assets/7df3e5fb-9751-42ce-99da-69300f10d0ff)

### What did you expect to see?

No error.

### Anything else?

Was working in 2.1.0

**Comment by efd6** [comment]
~@ipsec Which data stream is this for?~ By exclusion it must be telemetry.

**Comment by efd6** [comment]
@ipsec Please take a look at the pre-config.yaml in a diagnostic bundle from the agent that is complaining of this. You should see something like
```
    - data_stream:
        namespace: "59948"
      id: cel-trend_micro_vision_one-<UUID>
      meta:
        package:
            name: trend_micro_vision_one
            version: 2.2.0
      name: trend_micro_vision_one-telemetry-59948
      package_policy_id: <UUID>
      revision: 1
      streams:
        - config_version: 2
          data_stream:
            dataset: trend_micro_vision_one.telemetry
            type: logs
          fields_under_root: true
          id: cel-trend_micro_vision_one.telemetry-<UUID>
          interval: 15m
          keep_null: true
          program: |4
<SNIP>
          publisher_pipeline:
            disable_host: true
          redact:
            fields:
                - api_token
          resource:
            ssl: null
            timeout: 30s
            tracer:
                enabled: true
                filename: ../../logs/cel/http-request-trace-*.ndjson
                maxbackups: 5
            url: http://svc-trend_micro_vision_one:8080
          state:
            api_token: <REDACTED>
            initial_interval: 2h
            managed_pipeline_description: managed-by-elastic-integrations-trend_micro_vision_one-telemetry
            max_recency: 30s
            max_time_range: 1h
            min_time_range: 10m
            registration_count: 0
            top: 500
            want_more: false
          tags:
            - preserve_original_event
            - preserve_duplicate_custom_fields
            - forwarded
            - trend_micro_vision_one-telemetry
```
Can you confirm that the `inputs.streams.resource.url` for the data stream `trend_micro_vision_one.telemetry` has a value? (in the example above it is `http://svc-trend_micro_vision_one:8080`)
