### ISSUE TITLE
[Feature] System Integration Filters

### ISSUE THREAD

**Issue by bm11100** [elastic/integrations#1632]
As reported [here](https://discuss.elastic.co/t/system-integration-filters/283588), for the System integration for elastic-agent, I was curious if we could filter by log level, or eliminate various Event ID's that we may not want to collect due to noise. Collection of all informational logs at scale is just too much.

In beats, we could specify the informational level and also use a processor for event ID's to drop, but I am not seeing that in the options for the built in System integration.

Can we get that feature added to the integration as well?

**Comment by oleksandryz** [comment]
I tested filter for event id by edit the file state.yml file (located under data/elastic-agent-*) contains the entire, unencrypted policy.
Added "event_id: 4688":
```
      streams:
      - condition: ${host.platform} == 'windows'
        data_stream:
          dataset: system.security
          type: logs
        id: winlog-system.security-32f24874-7509-3414-fe49-d3b67f032f37
        name: Security
        tags: null
        event_id: 4688
```
It looks like filtering works on  the  agent side and what only need it is add this possibility to the page in kibana Fleet>Agent policies>Policy Name>Edit integration
