### ISSUE TITLE
[sophos] XG - sent_bytes bug

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#2158]
Our pipeline looks for `sent_bytes` within Sophos XG logs, but Sophos actually uses `bytes_sent`- can we update our pipeline to correctly parse `bytes_sent`. More information, including sample messages in this Discuss post: https://discuss.elastic.co/t/es-7-15-filebeats-sophos-xg-module-not-separating-data-into-variables/288577/15

**Comment by samywee** [comment]
This is not only limited to sent_bytes. All following need addressed and these are all numeric fields ; 
```
sent_bytes --change-to --> bytes_sent
bytes_received --change-to --> bytes_received
sent_pkts --change-to --> packets_sent
recv_pkts --change-to --> packets_received
```

There are multiple files in the filebeat/module/sophos/xg/ingest module to change  with above change. (find replace should work); 

```
antispam.yml
antivirus.yml
cfilter.yml
event.yml
firewall.yml
```

In additionl there may be some unused variables in these .yml files in the pipeline, that might need careful deep-dive. 

I also see this sample logs in github do not match current version log format - need a new sample log for testing. ; 
https://github.com/elastic/integrations/blob/master/packages/sophos/_dev/deploy/docker/sample_logs/sophos-xg.log

**Comment by samywee** [comment]
Attached 2 files that you can use for testing ; (File found at https://github.com/elastic/integrations/blob/master/packages/sophos/_dev/deploy/docker/sample_logs/sophos-xg.log is old format. )

One file is for pipeline testing of firewall.yml. Other file is for pipeline testing of cfilter.yml
[sophos.xg.firewall.log](https://github.com/elastic/integrations/files/7542487/sophos.xg.firewall.log)
[sophos.xg.cfilter.log](https://github.com/elastic/integrations/files/7542485/sophos.xg.cfilter.log)

**Comment by samywee** [comment]
Also finding cfilter.yml file is missing required steps to convert, bytes_received and bytes_sent fields to number ;  This file located in filebeat/module/sophos/xg/ingest/cfilter.yml  ; Without this incoming bytes_recived and bytes_sent will not be converted to a numeric during ingest. (Not sure why easy to understand field bytes_received is renamed to destination.bytes - must be some standard - beyond my knowledge)

They need following 
```
- convert:
    field: sophos.xg.bytes_received
    target_field: destination.bytes
    type: long
    ignore_failure: true
    ignore_missing: true
    if: "ctx.sophos?.xg?.bytes_received != null"
- convert:
    field: sophos.xg.bytes_sent
    target_field: source.bytes
    type: long
    ignore_failure: true
    ignore_missing: true
    if: "ctx.sophos?.xg?.bytes_sent != null"
```
