### ISSUE TITLE
Optimize index settings for synthetics

### ISSUE THREAD

**Issue by andrewvc** [elastic/integrations#2196]
The current mappings for this integration consume far too much space for network data in particular. Network data takes up the vast majority of Elasticsearch storage space in most cases. There are a number of sub-optimal things about our mappings, for network data in particular. Fixing these has yielded a 50% reduction in storage space in some ad-hoc tests.

The main problems with the current mapping are:

1. Dynamic mappings are enabled, and there are a number of fields sent by heartbeat that are not part of the explicit mapping. Auto-mapping these takes up a large quantity of space. Some such fields are individual HTTP headers.
2. Compression can be bumped up to `best_compression` since this is a write-heavy, read-light index
3. Index sorting can be enabled. Sorting the index by similar data puts similar docs in adjoining spots on disk, which makes them wind up grouped together in compression blocks making compression vastly more efficient.
4. In the future we should curate the list of fields more thoroughly and index only the minimum number, but to start with let's pick the low hanging fruit.

The following index settings should be sufficient. I tried adding them to [synthetics/manifest.yml](https://github.com/elastic/integrations/blob/master/packages/synthetics/manifest.yml) but that did not seem to actually affect the templates.

```
elasticsearch:
  index_template:
    mappings:
      dynamic: false
    settings:
      index:
        codec: best_compression
        sort.field: 
        - "url.full"
        - "http.request.url"
        - "http.response.headers.etag"
        - "monitor.id"
```
