### ISSUE TITLE
Support parsing json logs with kubernetes integration

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#2313]
Currently we use filestream input to parse logs coming from k8s containers. We need to [enhance](https://elastic.slack.com/archives/CJZ9U5G9X/p1638200313453800) k8s package to also provide option for parsing json logs like at https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html#_parsing_json_logs. 

Something like the following could do the trick here:
```
parsers:
 - container: ~
 - ndjson:
    keys_under_root: true
# etc....
```
