### ISSUE TITLE
Windows integration missing feature to filter out service metrics

### ISSUE THREAD

**Issue by iamsuganthi** [elastic/integrations#2359]
There's no way to filter out windows service metrics from the UI for Windows integration. It is possible to do that with beats at the moment. 
![Screen Shot 2021-12-20 at 3 35 43 pm](https://user-images.githubusercontent.com/640748/146712527-1a6afdba-c244-4662-a5f4-988389b1c117.png)

Windows perfmon metrics has the text area to enter "Perfmon queries". Can we add a similar section for "windows service metrics queries"?

**Comment by masci** [comment]
There's a substantial difference with the way perfmon metrics are gathered so I would implement this feature by letting the user specify an allow/deny list with one or more regex in the config file, matching the name of the service.

Example:
```
- module: windows
  metricsets: ["service"]
  enabled: true
  period: 60s
  service.names:
    allow:
      - "^Foo.+"
      - "^Bar.+"
    deny:
      - "FooService123"
```
