### ISSUE TITLE
[suricata] destination.ip not set from destination.address

### ISSUE THREAD

**Issue by andrewkroh** [elastic/integrations#2558]
There is a logic bug in the suricata pipeline that prevents `destination.ip` from being set.

https://github.com/elastic/integrations/blob/2f6350814be8eacf57ffbdc03a9a18673d8e4bf5/packages/suricata/data_stream/eve/elasticsearch/ingest_pipeline/default.yml#L42-L45

The `if` condition should be looking at `destination.address` rather than `destination.ip`. But a better resolution would be to use a `convert` processor with `type: ip` to validate the data (the same applies to `source.ip`). For example:

```
- convert:
    field: destination.address
    target_field: destination.ip
    type: ip
    ignore_failure: true
```
