### ISSUE TITLE
[Enhancement] Add ECS `host` mappings to synthetics data streams

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#2716]
## Proposal

Add `host` ECS field mappings to the synthetics' integration data streams.

## Reason

Currently, the synthetics' integration data streams don't have the `host` ECS field mappings. This limits the functionality of some of the things that may be useful for linking synthetics with other types of integrations/data sets.

#### Example 1 - Remote ICMP

Currently if I want to monitor a host remotely to see if it is reachable/online, I will setup a remote Agent with the ICMP integration which pings said host. This works well from a Kibana Uptime dashboard perspective as the goal is to really just see the monitor. 

However, if I want to have a regular dashboard which shows more information about the host, generally, I'd pivot off something like `host.name`, since the ICMP doesn't by default populate this field, I can add it via a processor:

```yaml
- copy_fields:
    fields:
      - from: url.domain
         to: host.domain
      - from: url.domain
         to: host.name
      - from: url.domain
         to: host.hostname
    fail_on_error: false
    ignore_missing: true
```

However, since the synthetics' data stream templates don't have the `host` ECS field mappings, this doesn't work out of the box. I then need to do some even more work to modify the individual `@custom` component templates for each of the different integration data sets for these fields to be usable.

#### Example 2 - Geo Info

Somewhat of an extension to the first example; but if I want to monitor host(s) from multiple location, I can set things like `observer.geo` to know where my observers are. However, if I want to expand this even further to also include `host.geo` I run into the same issue as example 1, where I can easily add the geo data (either via a processor, or an ingest geo pipeline), but I can't easily use it as the integrations are missing the needed mappings.
