### ISSUE TITLE
Zscaler ZIA Web - Pipeline failures for certain logs

### ISSUE THREAD

**Issue by kevinserafin** [elastic/integrations#3007]
Hello! We have been working on migrating from the filebeat module to the new integration and wanted to provide some feedback based on what we have seen come through the logs. Happy to put in a PR and supply more sanitized logs but figured I would post this first.

1. JSON parser is unreliable since NSS does not natively leverage JSON - users will run into unescaped characters.

`{ "sourcetype" : "zscalernss-web", "event" :{"time":"Wed Apr  6 03:15:32 2022","login":"test.user@here.com","proto":"HTTPS","eurl":"d.joinhoney.com/v3?operationName=merchant_getFeatureMonitors&variables={"platform":"ext","version":"14.7.0"}","action":"Allowed","appname":"AppName","appclass":"Business","reqsize":"1257","respsize":"226","stime":"1","ctime":"1","urlclass":"Business Use","urlsupercat":"Internet Communication","urlcat":"Internet Services","malwarecat":"None","threatname":"None","riskscore":"0","dlpeng":"None","dlpdict":"None","location":"User Location","dept":"Department","cip":"192.168.0.1","sip":"13.1.6.3","reqmethod":"GET","respcode":"304","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36","ereferer":"None","ruletype":"None","rulelabel":"None","contenttype":"Other","unscannabletype":"None","deviceowner":"usersname","devicehostname":"computer1","host":"d.joinhoney.com"}}`

We fought with this quite a bit but ended up just leveraging grok in lieu of the JSON parser since we are know the exact format that is set via the NSS. We used the following grok processor to minimize changes to the rest of the pipeline:

```json
{
  "grok" : {
    "field" : "event.original",
    "patterns" : [
      """{ "sourcetype" : "zscalernss-web", "event" :{"time":"%{DATA:resp.event.time}","login":"%{DATA:resp.event.login}","proto":"%{DATA:resp.event.proto}","eurl":"%{DATA:resp.event.eurl}","action":"%{DATA:resp.event.action}","appname":"%{DATA:resp.event.appname}","appclass":"%{DATA:resp.event.appclass}","reqsize":"%{DATA:resp.event.reqsize}","respsize":"%{DATA:resp.event.respsize}","stime":"%{DATA:resp.event.stime}","ctime":"%{DATA:resp.event.ctime}","urlclass":"%{DATA:resp.event.urlclass}","urlsupercat":"%{DATA:resp.event.urlsupercat}","urlcat":"%{DATA:resp.event.urlcat}","malwarecat":"%{DATA:resp.event.malwarecat}","threatname":"%{DATA:resp.event.threatname}","riskscore":"%{DATA:resp.event.riskscore}","dlpeng":"%{DATA:resp.event.dlpeng}","dlpdict":"%{DATA:resp.event.dlpdict}","location":"%{DATA:resp.event.location}","dept":"%{DATA:resp.event.dept}","cip":"%{DATA:resp.event.cip}","sip":"%{DATA:resp.event.sip}","reqmethod":"%{DATA:resp.event.reqmethod}","respcode":"%{DATA:resp.event.respcode}","ua":"%{DATA:resp.event.ua}","ereferer":"%{DATA:resp.event.ereferer}","ruletype":"%{DATA:resp.event.ruletype}","rulelabel":"%{DATA:resp.event.rulelabel}","contenttype":"%{DATA:resp.event.contenttype}","unscannabletype":"%{DATA:resp.event.unscannabletype}","deviceowner":"%{DATA:resp.event.deviceowner}","devicehostname":"%{DATA:resp.event.devicehostname}"}}"""
    ],
    "ignore_missing" : true
  }
}
```  
  
2. The uri_parts processor does not fully/correctly parse Zscaler URLs as they do not include a scheme. While not a huge deal, it does prevent url.host from being populated as well as has some oddities when the URL has a port in it. We used a few Set processors to prepend the scheme for the bulk of the events based on the network.protocol value. Not the cleanest way but this covered ~90% of our events:

```yml
  - set:
      field: json.eurl
      value: "https://{{{json.eurl}}}"
      if: "ctx?.network?.protocol == 'ssl' || ctx?.network?.protocol == 'https'"
      ignore_missing: true
      ignore_failure: true

  - set:
      field: json.eurl
      value: "http://{{{json.eurl}}}"
      if: "ctx?.network?.protocol == 'http'"
      ignore_missing: true
      ignore_failure: true

  - set:
      field: json.eurl
      value: "unk://{{{json.eurl}}}"
      if: "ctx?.network?.protocol != 'ssl' && ctx?.network?.protocol != 'https' && ctx?.network?.protocol != 'http'"
      ignore_missing: true
      ignore_failure: true
```

3. The urldecode processor stops the pipeline when handling malformed URLs. Some of the URLs we have seen for ad networks and video streaming sites use unencoded characters in parameters. We set the `ignore_failure: true` setting to let the pipeline finish what it can.

`{ "sourcetype" : "zscalernss-web", "event" :{"time":"Wed Apr  6 03:04:57 2022","login":"test.user@here.com","proto":"HTTPS","eurl":"some.website.com/ca?aid=bbms01&pid=butler01&cid=21_12_%epid!&js=st_2","action":"Allowed","appname":"AppName","appclass":"Business","reqsize":"604","respsize":"12028","stime":"14","ctime":"54","urlclass":"Business Use","urlsupercat":"Business and Economy","urlcat":"Professional Services","malwarecat":"None","threatname":"None","riskscore":"10","dlpeng":"None","dlpdict":"None","location":"User Location","dept":"Department","cip":"10.0.0.2","sip":"13.1.22.8","reqmethod":"GET","respcode":"200","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29","ereferer":"www.msn.com/","ruletype":"None","rulelabel":"None","contenttype":"text/javascript","unscannabletype":"None","deviceowner":"usersname","devicehostname":"computer1","host":"some.website.com"}}`

4. I think this may depend on the Zscaler implementation and the users IDP, but the user.email field is mapped from the login variable. It would be helpful to map it to user.name like in the Azure integration but this may be more our preference than others.

```yml
  - grok:
      field: user.email
      patterns:
        - '%{USERNAME:user.name}@%{HOSTNAME:user.domain}'
        - '%{GREEDYDATA:user.name}'
      ignore_missing: true
      ignore_failure: true
```
