### ISSUE TITLE
[Prometheus Integration] Evaluate Prometheus endpoint Metrics extraction with k8s

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#3487]
Currently Prometheus Integration is in [0.7.0 Technical Preview ](https://docs.elastic.co/en/integrations/prometheus).

The goal of this issue is to evaluate current situation for the integration and evaluate the metric extraction from a specific Prometheus endpoint
In more details evaluate K8s metrics extraction by using such configuration.

Existing Prometheus Metricbeat Module:
https://www.elastic.co/guide/en/beats/metricbeat/8.2/metricbeat-module-prometheus.html

Evaluate:
- K8s metrics extraction
- OOTB Dashboard validation
- Test below parameters especially diffrent filters from UI:
```#metrics_filters:
#  include: []
#  exclude: []
#username: "user"
#password: "secret"
```

Outcome of the issue:
- [ ] get documented `How to run elastic-agent standalone to get metrics from Prometheus endpoint`

Relevant tickets related with this:
a. https://github.com/elastic/integrations/issues/3488
b. https://github.com/elastic/integrations/issues/3489

**Comment by tetianakravchenko** [comment]
## Restrictions: elastic-agent standalone only
I have prometheus running in k8s, I want to install elastic-agent that would get metrics from prometheus.

The main issue here: now it is only possible in elastic-agent in [standalone](https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html) mode. To use predefined integration - prometheus integration, should be used autodiscover like in this example - [doc](https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html#_autodiscover_targeted_pods).

Adding support in UI to enable different modules, equal to [this standalone config ](https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html#_autodiscover_targeted_pods)- is a more generic topic, we have an open issue somewhere for this.

So there is no way for some evaluation points, like `Test below parameters especially diffrent filters from UI`.
For `OOTB Dashboard validation` I can install prometheus integration first to install index template, kibana dashboards. And then start standalone elastic-agent with proper configuration.

## Current situation.
We do already have prometheus integration https://github.com/elastic/integrations/tree/main/packages/prometheus, that supports collecting metrics from a Prometheus endpoint (`collector` data_stream).

### Evaluation points
K8s metrics extraction
- all metrics exposed by the prometheus server `/metrics` endpoint will be scraped by default, even the `go_*` metrics
OOTB Dashboard validation
- In case of installing prometheus integration first, only one promethues overview dashboard is available:
<img width="1788" alt="Screenshot 2022-06-21 at 21 46 39" src="https://user-images.githubusercontent.com/28299531/174885318-cf263357-63a1-44e5-8c98-ef25e14593e4.png">

Test below parameters especially diffrent filters from UI:
TODO:
- [ ] check `metrics_filters`
- [ ] check credentials


### How to run elastic-agent standalone to get metrics from Prometheus endpoint.
1. Install prometheus server:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install prometheus-server prometheus-community/prometheus
```
2. Deploy elastic-agent standalone with next configuration:
```
outputs:
  default:
    type: elasticsearch
    hosts:
      - >-
        ${ES_HOST}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
agent:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
providers.kubernetes:
  node: ${NODE_NAME}
  scope: node
inputs:
  - name: prometheus
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 0.7.0
    data_stream:
      namespace: default
    streams:
      - data_stream:
          dataset: prometheus.collector
          type: metrics
        metricsets:
          - collector
        hosts:
          - '${kubernetes.pod.ip}:9090'
        period: 10s
        # metrics_path: /metrics
        # metrics_filters:
        #  include: []
        #  exclude: []
        # username: "user"
        # password: "secret"
        #bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        #ssl.certificate_authorities:
        #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        condition: ${kubernetes.container.name} == 'prometheus-server'
```

## Few UI related comments/confusions related to the prometheus integration:
- in UI `Integrations > Prometheus` the default page will give tutorial for metricbeat and the link to the elastic-agent integration
<img width="1192" alt="Screenshot 2022-06-21 at 11 05 14" src="https://user-images.githubusercontent.com/28299531/174762150-75628fa1-f449-46de-a356-e3ab5c97ceab.png">
