### ISSUE TITLE
[Prometheus Integration] Evaluate metrics extraction from Prometheus server using remote_write option with k8s 

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#3488]
Currently Prometheus Integration is in [0.7.0 Technical Preview ](https://docs.elastic.co/en/integrations/prometheus).

The goal of this issue is to evaluate current situation for the integration and evaluate the metric extraction from a Prometheus server using remote_write option with k8s.
In more details evaluate K8s metrics extraction by using such configuration.

Existing Prometheus Metricbeat Module:
https://www.elastic.co/guide/en/beats/metricbeat/8.2/metricbeat-module-prometheus.html

Evaluate:
- K8s metrics extraction
- OOTB Dashboard validation

Relevant tickets related with this:
a. https://github.com/elastic/integrations/issues/3487
b.https://github.com/elastic/integrations/issues/3489

**Comment by tetianakravchenko** [comment]
How `remote_write` works:
when prometheus.remove_write is enabled - metricbeat/elastic-agent start listening on the defined host:port (default: localhost:9201), Prometheus should use this address as a remote_write URL.

Issue in k8s: It is possible to run prometheus.remote_write in both modes: managed and standalone, the only missing part for both - we do not have a `Service` for elastic-agent to be able to refer it as a remove_write URL (prometheus config). 

## Current situation
We do already have prometheus integration https://github.com/elastic/integrations/tree/main/packages/prometheus, that supports collecting metrics from a Prometheus server using remote_write (`remote_write` data_stream).

### Evaluation points

#### K8s metrics extraction:
How-to run elasti-agent:

##### standalone:
1. Use manifest https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml and add `Service` resource:
```
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-agent-standalone
  namespace: kube-system
  labels:
    app: elastic-agent-standalone
spec:
  ports:
    - port: 9201
      protocol: TCP
      targetPort: 9201
  selector:
    app: elastic-agent-standalone
  sessionAffinity: None
  type: ClusterIP
```
2. Standalone configuration:
```
    inputs:
      - name: prometheus
        type: prometheus/metrics
        use_output: default
        meta:
          package:
            name: prometheus
            version: 0.7.0
        data_stream:
          namespace: default
        streams:
          - data_stream:
              dataset: prometheus.remote_write
              type: metrics
            metricsets:
              - remote_write
            host: '0.0.0.0'
            port: 9201
```
3.  Install prometheus with modified configuration
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm upgrade --install prometheus-server prometheus-community/prometheus -f values.yml

$ cat values.yml
server:
  remoteWrite:
    - url: http://elastic-agent-standalone.kube-system:9201/write
```

##### managed:
1. Use next manifest - https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml and add `Service` resource:
```
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-agent
  namespace: kube-system
  labels:
    app: elastic-agent
spec:
  ports:
    - port: 9201
      protocol: TCP
      targetPort: 9201
  selector:
    app: elastic-agent
  sessionAffinity: None
  type: ClusterIP
```
2. Adjust `FLEET_URL` and `FLEET_ENROLLMENT_TOKEN` and apply manifests.
3.  Install prometheus with modified configuration
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm upgrade --install prometheus-server prometheus-community/prometheus -f values.yml

$ cat values.yml
server:
  remoteWrite:
    - url: http://elastic-agent.kube-system:9201/write
```

#### Dashboard:
We have 1 Overview dashboard - it doesn't work

## Few issue here:
- Documentation is a bit confusing, as here is used `localhost` as an example. Used resources: https://www.elastic.co/guide/en/beats/metricbeat/8.2/metricbeat-metricset-prometheus-remote_write.html, https://www.elastic.co/blog/how-to-implement-prometheus-long-term-storage-using-elasticsearch. Explanation on how it suppose to work would be useful to add
- metrics are added under `prometheus.*` field: 
<img width="2341" alt="Screenshot 2022-06-23 at 15 36 18" src="https://user-images.githubusercontent.com/28299531/175312417-f312b61b-1729-43b0-af23-ce2fd8831274.png">
this contradicts with [doc](https://www.elastic.co/guide/en/beats/metricbeat/8.2/metricbeat-metricset-prometheus-remote_write.html) and do not align with `collector` metricset
- dashboard does not work, I think the point above is the main reason for that:
<img width="2545" alt="Screenshot 2022-06-23 at 15 38 09" src="https://user-images.githubusercontent.com/28299531/175312830-8e575e4e-f42d-46f5-a2fa-1ec1b56c012f.png">
- After adding prometheus integration in UI, installation on K8s is not listed to enroll in Fleet
