### ISSUE TITLE
[network_traffic] Redis fails with `missing required field accessing 'hosts'`

### ISSUE THREAD

**Issue by belimawr** [elastic/integrations#3525]
* Version: 8.2.3
* OS: Win and Mac.

When enabling the "Capture network traffic" Filebeat will fail to start with the error: `Error creating runner from config: missing required field accessing 'hosts'`. See the Elastic-Agent status output.
```
Status: FAILED
Message: (no message)
Applications:
  * osquerybeat        (HEALTHY)
                       Running
  * packetbeat         (HEALTHY)
                       Running
  * endpoint-security  (HEALTHY)
                       Protecting with policy {4e3326b6-237c-4ba7-9f65-b30f646605f3}
  * filebeat           (FAILED)
                       1 error occurred:
                       * 1 error: Error creating runner from config: missing required field accessing 'hosts'


  * filebeat_monitoring    (HEALTHY)
                           Running
  * metricbeat_monitoring  (HEALTHY)
                           Running
  * metricbeat             (HEALTHY)
                           Running
```

This was originally posted on our Discuss, I tested on Windows and can confirm the issue. https://discuss.elastic.co/t/8-2-3-agent-unhealthy-when-network-packet-capture-integration-is-enabled-in-agent-policy/307396

I managed to narrow it down to the Redis input, the `hosts` setting is misting. Here is the configuration for this input generated by the integration:
```yaml
  - id: packet-network_traffic.redis-6d7ac86a-30a8-4766-b14d-9e7e1359a5fe
    index: logs-network_traffic.redis-default
    meta:
      package:
        name: network_traffic
        version: 1.3.0
    name: network_traffic-1
    ports:
    - 6379
    processors:
    - add_fields:
        fields:
          dataset: network_traffic.redis
          namespace: default
          type: logs
        target: data_stream
    - add_fields:
        fields:
          dataset: network_traffic.redis
        target: event
    - add_fields:
        fields:
          id: c959e182-7a24-481c-bd32-0066c57530fd
          snapshot: false
          version: 8.2.3
        target: elastic_agent
    - add_fields:
        fields:
          id: c959e182-7a24-481c-bd32-0066c57530fd
        target: agent
    revision: 1
    type: redis
```
