### ISSUE TITLE
[Enhancements][Synthetics] Ability to Set Observer Metadata

### ISSUE THREAD

**Issue by BenB196** [elastic/integrations#3554]
## Enhancement
Provide the ability to set the observer metadata for the synthetics integration.

Today if you want to use the synthetics integration, it will hard code:

```yaml
processors:
  - add_observer_metadata:
      geo:
        name: Fleet managed
```

This information really provides no use, especially if you want to monitor from multiple locations. Ideally it would be nice to set all values under `add_observer_metadata`, but at a minimum `geo.name` should be configurable.
