### ISSUE TITLE
[AWS] Endpoint config option does not update in agent policy

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#3776]
With changing the endpoint under advanced options when adding AWS integration, the endpoint parameter does not show up in the agent policy:
```
inputs:
  - id: aws/metrics-cloudwatch-dc28e285-6958-41d9-9942-10da809f2cd6
    name: aws-2
    revision: 1
    type: aws/metrics
    use_output: default
    meta:
      package:
        name: aws
        version: 1.18.0
    data_stream:
      namespace: default
    streams:
      - id: >-
          aws/metrics-aws.cloudwatch_metrics-dc28e285-6958-41d9-9942-10da809f2cd6
        data_stream:
          dataset: aws.cloudwatch_metrics
          type: metrics
        metricsets:
          - cloudwatch
        period: 300s
        access_key_id: foo
        secret_access_key: boo
        metrics:
          - name:
              - CPUUtilization
              - DiskWriteOps
            namespace: AWS/EC2
            resource_type: 'ec2:instance'
            statistic:
              - Average
              - Maximum
            tags:
              - key: created-by
                value: foo
```
<img width="457" alt="Screen Shot 2022-07-20 at 1 25 58 PM" src="https://user-images.githubusercontent.com/14081635/180065577-2da594b1-b4d7-4ef1-a517-ab44be6e8d2c.png">
