### ISSUE TITLE
Feature request: Enable dynamically setting key/value pairs on httpjson url.params

### ISSUE THREAD

**Issue by mdavis332** [elastic/integrations#3818]
**Describe the enhancement:**

I've been trying to figure out a way to dynamically set `url.params` keys and their values in the httpjson `url.params` url.Values object.

**Describe a specific use case for the enhancement or feature:**

Specifically for an elastic integration, I'd like a data_stream manifest.yml to have a section sort of like this:
```yaml
- name: filters
  type: yaml
  title: Optional REST API filters
  multi: false
  required: false
  show_user: false
  description: Optional REST API filters
```

On the Fleet integration page during configuration, the UI would then display a large textbox for typing in yaml such as:
```yaml
logRequest: false
tlp: white
```

Then, in the data_stream/\<stream\>/agent/stream/httpjson.yml.hbs file, I'd like to be able to iterate all the k/v's set there and assign them to `url.params`. Something like this I imagine:

```
{{#each filters}}
- set:
  target: url.params.{{@key}}
  value: {{this}}
{{/each}
```

Such that when `url.params` is assembled it has `url.params.logRequest` = `false` and `url.params.tlp` = `white`.

This would allow a user to specify any URL parameters and values without needing the params to be hardcoded into the manifest.yml, allowing for a bit more flexibility. It seems like this isn't supported today as best I can tell (or I just haven't figured out how to make it work).

I opened a similar issue at https://github.com/elastic/beats/issues/32474, but I'm being redirected to file the issue in this repo instead.
