### ISSUE TITLE
[cisco_meraki] ECS 8.4.0 expected values incompatibility for `threat.software.type`

### ISSUE THREAD

**Issue by leehinman** [elastic/integrations#3864]
Switching to ECS 8.4.0 gives this error:

```
one or more errors found in documents stored in logs-cisco_meraki.log-ep data stream: [0] parsing field value failed: field "threat.software.type"'s value "malicious" is not one of the expected values (Malware, Tool) 
```

will need to adjust `security.yml`

```
- rename:
    field: disposition
    target_field: threat.software.type
    if: ctx?.cisco_meraki?.event_subtype == 'security_filtering_file_scanned' || ctx?.cisco_meraki?.event_subtype == 'security_filtering_disposition_change'
```
