### ISSUE TITLE
Fortinet Integration Error

### ISSUE THREAD

**Issue by janniten** [elastic/integrations#3897]
Hi,
I've found errors in the Fortinet integration when ingesting Fortigate logs  of` type: utm` and `subtype: voip`.
The error.message is `field [email.from.address] already exists`
Error is raising in logs-fortinet.firewall-1.7.0-utm pipeline in this processor
```
    {
        "rename": {
          "field": "fortinet.firewall.from",
          "target_field": "email.from.address",
          "ignore_missing": true
        }
      }
```
(In my environment I temporary solved adding `"if": "ctx?.email?.from?.address == null `condition to the processor)

**Comment by efd6** [comment]
It looks like the pipeline is fighting with itself; if `fortinet.firewall.from` is non-null, `email.from.address` is populated with the content of `fortinet.firewall.from` and then unconditionally `fortinet.firewall.from` is attempted to be renamed to that now-constructed field.
```
  - append:
      field: email.from.address
      value: "{{fortinet.firewall.from}}"
      if: "ctx?.fortinet?.firewall?.from != null"
  - rename:
      field: fortinet.firewall.from
      target_field: email.from.address
      ignore_missing: true
```
I suspect that the correct fix is to remove the `rename` processor entirely since `email.from.address` is supposed to be an array and I would guess that the `from` field in the Fortinet log it a single value. It would be helpful if you could provide a redacted log line from your firewall (you should be able to get this from the `event.original` in the failing document.

Also, please note that the Fortinet integration is now deprecated and the fix will be into the Fortinet Fortigate integration. This is a drop-in replacement for the firewall dataset in the Fortinet integration.
