### ISSUE TITLE
Netflow fields validation issue

### ISSUE THREAD

**Issue by mtojek** [elastic/integrations#39]
I've been working on the fields validation in https://github.com/elastic/package-registry/pull/486 and noticed that the `netflow` integration fails the validation due to invalid format.

```yaml
name: netflow
type: group
description: >
  Fields from NetFlow and IPFIX.
fields:
  - name: type
    type: keyword
    description: >
      The type of NetFlow record described by this event.
```
^ this should be an array like this one:

```
- name: cisco
  type: group
```
