### ISSUE TITLE
[Synthetics] Add `observer.name` mapped to location id to observer processor

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/integrations#3927]
Add field `observer.name` to observer processor. This field should store the location id, rather than the location name, for private location monitors.

**Comment by andrewvc** [comment]
As a heads-up https://github.com/elastic/beats/pull/30632 adds this functionality to heartbeat. I think we still need this issue to track the integration changes however.

You can now add the following to monitors:

```yaml
- type: http
  id: my-monitor
  schedule: "@every 10s"
  location:
    id: "us-east-1a"
    geo:
      name: "US-East Coast"
      location: "44.123, 45.12345"
```
