### ISSUE TITLE
[Windows] Windows integration sysmon operational template is invalid

### ISSUE THREAD

**Issue by nchaulet** [elastic/integrations#4170]
## Description 

The sysmon operational handlebar template is invalid, if a user try to add a processors he get the following error:

<img width="921" alt="Screen Shot 2022-09-08 at 9 37 30 AM" src="https://user-images.githubusercontent.com/1336873/189138033-12fb3aca-c9af-4a34-a63e-6f72d1c2b9ec.png">

This seems to happens since `translate_sid` has been added to the template
```
processors:
  - translate_sid:
      field: winlog.event_data.MemberSid
      account_name_target: winlog.event_data._MemberUserName
      domain_target: winlog.event_data._MemberDomain
      account_type_target: winlog.event_data._MemberAccountType
      ignore_missing: true
      ignore_failure: true
```

The issues seems to happen for the `windows.powershell_operational` too.
