### ISSUE TITLE
Microsoft SQL Server integration : cannot connect to MSSQL server to retrieve performances & other metrics

### ISSUE THREAD

**Issue by Danouchka** [elastic/integrations#4198]
Hi 

Using Elastic-Agent (v 8.4.1-1), **Microsoft SQL Server** integration (v 1.4.0), I cannot connect to MSSQL server to retrieve performance and transaction logs metrics. 

Error raised
`[elastic_agent.metricbeat][error] Error fetching data for metricset sql.query: could not open connection: testing connection: parse "sqlserver://SA:sqlMS200675": invalid port ":sqlMS200675" after host`

Configuration used 
<img width="882" alt="Capture d’écran 2022-09-12 à 18 58 16" src="https://user-images.githubusercontent.com/48563314/189713906-6e847088-5ce9-4a54-af92-dbf16c588f06.png">

With metricbeat standalone , using mssql module, it works. And yet configuration of mssql parameters is the same: 

```
-module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["localhost"]
  username: SA
  password: sqlMS200675#
  period: 10s
```
