### ISSUE TITLE
[Question] System/Pipeline tests validation issues

### ISSUE THREAD

**Issue by ChrsMark** [elastic/integrations#422]
Hi!

While [developing NATS package](https://github.com/elastic/integrations/pull/413) I face a couple of issues that might be of interest for us. Filing this issue to keep track of them:

1. system tests have been failing with errors like:
```
[0] parsing field value failed: field "client.port"''s Go type, string, does not match the expected field type: long
[1] parsing field value failed: field "nats.log.msg.bytes"''s Go type, string, does not match the expected field type: long
[2] parsing field value failed: field "process.pid"''s Go type, string, does not match the expected field type: long
```
and I had to add conversions about them in the pipeline:
```
- convert:
    ignore_missing: true
    field: process.pid
    type: long
- convert:
    ignore_missing: true
    field: client.port
    type: long
- convert:
    ignore_missing: true
    field: nats.log.msg.bytes
    type: long
```
Is this normal? Why need this explicit conversion, shouldn't the mapping handle it properly like what happens with Filebeat?

2. Something similar is hit with pipeline tests:

```
nats/log test-log-sample.log:
[0] field "nats.log.timestamp" is undefined
[1] parsing field value failed: field "client.port"''s Go type, string, does not match the expected field type: long
[2] parsing field value failed: field "nats.log.msg.bytes"''s Go type, string, does not match the expected field type: long
[3] parsing field value failed: field "process.pid"''s Go type, string, does not match the expected field type: long
--- Test results for package: nats - END   ---
```

while in the same time system test works. Also notice that `nats.log.timestamp` should be removed by the pipeline https://github.com/elastic/integrations/pull/413/files#diff-6aa6fcf767f50c8a2625656e8b9f720003164e336a0cb72feeb5858653ee3599R167. 
Why all these things happen and why there weren't an issue back in Filebeat?

cc: @ycombinator @mtojek
