### ISSUE TITLE
Kubernetes integration v1.27.0 does not apply conditions

### ISSUE THREAD

**Issue by renzedj** [elastic/integrations#4598]
Kubernetes integration v1.27.0 gives the option to create a condition for monitoring container logs (see image below). However, it does not appear apply the condition as part of the policy (see YAML). As a result, the integration captures all logs for all containers.

![Screen Shot 2022-11-08 at 4 14 32 PM](https://user-images.githubusercontent.com/81439124/200688602-043a5b73-5251-44e2-b13d-d22c2d9c6df9.png)

YAML generated from the policy including the above is:

```yaml
- id: filestream-container-logs-d55d0708-fd8c-4d36-bc7f-aa46f9c67f69
  name: Kubernetes - myapp.log
  revision: 25
  type: filestream
  use_output: default
  meta:
    package:
      name: kubernetes
      version: 1.27.0
  data_stream:
    namespace: default
  package_policy_id: d55d0708-fd8c-4d36-bc7f-aa46f9c67f69
  streams:
    - id: >-
        kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
      data_stream:
        dataset: kubernetes.container_logs
        type: logs
      prospector.scanner.symlinks: true
      paths:
        - '/var/log/containers/*${kubernetes.container.id}.log'
      parsers:
        - container:
            stream: all
            format: auto
      processors:
        - add_tags:
            target: tags
            tags:
              - myapp
```
