### ISSUE TITLE
System integration for winlog condition broken

### ISSUE THREAD

**Issue by blakerouse** [elastic/integrations#4725]
Currently the condition for the winlog input defined in the system integration is incorrect. The condition is placed on each stream, which means that on a non-windows host all streams will be removed but the input will remain. The condition should be moved to the input itself and removed from each stream.

Currently:

```
  - id: winlog-system-4e851f19-cee3-42fc-8799-9cce99aad6b1
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.20.4
    data_stream:
      namespace: default
    package_policy_id: 4e851f19-cee3-42fc-8799-9cce99aad6b1
    streams:
      - id: winlog-system.application-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.security-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
      - id: winlog-system.system-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: System
        data_stream:
          dataset: system.system
          type: logs
        condition: '${host.platform} == ''windows'''
        ignore_older: 72h
```

It needs to be:

```
  - id: winlog-system-4e851f19-cee3-42fc-8799-9cce99aad6b1
    name: system-1
    revision: 1
    type: winlog
    use_output: default
    meta:
      package:
        name: system
        version: 1.20.4
    data_stream:
      namespace: default
    package_policy_id: 4e851f19-cee3-42fc-8799-9cce99aad6b1
    condition: '${host.platform} == ''windows'''
    streams:
      - id: winlog-system.application-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: Application
        data_stream:
          dataset: system.application
          type: logs
        ignore_older: 72h
      - id: winlog-system.security-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: Security
        data_stream:
          dataset: system.security
          type: logs
        ignore_older: 72h
      - id: winlog-system.system-4e851f19-cee3-42fc-8799-9cce99aad6b1
        name: System
        data_stream:
          dataset: system.system
          type: logs
        ignore_older: 72h
```

Without this Elastic Agent will try to start the winlog input on non-Windows hosts when it should not even try to start it. Elastic Agent could say with no streams that it should just not start the input, but the problem is there are many inputs that don't define streams. So it cannot just do that.
