### ISSUE TITLE
New integrations

### ISSUE THREAD

**Issue by dicolanl** [elastic/integrations#4730]
I am working on creating a new integration that is pulling JSON logs form a rest api.  I looked at several other pagackages but after deploying the package to the stack in containers i am seeing the following error

```
2022-11-29 08:43:37 {"log.level":"error","@timestamp":"2022-11-29T13:43:37.046Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-11-29T13:43:37Z - message: Application: filebeat--8.4.1[eb7ef569-9a80-42f9-883d-22ae4d33c91b]: State changed to FAILED: 1 error occurred:\n\t* 1 error: Error creating runner from config: each transform must have exactly one action, but found 4 actions accessing 'response'\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
```

Here is the httpjson.yml.hbs which i dont see multiple transforms on response?
```yaml
config_version: "2"
interval: {{interval}}
request.method: "GET"
request.url: {{api_url}}/api/v1/audit
{{#if ssl}}
request.ssl: {{ssl}} 
{{/if}}
{{#if http_client_timeout}} 
request.timeout: {{http_client_timeout}}
{{/if}}
{{#if proxy_url }}
request.proxy_url: {{proxy_url}}
{{/if}}

request.transforms:
  - set:
      target: header.Authorization
      value: "{{api_token}}"
  - set:
      target: url.params.from
      value: "[[.cursor.last_timestamp]]"
      default: '[[(now (parseDuration "-{{initial_interval}}")).UnixMilli]]'
  - set:
      target: url.params.to
      value: '[[(now).UnixMilli]]'
  - set:
      target: url.params._limit
      value: '[[{{limit}}]]'
  - set:
      target: url.params.order
      value: "asc"

response.split:
  target: body.items

response.pagination:
  - set:
    target: url.params.cursor
    value: '[[.last_response.body.scrollCursor]]'
    fail_on_template_error: true

cursor:
  last_timestamp:
    value: "[[.last_event.timestamp]]"
    fail_on_template_error: true

{{#if tags.length}}
tags:
{{else if preserve_original_event}}
tags:
{{/if}}
{{#each tags as |tag i|}}
  - {{tag}}
{{/each}}
{{#if preserve_original_event}}
  - preserve_original_event
{{/if}}
{{#contains "forwarded" tags}}
publisher_pipeline.disable_host: true
{{/contains}}
{{#if processors}}
processors:
{{processors}}
{{/if}}
```

Any help is greatly appreciated.
