### ISSUE TITLE
Azure Logs integration stops collecting logs after a configuration change

### ISSUE THREAD

**Issue by zmoog** [elastic/integrations#4743]
- Version: >= 8.3.3
- Operating System: any

### Steps

1. Visit **Integrations -> Installed integrations -> Azure Logs**.
2. Select **Integration Policies** tab.
3. Click on an integration policy.
4. In **Collect event from Event Hub**, expand **Change defaults**.
5. Change one configuration option (for example, toggle **Preserve original event**).
6. Click on **Save integration** button.
7. Click on **Save and deploy changes**.

Fleet will then update the Agent running the policy.

### Expected Result

After Fleet has applied this configuration change, Filebeats resumes processing logs with the new configuration.

### Actual Result

After Fleet has applied this configuration change, Filebeats stops sending data.

### 1 - Restart the Agent

By restarting the Agent, data collection resumes with the new configuration.

### 2 - Disable and re-enable the integration

Instead of manually restarting the Elastic Agent, you can do the following operations:

1. Disable the sign-in logs integration
2. Wait for the Agent to get the update (visible in the Agent list in Fleet)
3. Make the configuration change
4. Enable back the sign-in logs integration

This should have the same effect as a manual restart of the Elastic Agent on the host. Still not great, but it should avoid manually restarting the Agent on the host.

**Comment by zmoog** [comment]
I can reproduce the issue by running one integration from Azure Logs in my local stack:

```shell
elastic-package stack up -v -d --version 8.5.0
```

The `azureeventhub` input stopped working every time I made a configuration change.

The workarounds described above can restore functionality.

**Comment by zmoog** [comment]
During the stopping phase, Filebeats reports an error:

```json
{
  "log.level": "error",
  "@timestamp": "2022-11-29T20:23:21.438Z",
  "log.origin": {
    "file.name": "status/reporter.go",
    "file.line": 326
  },
  "message": "Elastic Agent status changed to \"error\": \"app filebeat--8.5.0-b09e90e3: failed to stop after 30s: application stopping timed out\"",
  "ecs.version": "1.6.0"
}


{
  "log.level": "error",
  "@timestamp": "2022-11-29T20:23:21.438Z",
  "log.origin": {
    "file.name": "process/app.go",
    "file.line": 156
  },
  "message": "failed to stop after 30s: application stopping timed out",
  "ecs.version": "1.6.0"
}

{
  "log.level": "error",
  "@timestamp": "2022-11-29T20:23:21.438Z",
  "log.origin": {
    "file.name": "log/reporter.go",
    "file.line": 36
  },
  "message": "2022-11-29T20:23:21Z - message: Application: filebeat--8.5.0[c79c7145-1ce5-47fa-b4f8-72e67e70e87f]: State changed to FAILED: failed to stop after 30s: application stopping timed out - type: 'ERROR' - sub_type: 'FAILED'",
  "ecs.version": "1.6.0"
}
```

**Comment by zmoog** [comment]
This issue happens on stack 8.4.0+, and earlier versions are not affected.

**Comment by zmoog** [comment]
Since 8.3.3, the input Runner changed its behavior during the [live reload](https://github.com/elastic/beats/blob/5fd004137864d356ef5ad33d0e8687e5192e651a/libbeat/cfgfile/list.go#L55):

- `< 8.3.3`: the input Runner stops the old input and starts a new input [without waiting](https://github.com/elastic/beats/blob/v8.3.2/libbeat/cfgfile/list.go#L84-L90) for the stop to complete.
- `>= 8.3.3`: the input Runner stops the old input and [waits for](https://github.com/elastic/beats/blob/5fd004137864d356ef5ad33d0e8687e5192e651a/libbeat/cfgfile/list.go#L84-L96) the `Stop()` method to complete before starting a new one.

Unfortunately, if we run [Start()](https://github.com/Azure/azure-event-hubs-go/blob/0e9e4ef2a1d1218a0eafa928345758ce3d274611/eph/eph.go#L302) with EPH in a blocking mode, the method will not return because it will [continue waiting](https://github.com/Azure/azure-event-hubs-go/blob/0e9e4ef2a1d1218a0eafa928345758ce3d274611/eph/eph.go#L325-L329) for an `os.Signal` that will never come.

If the EPH's `Start()` method does not end, the EPH `sync.WaitGroup` will [continue waiting forever](https://github.com/elastic/beats/blob/5fd004137864d356ef5ad33d0e8687e5192e651a/x-pack/filebeat/input/azureeventhub/input.go#L168).

**Comment by zmoog** [comment]
Tested successfully on [8.6 BC9](https://staging.elastic.co/8.6.0-43d88470/summary-8.6.0.html).

**Comment by zmoog** [comment]
Here's how I tested Filebeat 8.6 BC9.

## Get Filebeat 8.6 BC9

Download the tarball for your OS and architecture:

```shell
$ wget https://staging.elastic.co/8.6.0-43d88470/downloads/beats/filebeat/filebeat-8.6.0-darwin-aarch64.tar.gz
--2022-12-30 12:18:14--  https://staging.elastic.co/8.6.0-43d88470/downloads/beats/filebeat/filebeat-8.6.0-darwin-aarch64.tar.gz
Resolving staging.elastic.co (staging.elastic.co)... 34.120.127.130
Connecting to staging.elastic.co (staging.elastic.co)|34.120.127.130|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 34403318 (33M) [application/x-gzip]
Saving to: ‘filebeat-8.6.0-darwin-aarch64.tar.gz’

filebeat-8.6.0-darwin-aarch64.tar.gz

2022-12-30 12:18:20 (6,95 MB/s) - ‘filebeat-8.6.0-darwin-aarch64.tar.gz’ saved [34403318/34403318]
```

Decompress the archive:

```shell
$ tar zxvf ../filebeat-8.6.0-darwin-aarch64.tar.gz
x filebeat-8.6.0-darwin-aarch64/
x filebeat-8.6.0-darwin-aarch64/modules.d/
x filebeat-8.6.0-darwin-aarch64/kibana/
x filebeat-8.6.0-darwin-aarch64/filebeat
x filebeat-8.6.0-darwin-aarch64/filebeat.reference.yml
....
```

And finally move into it:

```shell
cd filebeat-8.6.0-darwin-aarch64
```

## Configure Filebeat

### Azure module

Enable the Azure module in Filebeat:

```shell
cp modules.d/azure.yml.disabled modules.d/azure.yml
```

Edit the Azure module to enable the platform logs, for example:

```yaml
  platformlogs:
    enabled: true
    var:
      # adding a new line
      eventhub: "platformlogs"
      consumer_group: "$Default"
      connection_string: "Endpoint=sb://....="
      storage_account: ""
      storage_account_key: ""
      tags:
        - "azure"
        - "whatever4"
```

### Live reload

Edit the `filebeat.yml` file and update the "Filebeat modules" section like this one:

```yaml
# ============================== Filebeat modules ==============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  # reload.enabled: false
  reload.enabled: true

  # Period on which files under path should be checked for changes
  #reload.period: 10s
  reload.period: 10s

# ======================= Elasticsearch template setting =======================
```

## Run Filebeat

```shell
export CLOUD_ID=""
export CLOUD_AUTH=""

$ ./filebeat -e \
  -E cloud.auth=${CLOUD_AUTH} \
  -E cloud.id=${CLOUD_ID} \
  -E output.elasticsearch.allow_older_versions=true
```

## Test if live reload works 

When Filebeat starts with the platform logs enabled, you should see log messages like this one:

```json
{"log.level":"info","@timestamp":"2022-12-30T12:34:08.591+0100","log.logger":"azure-eventhub input","log.origin":{"file.name":"azureeventhub/input.go","file.line":109},"message":"azure-eventhub input worker is starting.","service.name":"filebeat","connection string":"Endpoint=sb://zmoogazurelogs.servicebus.windows.net/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-30T12:34:09.868+0100","log.logger":"azure-eventhub input","log.origin":{"file.name":"azureeventhub/eph.go","file.line":92},"message":"handler id: \"48c45ee8-fe70-4279-b282-ab9f02a4e766\" is registered\n","service.name":"filebeat","connection string":"Endpoint=sb://zmoogazurelogs.servicebus.windows.net/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-30T12:34:10.766+0100","log.logger":"azure-eventhub input","log.origin":{"file.name":"azureeventhub/input.go","file.line":115},"message":"azure-eventhub input worker has started.","service.name":"filebeat","connection string":"Endpoint=sb://zmoogazurelogs.servicebus.windows.net/","ecs.version":"1.6.0"}
```

The next step is to change the `modules.d/azure.yml` file; for example, add or remove a tag in the platform logs configuration:

```yaml
  platformlogs:
    enabled: true
    var:
      # adding a new line
      eventhub: "platformlogs"
      consumer_group: "$Default"
      connection_string: "Endpoint=sb://....="
      storage_account: ""
      storage_account_key: ""
      tags:
        - "azure"
        - "whatever4"
        - "yet-another-tag"
```

Save the file, and within a few seconds Filebeat should stop and restart the `azure-eventhub` input, showing again the same messages, like "azure-eventhub input worker has started.":

```json
{"log.level":"info","@timestamp":"2022-12-30T12:40:43.124+0100","log.logger":"azure-eventhub input","log.origin":{"file.name":"azureeventhub/input.go","file.line":115},"message":"azure-eventhub input worker has started.","service.name":"filebeat","connection string":"Endpoint=sb://zmoogazurelogs.servicebus.windows.net/","ecs.version":"1.6.0"}
```
