### ISSUE TITLE
[MongoDB] integration pipeline doesnt remove original event when preserve_original_event is not set

### ISSUE THREAD

**Issue by ManojS-shetty** [elastic/integrations#4836]
Customer noticed that the MongoDB integration pipeline `logs-mongodb.log-1.5.0-pipeline-json` always saves the original event, even if `preserve_original_event` isn't set. Looking at the other pipelines there may need to be a `remove` action added to the pipeline.

**Comment by ManojS-shetty** [comment]
Solution:

Add the remove processor in ingest pipeline:

```
  - remove:
      field: event.original
      if: "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))"
      ignore_failure: true
      ignore_missing: true
```
