### ISSUE TITLE
[Prototype] TSDB For Oracle Integration

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#4848]
- [ ]  #4848

- TSDB settings are enabled for Oracle integration in Kibana for Enabling and disabling. 
- Validate that if TSDB is already enabled, switch back to standard index type is disabled. 
- Enable Timeseries settings in manifest.yml for performance datastream
```
elasticsearch:
  index_mode: "time_series"
  index_template:
    settings:
      # Defaults to 16
      index.mapping.dimension_fields.limit: 32
```
- Define the dimensions for the performance datastream
- Verify the data ingestion and data querying (exploration) for performance datastream

PR Details : https://github.com/elastic/integrations/pull/4966

**Comment by agithomas** [comment]
**metrics-oracle.performance@package**

{
  "index": {
    "lifecycle": {
      "name": "metrics"
    },
    "codec": "best_compression",
    "default_pipeline": "metrics-oracle.performance-1.9.4",
    "mapping": {
      "total_fields": {
        "limit": "10000"
      },
      "dimension_fields": {
        "limit": "16"
      }
    },
    "query": {
      "default_field": [
        "ecs.version",
        "service.address",
        "service.type",
        "oracle.performance.machine",
        "oracle.performance.buffer_pool",
        "oracle.performance.username",
        "oracle.performance.wait.wait_class"
      ]
    }
  }
}

**Comment by agithomas** [comment]
![Image](https://user-images.githubusercontent.com/101976829/211597370-81f7fa71-01b7-4159-b36e-f5eaf5bca113.png)

**Comment by agithomas** [comment]
```
elasticsearch:
  source_mode: "synthetic"
  index_mode: "time_series"
  index_template:
    settings:
      # Defaults to 16
      index.mapping.dimension_fields.limit: 16
```
