### ISSUE TITLE
[O365] Add fingerprint processor to prevent duplicate events being ingested

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#5046]
There appears to be a bug in the [O365 Management API input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-o365audit.html) where duplicate events are sent when the last event of the previous response is included in the current response. Since the `_id` field doesn't appear to be set on documents, if a duplicate event is processed, it is also ingested as well.

A [fingerprint](https://www.elastic.co/guide/en/elasticsearch/reference/current/fingerprint-processor.html) processor should be added to the pipeline so the `_id` field is set properly.

Something like this should suffice:

```yaml
- fingerprint:
    fields:
      - o365audit
    target_field: "_id"
    ignore_missing: true
```
