### ISSUE TITLE
[Cisco Meraki] Flow pipeline is removing data

### ISSUE THREAD

**Issue by richardleeps** [elastic/integrations#5086]
The ingest pipeline "logs-cisco_meraki.log-1.5.0-flows" of the Cisco Meraki Integration is not parsing the data that correctly for the following logs lines 

flows.src=10.10.10.11.dst=145.343.192.205.mac=9C:7B:EF:A9:6C:D8.protocol=udp.sport=64138.dport=3289.pattern:.deny.(src.10.10.0.0/16)
flows.src=10.10.10.12.dst=10.8.6.10.mac=9C:7B:EF:A9:6C:D8.protocol=tcp.sport=12324.dport=443.pattern:.deny.all

All information that after "dport=%{NONNEGINT:destination.port:long}?" is removed.

**Comment by efd6** [comment]
@richardleeps Are you able to provide events with `event.original` present so that we can see what we should be expecting. There is [this](https://www.ibm.com/docs/en/dsm?topic=meraki-cisco-sample-event-messages) which shows 
```
<134>1 1515988859.626061236 appliance flows src=172.21.84.107 dst=10.52.193.137 mac=5C:E0:C5:22:85:E4 protocol=tcp sport=50395 dport=443 pattern: allow all
```
and [this](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples)
```
1374543986.038687615 MX84 flows src=192.168.1.186 dst=8.8.8.8 mac=58:1F:AA:CE:61:F2 protocol=udp sport=55719 dport=53 pattern: allow all
```
So it would be helpful to know what we will see. I am expecting something like 
```
- grok:
    field: event.original
    patterns:
      - "flows( %{NOTSPACE:cisco_meraki.flows.op})? src=%{IP:source.ip:ip} dst=%{IP:destination.ip:ip}( mac=%{MAC:source.mac})? protocol=%{NOTSPACE:network.protocol}( sport=%{NONNEGINT:source.port:long})?( dport=%{NONNEGINT:destination.port:long})?( pattern: %{GREEDYDATA:cisco_meraki.pattern})?"
```
Potentially with some work to structure `cisco_meraki.pattern` into something more meaningful than raw text.
