### ISSUE TITLE
[Check Point] GROK Filters add tag_on_failure

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#5108]
Check Point integration is not leveraging `tag_on_failure` for the GROK filters. If there is a tag_on_failure for the GROK filters, then it could be used with a custom pipeline added to the integration configuration via processor on settings. Then could be used as a handle to reprocess source with custom GROK pattern(s).

Right now you need to modify or add to the existing GROK patterns in the pipeline asset of the integration. This will be overridden and lost with upgrade/reinstall of that integration. Whereas the custom pipeline would not.

There is a on_failure end filter in pipeline, but that is long text line and you would need to parse or do a logic like 'starts with xyz' .

**Acceptance Criteria**
Add tag_on_failure on GROK filters in integration pipelines to use in logic of custom pipeline
Or add manner to retain additional GROK pattern modification/adds to integration existing GROK filters without loss on update/reinstall of integration.

**Comment by efd6** [comment]
The [ES grok processor does not have](https://www.elastic.co/guide/en/elasticsearch/reference/master/grok-processor.html) a `tag_on_failure` option. This *does* exist for the [logstash grok filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-tag_on_failure). However, we can use the `on_failure` option to append either to `tags` or `error.message`. Given that the failure would be a failure, the latter seems like a more appropriate approach.

Adding a failure error would have two uses, one is to provide a human-oriented message while the second would address the request above to be able to efficiently enable programmatic error recovery. Unfortunately these two uses are at odds (the former use would require that the user recover with approaches like the logic described above). An alternative would be to cover both approaches by appending both the human-directed message and a processor/failure-mode specific tag that would allow programmatic recovery. Another proposal that discusses this has been made [here](https://github.com/elastic/integrations/issues/5214).

Taking the CheckPoint grok processor as an example I propose something like (original [here](https://github.com/elastic/integrations/blob/437d57ef5d31e7b5638acd7b63f02ebc2ea2b267/packages/checkpoint/data_stream/firewall/elasticsearch/ingest_pipeline/default.yml#L11-L20))

```
  - grok:
      field: event.original
      tag: "grok_syslog_line"
      patterns:
        - '%{SYSLOG5424PRI}%{NONNEGINT:syslog5424_ver} +(?:%{TIMESTAMP}|-)
          +(?:%{IPORHOST:syslog5424_host}|-) +(-|%{SYSLOG5424PRINTASCII:syslog5424_app})
          +(-|%{SYSLOG5424PRINTASCII:syslog5424_proc}) +(?::-|%{SYSLOG5424PRINTASCII:syslog5424_msgid})
          +\[%{GREEDYDATA:syslog5424_sd}\]'
      pattern_definitions:
        TIMESTAMP: "%{TIMESTAMP_ISO8601:syslog5424_ts}(?:-?%{ISO8601_TIMEZONE:_temp_.tz})?"
        TIMESTAMP_ISO8601: "%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?"
      on_failure:
        - append:
            field: error.message
            value: "fail-{{{ _ingest.on_failure_processor_tag }}}"
        - fail:
            message: "Processor {{ _ingest.on_failure_processor_type }} with tag {{ _ingest.on_failure_processor_tag }} in pipeline {{ _ingest.on_failure_pipeline }} failed with message: {{ _ingest.on_failure_message }}"
```

With this addition, on attempting to ingest an invalid input like
```
<134>1 this_is_not_a_valid_year-03-30T07:20:35Z gw-da58d3 CheckPoint 7776 - [action:"Accept"; flags:"444676"; ifdir:"outbound"; ifname:"eth0"; logid:"0"; loguid:"{0x5e819dc3,0x0,0x353707c7,0xee78a1dc}"; origin:"192.168.1.100"; originsicname:"cn=cp_mgmt,o=gw-da58d3..tmn8s8"; sequencenum:"1"; time:"1594646954"; version:"5"; __policy_id_tag:"product=VPN-1 & FireWall-1[db_tag={880771B0-FD92-2C4F-82FC-B96FC3DE5A07};mgmt=gw-da58d3;date=1585502566;policy_name=Standard\]"; dst:"192.168.1.153"; inzone:"Local"; layer_name:"Network"; layer_uuid:"63b7fe60-76d2-4287-bca5-21af87337b0a"; match_id:"1"; parent_rule:"0"; rule_action:"Accept"; rule_uid:"1fde807b-6300-4b1a-914f-f1c1f3e2e7d2"; outzone:"External"; product:"VPN-1 & FireWall-1"; proto:"17"; s_port:"43103"; service:"514"; service_id:"syslog"; src:"192.168.1.100"]
```
we get an event like
```
{
    "_conf": {
        "tz_offset": "+0500"
    },
    "ecs": {
        "version": "8.6.0"
    },
    "error": {
        "message": [
            "fail-grok_syslog_line",
            "Processor grok with tag grok_syslog_line in pipeline default-1675904098718607000 failed with message: Provided Grok expressions do not match field value: [\u003c134\u003e1 this_is_not_a_valid_year-03-30T07:20:35Z gw-da58d3 CheckPoint 7776 - [action:\\\\\\\"Accept\\\\\\\"; flags:\\\\\\\"444676\\\\\\\"; ifdir:\\\\\\\"outbound\\\\\\\"; ifname:\\\\\\\"eth0\\\\\\\"; logid:\\\\\\\"0\\\\\\\"; loguid:\\\\\\\"{0x5e819dc3,0x0,0x353707c7,0xee78a1dc}\\\\\\\"; origin:\\\\\\\"192.168.1.100\\\\\\\"; originsicname:\\\\\\\"cn=cp_mgmt,o=gw-da58d3..tmn8s8\\\\\\\"; sequencenum:\\\\\\\"1\\\\\\\"; time:\\\\\\\"1594646954\\\\\\\"; version:\\\\\\\"5\\\\\\\"; __policy_id_tag:\\\\\\\"product=VPN-1 \u0026 FireWall-1[db_tag={880771B0-FD92-2C4F-82FC-B96FC3DE5A07};mgmt=gw-da58d3;date=1585502566;policy_name=Standard\\\\\\\\]\\\\\\\"; dst:\\\\\\\"192.168.1.153\\\\\\\"; inzone:\\\\\\\"Local\\\\\\\"; layer_name:\\\\\\\"Network\\\\\\\"; layer_uuid:\\\\\\\"63b7fe60-76d2-4287-bca5-21af87337b0a\\\\\\\"; match_id:\\\\\\\"1\\\\\\\"; parent_rule:\\\\\\\"0\\\\\\\"; rule_action:\\\\\\\"Accept\\\\\\\"; rule_uid:\\\\\\\"1fde807b-6300-4b1a-914f-f1c1f3e2e7d2\\\\\\\"; outzone:\\\\\\\"External\\\\\\\"; product:\\\\\\\"VPN-1 \u0026 FireWall-1\\\\\\\"; proto:\\\\\\\"17\\\\\\\"; s_port:\\\\\\\"43103\\\\\\\"; service:\\\\\\\"514\\\\\\\"; service_id:\\\\\\\"syslog\\\\\\\"; src:\\\\\\\"192.168.1.100\\\\\\\"]]"
        ]
    },
    "event": {
        "original": "\u003c134\u003e1 this_is_not_a_valid_year-03-30T07:20:35Z gw-da58d3 CheckPoint 7776 - [action:\"Accept\"; flags:\"444676\"; ifdir:\"outbound\"; ifname:\"eth0\"; logid:\"0\"; loguid:\"{0x5e819dc3,0x0,0x353707c7,0xee78a1dc}\"; origin:\"192.168.1.100\"; originsicname:\"cn=cp_mgmt,o=gw-da58d3..tmn8s8\"; sequencenum:\"1\"; time:\"1594646954\"; version:\"5\"; __policy_id_tag:\"product=VPN-1 \u0026 FireWall-1[db_tag={880771B0-FD92-2C4F-82FC-B96FC3DE5A07};mgmt=gw-da58d3;date=1585502566;policy_name=Standard\\]\"; dst:\"192.168.1.153\"; inzone:\"Local\"; layer_name:\"Network\"; layer_uuid:\"63b7fe60-76d2-4287-bca5-21af87337b0a\"; match_id:\"1\"; parent_rule:\"0\"; rule_action:\"Accept\"; rule_uid:\"1fde807b-6300-4b1a-914f-f1c1f3e2e7d2\"; outzone:\"External\"; product:\"VPN-1 \u0026 FireWall-1\"; proto:\"17\"; s_port:\"43103\"; service:\"514\"; service_id:\"syslog\"; src:\"192.168.1.100\"]"
    }
}
```

This would allow the user conditionally parse the `event.original` if `(ctx.error?.message instance of List) && ctx.error.message.contains('fail-grok_syslog_line')`.

The checkpoint package has only a single grok processor, but in more complex pipelines, processors would be differentiated by their tag.

Note that the change proposed does a `fail` since there is no way to recover operation of the pipeline after the initial grok failure. There is also no way to make use of the subsequent processors and the user's custom processor pipeline would have to do all the necessary operations to construct an appropriately formatted document.
