### ISSUE TITLE
K8s Integration does not report correct container.id when container restarts

### ISSUE THREAD

**Issue by gizas** [elastic/integrations#5348]
**Issue**

Customer deploys pod with several containers. Elastic Agent with Kubernetes Integration installed is used to monitor the **logs** of given pod's containers. Customer reported  that `container.id`  in Elasticsearch matches the actual container id as reported by kubectl.

Container is being restarted. After restart, the container ids dont match the new assigned container ids. 

**Relevant Screenshot**

![pod-id-constant-something-wrong](https://user-images.githubusercontent.com/1685415/220380797-c74ea2ac-5e5e-4e6b-9ed5-1a8029de7aaa.PNG)

**Comment by sunileman** [comment]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/12245219/220522233-143a59ab-5cce-4be6-a702-4c6bbdaca4f6.png">

K8s container logs are by default fetched using 
`/var/log/containers/*${kubernetes.container.id}.log`

During our debug session, we found container id did not match the container id found in the log file path.  

Where and how is `kubernetes.container.id` set?  In the context of K8s, I understand where `kubernetes.container.id` comes from.  I don't understand how our integration uses it.  The mismatch combo of `container.id`, logfile container id, and `kubernetes.container.id` is puzzling.

**Comment by gizas** [comment]
I have managed to replicate the scenario of the user where the containers restart with updated manifest of https://github.com/elastic/integrations/issues/5348#issuecomment-1438661858, but everything seems to work!

Long story short the container.id is recognised correctly for restarted container.
This is the busybox that restarts every 60 sec
![Screenshot 2023-02-22 at 5 02 11 PM](https://user-images.githubusercontent.com/1685415/220664369-ccc69082-8225-4e96-86ce-00da70d1ebbe.png)

Those are the 
![Screenshot 2023-02-22 at 5 01 44 PM](https://user-images.githubusercontent.com/1685415/220664389-01752665-c962-4e5d-ad3e-3674b4df5a0b.png)

The relevant kubectl output:
```yaml
 kubectl describe pod -n development multi-container-pod
Name:             multi-container-pod
Namespace:        development
Priority:         0
Service Account:  default
Node:             pas-control-plane/172.20.0.2
Start Time:       Wed, 22 Feb 2023 16:46:13 +0200
Labels:           <none>
Annotations:      <none>
Status:           Running
IP:               10.244.0.20
IPs:
  IP:  10.244.0.20
Containers:
  container-1:
    Container ID:   containerd://80ece243fc07e9c6373b9eee8f856e5dfc21c9a0546a7f248c9b6e68b49e43e6
    Image:          nginx
      container-2:
    Container ID:  containerd://1b8800bb3c7eb1020d4c57fc79e07888da72c970789787e5c56d5161259b4d0e
   Image: alpine
      hello:
    Container ID:  containerd://b23931a68125a444ef97509fc190f86dfd3d747c4f8d5f5e2bf0ba3b6bfeedbf
    Image:         busybox:1.28
  [output was truncated]
```

Some remarks for all the comments made above:
1. This is the policy I used in my tests. Only logs are enabled. Just to ensure that no other datastream can ingest container.id
![Screenshot 2023-02-22 at 12 07 29 PM](https://user-images.githubusercontent.com/1685415/220665573-7f64ae77-7d7c-4a96-ba1e-024570e4d212.png)

2. Kubernetes.pod.uid not to be mixed with container.id field. (UId is unique per [pod](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids))
```yaml
kgp -n development multi-container-pod -o jsonpath='{.metadata.uid}'
2ef5500e-4f3c-4326-825c-cf2ca220baa
```

3. Indeed K8s container logs are by default fetched using
/var/log/containers/*${kubernetes.container.id}.log

This refers to https://www.elastic.co/guide/en/fleet/master/kubernetes-provider.html field and should be the same with the container.id you see ingested in Kibana Discovery
 
4. In order to see kibana entry for the restarted container you will need a successful log entry in to be created inside /var/log/ folder. So it might take sometime until next restart of container to see the entry.

Can we please verify with customer the id mismatch again (not to compare with uid)? Do the restart containers produce log entries in respected files? Is our policy correct and user cares only for logs ?
