### ISSUE TITLE
AWS Cloudwatch is indexing data in the wrong data stream

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/integrations#5467]
This issue concerns https://docs.elastic.co/integrations/aws/cloudwatch

In particular, the `cloudwatch_logs`.

The problem is the Cloudwatch Logs are being indexed in the wrong data stream because of the presence of a wrong `dataset`.
See https://github.com/elastic/integrations/blob/b72fe2e619dc1fa8f5a6c0731e3661c940c00b1f/packages/aws/data_stream/cloudwatch_logs/manifest.yml#L181

The consequence of the presence of `data_stream.dataset` set to `generic` is while the assets are installed to work with `logs-aws.cloudwatch_logs-default` data stream, the logs will actually end up in `logs-generic-default`. So no ingest pipelines, mappings or settings of the expected data stream will be used.

This problem has been investigated with the help of @P1llus.

⚠️ Note that given the fact this setting was available to final users, reverting it must be carefully planned as:
- users might have tweaked the setting
- mappings might have been tweaked by users

As it is a quite used integration, we should warn the users if we revert back.

A possible approach is:
- for new policies, do not offer the `dataset` setting and set it to the correct value
- for existing policies where the field exists, we should guide the users on how to go back to the "proper" data stream

Example rendered policy just saving with default values:
```
  - id: aws-cloudwatch-cloudwatch-23aacfba-ffe0-4123-b981-ad713db31b9c
    name: aws-1
    revision: 1
    type: aws-cloudwatch
    use_output: fd5e4b10-ae2d-11ed-91ee-0320f091a587
    meta:
      package:
        name: aws
        version: 1.32.0
    data_stream:
      namespace: default
    package_policy_id: 23aacfba-ffe0-4123-b981-ad713db31b9c
    streams:
      - id: >-
          aws-cloudwatch-aws.cloudwatch_logs-23aacfba-ffe0-4123-b981-ad713db31b9c
        data_stream:
          dataset: generic <<<<<<<<
        region_name: null
        start_position: beginning
        scan_frequency: 1m
        api_sleep: 200ms
        tags:
          - forwarded
          - aws-cloudwatch-logs
        publisher_pipeline.disable_host: true
```
