### ISSUE TITLE
Agent to Filebeat migration for 1Password, excessive loop on pagination

### ISSUE THREAD

**Issue by dpamilih** [elastic/integrations#5471]
Hi All, this is regarding Agent to Filebeat migration for Canva for 1Password API integration. I found that the API pagination logic that built into the agent is not working on the filebeat. My analysis is that with the 1Password API, it always return the same cursor over and over again when it doesn't found any other data and with the settings that is built into the Agent won't trigger any Go Template error which is required for the pagination to stop with `fail_on_template_error: true` settings hence excessive loop:

```yml
  response.pagination:
    - set:
        fail_on_template_error: true
        value: '[[.last_response.body.cursor]]'
        target: body.cursor
```

It seems like the Agent somewhat able to handle the infinite loop and stop the pagination while filebeat will keep on doing the loop and eventually got throttled by 1Password API gateway. I tweaked the config a bit to trigger a Go Template error when the last call returns no items with the help of a dummy header:
```yml
  response.pagination:
    - set:
        fail_on_template_error: true
        value: '[[with .last_response.body.items]][[uuid]][[end]]'
        target: header.X-TEMP
```

tag: @nimarezainia
