### ISSUE TITLE
Cloudflare Logpush - http_request ingest pipeline does not set @Timestamp

### ISSUE THREAD

**Issue by nathangiuliani** [elastic/integrations#5571]
It appears that the `http_request` ingest pipeline does not set the `@Timestamp` field. I assume this is not deliberate as the other ingest pipelines do. Example [here ](https://github.com/elastic/integrations/blob/185e19498616bb697535605aa29f7b61cedc5acb/packages/cloudflare_logpush/data_stream/firewall_event/elasticsearch/ingest_pipeline/default.yml#L25) for `firewall_event`.

The only date processors on the `http_request` pipeline set other fields, not the default `@Timestamp`. This makes looking at the logs a little confusing, although you can filter by one of the other fields as a workaround.

I've duplicated the [date processor that sets the `cloudflare_logpush.http_request.edge.end_time` field](https://github.com/elastic/integrations/blob/185e19498616bb697535605aa29f7b61cedc5acb/packages/cloudflare_logpush/data_stream/http_request/elasticsearch/ingest_pipeline/default.yml#L24) in my test instance, leaving the `target_field` blank to set `@Timestamp`. This works as expected, but I'm not sure if this is the best way to to handle it - perhaps we should only process it once, and copy to the other field?

**Comment by leandrojmp** [comment]
> This works as expected, but I'm not sure if this is the best way to to handle it - perhaps we should only process it once, and copy to the other field?

If I'm not wrong it should use the time from `EdgeStartTimestamp`, which is the time when the request was received by cloudflare, and not `EdgeEndTimestamp`.

The _logpull_ integration has this [processor](https://github.com/elastic/integrations/blob/185e19498616bb697535605aa29f7b61cedc5acb/packages/cloudflare/data_stream/logpull/elasticsearch/ingest_pipeline/http.yml#L21-L31) to set the value for `@timestamp`.

```
- date:
    field: json.EdgeStartTimestamp
    formats:
    - ISO8601
    - uuuu-MM-dd'T'HH:mm:ssX
    - uuuu-MM-dd'T'HH:mm:ss.SSSX
    - yyyy-MM-dd'T'HH:mm:ssZ
    - yyyy-MM-dd'T'HH:mm:ss.SSSZ
    - UNIX_MS
    timezone: UTC
    target_field: "@timestamp"
```
As you can see it uses the value from `EdgeStartTimestamp` to populate the `@timestamp` field.

While I do not use this integration, I'm also using the value of `EdgeStarTimestamp` to populate the `@timestamp` field in my Logstash pipeline, it seems the correct field to use according to the Cloudflare documentation about it.

> EdgeStartTimestamp - Timestamp at which the edge received request from the client.
