### ISSUE TITLE
[O11Y][MongoDB] Update MongoDB dashboards and visualizations

### ISSUE THREAD

**Issue by rajvi-elastic** [elastic/integrations#5846]
# Description

The `mongodb.log.timestamp` column has been used in `[Logs MongoDB] Overview` dashboard. But in the [pipeline](https://github.com/elastic/integrations/blob/main/packages/mongodb/data_stream/log/elasticsearch/ingest_pipeline/pipeline-plaintext.yml#L9-L15) `mongodb.log.timestamp` field has been removed. 

```
- date:
    field: mongodb.log.timestamp
    target_field: '@timestamp'
    formats:
    - yyyy-MM-dd'T'HH:mm:ss.SSSZZ
- remove:
    field: mongodb.log.timestamp
```

## Task
- [ ] Remove `mongodb.log.timestamp` field from  dashboard and visualizations

## Screenshots

![image](https://raw.githubusercontent.com/elastic/integrations/5c49ab0cbbba404aba6620a21d2592ca3c9681f0/packages/mongodb/img/filebeat-mongodb-overview.png)
