### ISSUE TITLE
[TSDB] [Kafka] Update dimension field limit settings for consumergroup datastream

### ISSUE THREAD

**Issue by agithomas** [elastic/integrations#6278]
Include below setting for consumergroup datastream as the dimensions exceeded the default 16
```yaml
elasticsearch:
  index_template:
    settings:
      index.mapping.dimension_fields.limit: 24
```
