### ISSUE TITLE
Elastic Agent http_endpoint integration does not allow multiple include headers

### ISSUE THREAD

**Issue by psanz-estc** [elastic/integrations#6523]
In Elastic Agent http_endpoint integration there is a configuration called `include_headers`. 

If you only set a single header here, it is working fine (e.g. only x-real-ip will add the headers.X-Real-Ip field in the indexed document). 

As soon as you set multiple headers (e.g. x-real-ip and user-agent), it will not set any `headers.*` field.

![image](https://github.com/elastic/integrations/assets/44199691/1fe0bca7-42ce-4822-a5af-d449b74f2b27)

That configuration translates into:

```
 - data_stream:
      dataset:user-events
    id: http_endpoint-http_endpoint.generic-ad5d8570-0456-11ee-a2d5-1234567890
    include_headers: user-agent,x-real-ip
    listen_address: 0.0.0.0
    listen_port: 8080
    pipeline: logs-user-events
    preserve_original_event: true
```

But as mentioned, the fields are not populated.
