### ISSUE TITLE
[ti_misp] ti_misp threat attributes pipeline duplicating events.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#6686]
Hello,

On Friday we added the MISP Integration on our Elastic Agent to collect MISP Attributes from our MISP, currently we have around ~ 716k attributes, but today looking at the data stream we had more than 4 million events.

Investigating the issue I saw that every event has many duplicates, basically one duplicate for every hour the integration has been running.

The following image shows an example of a duplicates event.
![Screenshot from 2023-06-24 22-10-51](https://github.com/elastic/integrations/assets/322886/ae88da97-5c63-47af-8399-8947e06e72f2)

Looking at the ingest pipeline I saw that there is a fingerprint processor to generate an `_id` based on two fields:

```
  - fingerprint:
      fields:
        - misp.attribute.Attribute.uuid
        - misp.attribute.Attribute.Event.uuid
      target_field: "_id"
      ignore_missing: true
```

But that `Attribute` field does not exist in the message.

The response from the endpoint `/attributes/restSearch` is something like this:

```
{ "response": { "Attribute": [ array with the attributes ] }}
```

In the httpjson input there is a split on the field `body.response.Attribute` with `keep_parent` set to **false**, this will then put each attribute _on the root of the message_ that will be processed by the ingest pipeline.

```
response.split:
  target: body.response.Attribute
  ignore_empty_value: true
  keep_parent: false
```

This message will then be copied into `event.original` where a json filter will be applied with a target of `misp.attribute`.

So there will be no `misp.attribute.Attribute.uuid` nor `misp.attribute.Attribute.Event.uuid`, the correct fields would be:
- `misp.attribute.uuid`
- `misp.attribute.Event.uuid`

The `uuid` and `Event` field would be at the root of the message, later in the ingest pipeline the `misp.attribute.Event` field is even correctly renamed to `misp.event`.

I deleted the integration and will try to add it again on Monday and edit the ingest pipeline to see if this fix the issue.

Another issue is, why is it duplicating documents anyway?

From my understanding the API requests should not look back in time after the initial interval, for example, in the image shared above it indexed the same document from March 2nd multiple times, this would mean that a request for the API returned this document multiple times, which does not make much sense since the cursor for the timestamp should be moving forward.
