### ISSUE TITLE
[Azure] Make sure query filters work without resource types

### ISSUE THREAD

**Issue by sorantis** [elastic/integrations#693]
As a user I want to be able to monitor my Azure resources that have a certain tag. 
Today this is possible with the `resource_query` option in the monitor metricset, however this configuration method requires a resource type to be specified, which is not ideal because the same tag can be set to various Azure resources.

Check of the current implementation can work without resource types.

**Comment by narph** [comment]
Current implementation will return the resources that contain a specific tag name and/or tag value, ex config:

```
  resources:
  - resource_query: "tagName eq 'module' and tagValue eq 'azure'"
    metrics:
    - name: ["*"]
      namespace: ""
```

Since different types of resources can have the same tag name and tag value then the namespace or explicit metrics should not be configured. 
Instead, we can retrieve the default/supported namespace for each resource and then all metrics for each namespace. (not implemented yet)
