### ISSUE TITLE
[Azure] [container_instance] Not correct metrics field

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#7158]
azure_metrics datastrems are using rename processor to rename `azure.metrics` to `azure.{datastream_name}`
https://github.com/elastic/integrations/blob/main/packages/azure_metrics/data_stream/container_registry/elasticsearch/ingest_pipeline/default.yml#L7-L10

For `container_instance` is used `azure.monitor` field - https://github.com/elastic/integrations/blob/main/packages/azure_metrics/data_stream/container_instance/elasticsearch/ingest_pipeline/default.yml#L7-L10, that does not exist.

As result metrics are reported under `azure.metrics`, instead of under `azure.container_instance`

**Comment by zmoog** [comment]
Yeah, this is an bug.

We need to fix the rename processor and related dashboard, if exists. We also need to make use of existing data collected with the wrong name.

For the existing data, I think we can add a field mapping with an `alias` for the wrong name.  I take this issue, fix this processor error, and try the alias solution.

**Comment by zmoog** [comment]
@tetianakravchenko, I ran some test about using the [alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/field-alias.html) field type to make the `azure.metrics.*` fields available for those users who installed the integration and collected some data using the wrong field name.

Starting from the extended fields definition you are adding with #7127 :

```yaml
- name: azure.container_instance
  type: group
  fields:
    - name: cpu_usage.avg
      type: float
      metric_type: gauge
      description: CPU usage on all cores in millicores.
    - name: memory_usage.avg
      type: float
      metric_type: gauge
      unit: byte
      description: Total memory usage in byte.
    - name: network_bytes_received_per_second.avg
      type: float
      metric_type: gauge
      unit: byte
      description: The network bytes received per second.
    - name: network_bytes_transmitted_per_second.avg
      type: float
      metric_type: gauge
      unit: byte
      description: The network bytes transmitted per second.
```

I added the following aliases:

```yaml
- name: azure.metrics.cpu_usage.avg
  type: alias
  path: azure.container_instance.cpu_usage.avg
- name: azure.metrics.memory_usage.avg
  type: alias
  path: azure.container_instance.memory_usage.avg
- name: azure.metrics.network_bytes_received_per_second.avg
  type: alias
  path: azure.container_instance.network_bytes_received_per_second.avg
- name: azure.metrics.network_bytes_transmitted_per_second.avg
  type: alias
  path: azure.container_instance.network_bytes_transmitted_per_second.avg
```

With this change, the installed mapping for the integration looks like this:

```json
{
    "metrics": {
        "properties": {
            "cpu_usage": {
                "properties": {
                    "avg": {
                        "type": "alias",
                        "path": "azure.container_instance.cpu_usage.avg"
                    }
                }
            },
            "memory_usage": {
                "properties": {
                    "avg": {
                        "type": "alias",
                        "path": "azure.container_instance.memory_usage.avg"
                    }
                }
            },
            "network_bytes_received_per_second": {
                "properties": {
                    "avg": {
                        "type": "alias",
                        "path": "azure.container_instance.network_bytes_received_per_second.avg"
                    }
                }
            },
            "network_bytes_transmitted_per_second": {
                "properties": {
                    "avg": {
                        "type": "alias",
                        "path": "azure.container_instance.network_bytes_transmitted_per_second.avg"
                    }
                }
            }
        }
    }
}
```

And now we can use both `azure.container_instance.*` or `azure.metrics.*` fields to query the data stream:

```
# both queries return the same data

POST metrics-azure.container_instance-default/_search
{
  "query": {
    "range": {
      "azure.container_instance.cpu_usage.avg": {
        "gte": 0
      }
    }
  }
}

POST metrics-azure.container_instance-default/_search
{
  "query": {
    "range": {
      "azure.metrics.cpu_usage.avg": {
        "gte": 0
      }
    }
  }
}
```

I can see both fields in Discover too:

<img width="1895" alt="image" src="https://github.com/elastic/integrations/assets/25941/eb219988-4edc-4c1a-8d05-01f7ae4ecaf4">
