### ISSUE TITLE
[Azure] [container_service] Duplicated documents for the `kube_node_status_condition` metric

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/integrations#7160]
for the `container_service` data_stream: some documents will be dropped after enabling TSDB due to duplications, mainly for the `kube_node_status_condition` metric - since each condition is stored in separate document:

example: for the same node/status and condition there are multiple documents with the same metric value:
<img width="2417" alt="Screenshot 2023-07-25 at 16 29 03" src="https://github.com/elastic/integrations/assets/28299531/4b40d3c9-98df-4df4-8345-5c804fac2a1f">

we checked together with @zmoog and could easily reproduce this behavior

cc @tommyers-elastic

**Comment by tommyers-elastic** [comment]
is node status condition a dimension? if so we will only drop identical docs, which seems ok to me?

**Comment by tetianakravchenko** [comment]
@tommyers-elastic yes, `node`, `status` and `condition` are dimensions. On the screenshot it is a "good" example, I will try to provide different example.

I think we shouldn't move de-duplication logic to the tsdb, instead it should be on the beats side

**Comment by tommyers-elastic** [comment]
we are going to look into the azure API response here to ensure we are not missing some dimensions. once that is confirmed we can come back to the discussion about where is the appropriate place to do the deduplication, if necessary.

**Comment by zmoog** [comment]
@tetianakravchenko, I think I now have a good understanding of why we're getting multiple documents with the same dimension values.

I created the PR elastic/integrations#7160 and experimented with a solution. I hope to wrap this up soon.

**Comment by zmoog** [comment]
I'm expanding the commit message a little.

The integration/model sets up dimensions in the config:

```yaml
    resources:
    - resource_group: ""
      resource_type: "Microsoft.ContainerService/managedClusters"
      metrics:
      - name: ["kube_node_status_condition"]
        namespace: "Microsoft.ContainerService/managedClusters"
        ignore_unsupported: true
        timegrain: "PT5M"
        dimensions:
        - name: "node"
          value: "*"
        - name: "status"
          value: "*"
        - name: "condition"
          value: "*"
```

When we have dimensions, the [current implementation](https://github.com/elastic/beats/blob/a6bae85b20b85985fe4e8adb641bc51902251e89/x-pack/metricbeat/module/azure/data.go#L76-L80) groups metrics response by timestamp + dimension (just one).

Grouping by timestamp + single dimension can sometimes lead to multiple documents with the same dimension values. 

Here's an example where we have 10 metrics values right before entering the final groupings:

![CleanShot 2023-09-04 at 01 21 35@2x](https://github.com/elastic/integrations/assets/25941/f2af4bb0-afff-42c1-885f-522eb726f212)

At this point, the current implementation starts grouping these 10 metric values by each single dimension. Here are screenshots of the groupings:

![CleanShot 2023-09-04 at 00 58 58@2x](https://github.com/elastic/integrations/assets/25941/58720527-f3aa-4354-afee-a080ed28af38)

![CleanShot 2023-09-04 at 00 59 15@2x](https://github.com/elastic/integrations/assets/25941/550fe0cd-0515-4f61-9256-899b46a7af27)

![CleanShot 2023-09-04 at 00 59 45@2x](https://github.com/elastic/integrations/assets/25941/30942797-272c-4487-8335-e531fb157736)

This grouping does not play well with TSDB because it expects all documents with the same timestamp to have
a unique combination of dimensions values.

Here's the result of the grouping: we end up having 1 + 2 + 10 = 13 documents in Elasticsearch:

![CleanShot 2023-09-04 at 01 08 17@2x](https://github.com/elastic/integrations/assets/25941/1e849a16-42bb-430a-af8f-40201de736f0)
