### ISSUE TITLE
[modsecurity] Pipeline error in case of nginx server_tokens off

### ISSUE THREAD

**Issue by boomaker** [elastic/integrations#7286]
In case of nginx is configured with `server_tokens off`, modsecurity integration pipeline will fail with this error:

![image](https://github.com/elastic/integrations/assets/1837884/a99b0c06-83f5-4161-944f-2378cc8223c4)

This is because the pipeline is based on the `Server` HTTP response header found in the modsecurity audit log:

https://github.com/elastic/integrations/blob/main/packages/modsecurity/data_stream/auditlog/elasticsearch/ingest_pipeline/default.yml#L23C33-L24C58
```
  - set:
      field: modsec.audit.server
      copy_from: json.transaction.response.headers.Server
      ignore_empty_value: true
  - pipeline:
      name: '{{ IngestPipeline "nginx-modsec" }}'
      if: ctx.modsec.audit.server.toLowerCase().contains('nginx')
  - pipeline:
      name: '{{ IngestPipeline "apache-modsec" }}'
      if: ctx.modsec.audit.server.toLowerCase().contains('apache')
```

I suggest to use transaction.producer.connector field which is more constant to trigger the apache/nginx pipelines:

```
{
    "transaction": {
        [...]
        "producer": {
            "modsecurity": "ModSecurity v3.0.8 (Linux)",
            "connector": "ModSecurity-nginx v1.0.3",
            "secrules_engine": "Enabled",
            "components": ["OWASP_CRS/3.3.4\""]
        },
        "messages": []
    }
}
```
