### ISSUE TITLE
Fix support for IAM role arn in aws config

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/integrations#738]
I added support for IAM role ARN into `aws` package in https://github.com/elastic/beats/pull/17658 but I believe this credential configuration method still relies on the shared credential file default profile. This issue is to investigate IAM role ARN configuration and improve it in both Beats and the integrations package.

Using metricbeat config as an example, we should be able to also specify `credential_profile_name` and/or `shared_credential_file` along with `role_arn` when the default credential is not at the default location. For example:
```
- module: aws
  period: 5m
  role_arn: arn:aws:iam::123456789012:role/example-role
  shared_credential_file: /Users/kaiyansheng/.aws/credentials_backup
  credential_profile_name: test
  metricsets:
    - ec2
```
