### ISSUE TITLE
Prometheus integration default settings not working

### ISSUE THREAD

**Issue by anmironov** [elastic/integrations#7652]
Integration version 1.11.0

Default settings for Prometheus integration https://docs.elastic.co/integrations/prometheus contain not working placeholder config (see below). It would be better to have a link to the docs or Prometheus querying instead of it.

Prometheus query metrics:
```
- name: instant_vector
  params:
    query: sum(rate(prometheus_http_requests_total[2m]))
  path: /api/v1/query
- name: range_vector
  params:
    end: "2019-12-21T00:00:00.000Z"
    query: up
    start: "2019-12-20T00:00:00.000Z"
    step: 1h
  path: /api/v1/query_range
- name: scalar
  params:
    query: "100"
  path: /api/v1/query
- name: string
  params:
    query: some_value
  path: /api/v1/query

```
