### ISSUE TITLE
elastic-agent system module - filesystem.ignore_types in metricbeat is not being applied

### ISSUE THREAD

**Issue by TheRiffRafi** [elastic/integrations#7703]
- Version:  8.9.0
- Operating System: Windows

- Steps to Reproduce: 

1. Have a Elasticsearch - Fleet - Elastic Agent setup. 
2. Install the "system" integration to an agent. Go to the integrations settings, the metrics section, filesystem, and add to the `List of filesystem types to ignore` the `unknown` and `unavailable` values in a row each. 
3. Save and observe how the Elastic Agent logs still show the error:
`{"log.level":"error","@timestamp":"2023-04-06T08:59:18.495+0200","log.origin":{"[file.name](https://file.name/)":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset system.filesystem: error getting filesystem usage for [Z:\\](file:///Z://): GetDiskFreeSpaceEx failed: The device is not ready.","[service.name](https://service.name/)":"metricbeat","ecs.version":"1.6.0"}`

### Something worth pointing out.

I don't know if the way the list is built has something to do with this. 
I went looking into how the `ignore_types` is done in Metricbeat (no Elastic Agent paired) and the values are each part of an array:

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-filesystem.html#_filtering

When looking at the Elastic Agent diagnostic, I see that the values are passed as a string-value:

```
 - kind:
                    structvalue:
                      fields:
                        data_stream:
                          kind:
                            structvalue:
                              fields:
                                dataset:
                                  kind:
                                    stringvalue: system.filesystem
                                type:
                                  kind:
                                    stringvalue: metrics
                        filesystem.ignore_types:
                          kind:
                            stringvalue: unknown,unavailable,cdfs
```

And looking at the yml file from the policy, it comes up as a string:

```
        filesystem.ignore_types: 'unknown,unavailable,cdfs'
```
I don't know enough on how the options sent to the Metricbeat process are built so my guess is probably completely wrong, but I thought it was worth pointing out.

I've seen this setting not working twice. Here is another reference: https://github.com/elastic/beats/issues/35187#issuecomment-1632955693

**Comment by willem-dhaese** [comment]
We get a lot of the following errors on Windows Servers:

`error getting filesystem usage for D:\: GetDiskFreeSpaceEx failed: The device is not ready.`

D:\ is a virtual DVD Drive

![image](https://github.com/elastic/integrations/assets/147597619/c7b789aa-e0be-4554-829c-e5796f902abf)

Will the resolution of this issue resolve these errors. What filesystem type do we need to exclude?

**Comment by TheRiffRafi** [comment]
Hi @willem-dhaese, this fix will target a bug where an "array" can't be provided as a list of filesystem types to exclude. So once this fix is addressed, then you can add "unknown" **AND** "unavailable" as the filesystem types to exclude and that will resolve the issue. 

If you are not running an elastic-agent integration, and instead you are running `metricbeat` as a standalone application, then you just have to add those types in the exclude list as shown in this comment: https://github.com/elastic/beats/issues/35187#issuecomment-1587665947

**Comment by StefanSa** [comment]
@TheRiffRafi Hi Rafi,
when will there be a solution for this, have the same problems as @willem-dhaese .

**Comment by 1Atlas1** [comment]
Adding the following to the processor fixed it for me:

```
- drop_event.when.regexp:
    system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
- or:
        - equals:
            system.filesystem.type: 'unknown'
        - equals:
            system.filesystem.type: 'unavailable'
```

![image](https://github.com/elastic/integrations/assets/74820576/b9fe8764-89cb-4ca8-9e20-afb324f18242)
