### ISSUE TITLE
Incomplete metrics in 8.8.2 stack version with cloudwatch metricset

### ISSUE THREAD

**Issue by lucian-ioan** [elastic/integrations#7733]
The metrics fetched for the AWS API Gateway Integration are incomplete in 8.8.2 stack version. Testing was done for 8.8.2 and 8.9.0.

Document Example for 8.8.2: 
-------------------------------
![API_Gateway_8 8 2](https://github.com/elastic/integrations/assets/59661554/d2c437b7-2166-4918-ae2d-025def60c90c)

Issues: Lots of missing data points, all metrics appear to be inconsistently fetched.

Document Example for 8.9.0:
-------------------------------

![apigateway_8 9 0](https://github.com/elastic/integrations/assets/59661554/759b4882-1d50-42ed-bbdd-2214ada152bb)

Issue:  The data follows the above format consistently, however it isn't immediately obvious why some data points are missing and why the extra documents are there.

_Later edit: This is consistent with the CloudWatch groupings by metrics/dimensions and is the intended document format (although uncommon):_

1) The first document with no dimensions and just the `Count.sum` metric adds the `Count.sum` from both lucian-REST-PetStore and PetStore (48+24=72).
2) The following 2 documents with the `apiName` dimension present have the `Count.sum` per API.
3) The following 3 documents filter `Count.Sum` by API and stage (here 4XX Errors are also considered).
4) The last 6 documents accurately the number of successful requests per API/stage/path.

How to replicate
------------------
1. Create REST APIs in AWS API Gateway and deploy them. I am using 2 APIs: `lucian-REST-PetStore` (stages beta and prod, path /pets) and `PetStore` (stage First_Stage, path /pets).

3. Set up a script to constantly generate data from the API endpoints. I am using a script that does the following every 60 seconds:

> 2 `GET` requests into `lucian-REST-PetStore/beta/pets` and `lucian-REST-PetStore/prod/pets` 
> 1 `GET` request into `lucian-REST-PetStore/beta` and `lucian-REST-PetStore/prod`
> 1 `GET` request into `PetStore/First_Stage `
> 
> 2 `POST` requests into `lucian-REST-PetStore/beta/pets` and `lucian-REST-PetStore/prod/pets` 
> 1 `POST` request into `lucian-REST-PetStore/First_Stage`, `lucian-REST-PetStore/beta` and  `lucian-REST-PetStore/prod` which returns a `4XX Error`.

3. Run the Elastic stack locally using elastic-package for 8.9.0 (aws 2.2.0) and 8.8.2 (aws 1.51.2) versions . Set up the AWS API Gateway integration and check the box to collect metrics with Latency set to 5m.

4. Wait a bit for the metrics to get fetched from CloudWatch, filter the data in Kibana Discover using `data_stream.dataset : "aws.apigateway_metrics"` and add the columns in the document screenshots.

**Comment by lucian-ioan** [comment]
Note that this bug happens while using a single stage as well:

![metrics_AWS](https://github.com/elastic/integrations/assets/59661554/b19cdeef-b6d1-431f-856c-7772a4bcb5ba)

**Comment by lalit-satapathy** [comment]
@lucian-ioan,
 
Since the metrics are ingested for both with and without dimensions, so need to keep them separate.

It's not clear to me why results would vary between two ES version, unless the metricbeat cloudwatch code has changed.

When we are comparing two sets of metrics, Can we compare them when a fixed dimension set(Apiname,stage,resource & method)? If the dimension set is same and for a given timestamp, Are we seeing differing values?

**Comment by lucian-ioan** [comment]
@lalit-satapathy 

I am seeing the following while only using a GET request every 15 seconds for a single REST API endpoint:

8.8.2
-----
![document_8 8 2](https://github.com/elastic/integrations/assets/59661554/671caf47-42f0-4e55-9502-2f4e268b3059)

8.9.0
-----
![document_8 9 0](https://github.com/elastic/integrations/assets/59661554/f5dd963f-7061-445f-904a-1d4fd180c599)


`Count` and `4XXError` are metrics not found in 8.8.2 for the document with `apiName` as a dimension.

There's also a difference in the number of documents fetched, with 8.8.2 missing the additional third document with no dimensions.

**Comment by lalit-satapathy** [comment]
Thanks @lucian-ioan this helps.

>Count and 4XXError are metrics not found in 8.8.2 for the document with apiName as a dimension.

Can we run the exact same setup with [metricbeat cloudwatch](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-cloudwatch.html) directly and summarise the difference of documents (if any) between 8.8.2 vs 8.9.0? This will ignore any potential integration and/or TSDB angle and also narrow down the issue to metricbeat.

**Comment by lucian-ioan** [comment]
@lalit-satapathy Debugged with metricbeat 8.8.2 and 8.9.0.  The results are the same as above (both in metrics/dimensions and number of documents). 

<details>
<summary>8.8.2 document with ApiName dimension</summary>

```
{
  "aws": {
    "apigateway": {
      "metrics": {
        "5XXError": {
          "sum": 0
        },
        "IntegrationLatency": {
          "avg": 3.0526315789473686
        },
        "Latency": {
          "avg": 5.842105263157895
        }
      }
    },
    "cloudwatch": {
      "namespace": "AWS/ApiGateway"
    },
    "dimensions": {
      "ApiName": "lucian-REST-PetStore"
    }
  },
  "cloud": {
    "account": {
      "id": "627286350134",
      "name": "MonitoringAccount"
    },
    "provider": "aws",
    "region": "us-east-1"
  },
  "event": {
    "dataset": "aws.cloudwatch",
    "duration": 1025728033,
    "module": "aws"
  },
  "metricset": {
    "name": "cloudwatch",
    "period": 300000
  },
  "service": {
    "type": "aws"
  }
}
```



</details> 


<details>
<summary>8.9.0 document with ApiName dimension</summary>

```
{
  "aws": {
    "apigateway": {
      "metrics": {
        "4XXError": {
          "sum": 0
        },
        "5XXError": {
          "sum": 0
        },
        "Count": {
          "sum": 19
        },
        "IntegrationLatency": {
          "avg": 3.263157894736842
        },
        "Latency": {
          "avg": 6.947368421052632
        }
      }
    },
    "cloudwatch": {
      "namespace": "AWS/ApiGateway"
    },
    "dimensions": {
      "ApiName": "lucian-REST-PetStore"
    }
  },
  "cloud": {
    "account": {
      "id": "627286350134",
      "name": "MonitoringAccount"
    },
    "provider": "aws",
    "region": "us-east-1"
  },
  "event": {
    "dataset": "aws.cloudwatch",
    "duration": 1677619194,
    "module": "aws"
  },
  "metricset": {
    "name": "cloudwatch",
    "period": 300000
  },
  "service": {
    "type": "aws"
  }
}
```



</details> 


As far as I can tell, TSDB has nothing to do with this behavior.

**Comment by kaiyan-sheng** [comment]
I tested with `8.8.2` and the `main` branch of metricbeat and was able to reproduce this issue. One thing I noticed is: if dimension `ApiName` is specified in the CloudWatch metricset config, both `8.8.2` and `main` branch work fine.
```
- module: aws
  period: 5m
  credential_profile_name: elastic-observability
  metricsets:
    - cloudwatch
  metrics:
    - namespace: AWS/ApiGateway
      statistic: [ "Sum" ]
      dimensions:
        - name: ApiName
          value: lucian-REST-PetStore
      name:
      name:
        - 4XXError
        - 4xx
        - 5XXError
        - 5xx
        - CacheHitCount
        - CacheMissCount
        - Count
        - ConnectCount
        - MessageCount
        - IntegrationError
        - ClientError
        - ExecutionError
    - namespace: AWS/ApiGateway
      statistic: [ "Average" ]
      dimensions:
        - name: ApiName
          value: lucian-REST-PetStore
      name:
      name:
        - Latency
        - IntegrationLatency
        - DataProcessed
```
Will look into this issue more tomorrow!
