### ISSUE TITLE
Allow url in prometheus query variables

### ISSUE THREAD

**Issue by bartoszcisek** [elastic/integrations#7886]
**Describe the enhancement:**

Currently prometheus integration `query` config variable accept variables, but escape them before creating query.

```
  - id: prometheus/metrics-prometheus-${kubernetes.hints.container_id}
    name: prometheus-1
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.12.0
    data_stream:
      namespace: default
    processors:
      - drop_fields:
          fields: ["/^kubernetes.node./", "/^kubernetes.namespace_labels/", "kubernetes.namespace_uid"]
      - add_fields:
          fields:
            name: default
          target: orchestrator.cluster
    streams:
      - condition: ${kubernetes.hints.prometheus.collector.enabled} == true or ${kubernetes.hints.prometheus.enabled} == true
        data_stream:
          dataset: prometheus.collector
          type: metrics
        hosts:
          - ${kubernetes.hints.prometheus.collector.host|kubernetes.hints.prometheus.host|'localhost:9090'}
        metrics_filters.exclude: null
        metrics_filters.include: null
        metrics_path: '/probe'
        metricsets:
          - collector
        period: ${kubernetes.hints.prometheus.collector.period|kubernetes.hints.prometheus.period|'60s'}
        rate_counters: true
        timeout: ${kubernetes.hints.prometheus.collector.timeout|kubernetes.hints.prometheus.timeout|'3s'}
        use_types: true
        query:
          target: "http://127.0.0.1:3000/json/endpoint"
``` 

Results in query to `json-exporter`:

```
http://10.1.1.1:9090/probe?target=http%3A%2F%2F127.0.0.1%3A3000%2Fjson%2Fendpoint
```

**Describe a specific use case for the enhancement or feature:**

`json_exporter`, `blackbox_exporter` allow unified configuration where specific endpoint url is passed via `target` variable. 

**What is the definition of done?**

Query variables allow URL type values, which are not escaped.  

**Notes**
Cross posting https://github.com/elastic/elastic-agent/issues/3421

**Comment by belimawr** [comment]
Looking at the documentation/example provided in the integration page (in Kibana go to Integrations -> Prometheus -> Configs) (`https://<your kibana URL>/app/integrations/detail/prometheus-1.13.1/configs`), that seems to be the correct behaviour to me.

There is a `hosts` field that can be used to configure Prometheus host, any query string parameters go into the `query` map.

If I understood it correctly you would like to set the host field the integration is using to query Prometheus, is that correct?

So in the example you posted we can see (I'm quoting only the interesting parts here):
```yaml
        hosts:
          - ${kubernetes.hints.prometheus.collector.host|kubernetes.hints.prometheus.host|'localhost:9090'}
        query:
          target: "http://127.0.0.1:3000/json/endpoint"
```
And looking at the final URL you mentioned:
```
http://10.1.1.1:9090/probe?target=http%3A%2F%2F127.0.0.1%3A3000%2Fjson%2Fendpoint
```
The `query` is correctly URL escaped, the host (`http://10.1.1.1:9090/`) looks to be coming from the  Kubernetes hints from the `host` field, so either `kubernetes.hints.prometheus.collector.host` or `kubernetes.hints.prometheus.host` are resolving to `http://10.1.1.1:9090`

**Comment by belimawr** [comment]
I did some testing on a Fleet managed Elastic-Agent and it works as I described. For the Prometheus host I used `https://httpdump.app/` that will give you a URL dumping all requests made against it.

My input YAML configuration (I added a few extra query parameters just for the sake of testing):
```
  - id: prometheus/metrics-prometheus-fd262db7-f731-430f-bfb1-c741e15d8f3d
    name: prometheus-1
    revision: 2
    type: prometheus/metrics
    use_output: default
    meta:
      package:
        name: prometheus
        version: 1.13.1
    data_stream:
      namespace: default
    package_policy_id: fd262db7-f731-430f-bfb1-c741e15d8f3d
    streams:
      - id: >-
          prometheus/metrics-prometheus.collector-fd262db7-f731-430f-bfb1-c741e15d8f3d
        data_stream:
          dataset: prometheus.collector
        metricsets:
          - collector
        hosts:
          - 'https://httpdump.app/dumps/2ecc5393-3ed4-483a-ac45-48defce229a3'
        metrics_filters.exclude: null
        metrics_filters.include: null
        metrics_path: /metrics
        period: 10s
        rate_counters: true
        use_types: true
        username: user
        password: secret
        query:
          target: 'http://127.0.0.1:3000/json/endpoint'
          foo: bar
          answer: 42
```
Note that `hosts` is set to the `httpdump.app` URL
The final requests are as expected:
```
https://httpdump.app/dumps/2ecc5393-3ed4-483a-ac45-48defce229a3?answer=42&foo=bar&target=http%3A%2F%2F127.0.0.1%3A3000%2Fjson%2Fendpoint
```

A screenshot showing the full request:
![2023-11-03_08-56](https://github.com/elastic/integrations/assets/333577/f7fa71f6-d44f-41a7-b3e4-2710a17716ce)
