### ISSUE TITLE
[Fleet] Fleet server integration is missing an input agent template

### ISSUE THREAD

**Issue by nchaulet** [elastic/integrations#803]
## Description 

Currently we do not send the config from kibana to fleet server as there is not input agent template, we should add one.
<img width="622" alt="Screen Shot 2021-03-24 at 2 49 18 PM" src="https://user-images.githubusercontent.com/1336873/112367318-23577900-8cb0-11eb-9c06-ef834db18585.png">

@blakerouse can you confirm we just need to add the `host` and `port` field in the following input right?

**Comment by blakerouse** [comment]
Correct looks like `host` and `port` is missing.

```
  - id: 98c08e57-6a5a-4427-950c-28f7673f7e4b
    name: fleet_server-1
    revision: 1
    type: fleet-server
    use_output: default
    meta:
      package:
        name: fleet_server
        version: 0.2.4
    data_stream:
      namespace: default
    server:
      host: 0.0.0.0
      port: 8220
```

**Comment by ph** [comment]
@nchaulet Do you think we could add  `max_connection` too https://github.com/elastic/fleet-server/pull/122/files#diff-f49cf4b4933ac6234edb14219c265a94752d5d7e034f22cb9af3d11ef3f3d84aR73  ?

**Comment by blakerouse** [comment]
Max connections would sit alongside of the `host` and `port`. So example configuration would be:

```
  - id: 98c08e57-6a5a-4427-950c-28f7673f7e4b
    name: fleet_server-1
    revision: 1
    type: fleet-server
    use_output: default
    meta:
      package:
        name: fleet_server
        version: 0.2.4
    data_stream:
      namespace: default
    server:
      host: 0.0.0.0
      port: 8220
      max_connections: 100
```

**Comment by nchaulet** [comment]
@blakerouse  I have the following policy but looks like when running in a docker container it's still binding fleetserver to localhost
```
inputs:
  - id: b70dd004-cb50-4215-b552-6cbf4f2aa80b
    name: fleet_server-1
    revision: 3
    type: fleet-server
    use_output: default
    meta:
      package:
        name: fleet_server
        version: 0.2.7
    data_stream:
      namespace: default
    server:
      port: '8220'
      host: 0.0.0.0
```
