### ISSUE TITLE
[SEI] Add check for `event.original` rename/set to avoid issues with Logstash events

### ISSUE THREAD

**Issue by marc-gr** [elastic/integrations#8146]
Since Logstash sets `event.original` by default on all events our integration pipelines fail if they do not have a specific check to avoid renaming/setting the `event.original` value if it already exists.

Changes need to be made to have a check such as:

```
  - rename:
      field: message
      target_field: event.original
      ignore_missing: true
      if: ctx.event?.original == null
```

For all our integrations.

Special attention with cases where instead of rename we use `set` or others and to check if further references to `message` need to be changed to `event.original` in addition.
