### ISSUE TITLE
[System] System Auth Ingest pipeline seems to fail if event.original already exists.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#8244]
Hello,

It seems that the auth ingest pipeline of the System integration can fail if the `event.original` field is present in the document.

In the beginning of the pipeline there is this processor:

```
  - rename:
      if: ctx.event?.original == null
      field: message
      target_field: event.original
      ignore_missing: true
```

It will rename the `message` field into `event.original` if it does not exist, if `event.original` exists it will do nothing.

But later on we have this `grok`:

```
  - grok:
      description: Grok specific auth messages.
      tag: grok-specific-messages
      field: _temp.message
      ignore_missing: true
      patterns:
        - '^%{DATA:system.auth.ssh.event} %{DATA:system.auth.ssh.method} for (invalid user)?%{DATA:user.name} from %{IPORHOST:source.address} port %{NUMBER:source.port:long} ssh2(: %{GREEDYDATA:system.auth.ssh.signature})?'
        - '^%{DATA:system.auth.ssh.event} user %{DATA:user.name} from %{IPORHOST:source.address}'
        - '^Did not receive identification string from %{IPORHOST:system.auth.ssh.dropped_ip}'
        - '^%{DATA:user.name} :( %{DATA:system.auth.sudo.error} ;)? TTY=%{DATA:system.auth.sudo.tty} ; PWD=%{DATA:system.auth.sudo.pwd} ; USER=%{DATA:system.auth.sudo.user} ; COMMAND=%{GREEDYDATA:system.auth.sudo.command}'
        - '^new group: name=%{DATA:group.name}, GID=%{NUMBER:group.id}'
        - '^new user: name=%{DATA:user.name}, UID=%{NUMBER:user.id}, GID=%{NUMBER:group.id}, home=%{DATA:system.auth.useradd.home}, shell=%{DATA:system.auth.useradd.shell}$'
      on_failure:
        - rename:
            description: Leave the unmatched content in message.
            field: _temp.message
            target_field: message
```

On this grok there is a `on_failure` setting that will try to rename the field `_temp.message` into `message`, but if the `event.original` already exists in the event, the `message` field will not be renamed and will still exist in this stage of the pipeline, so the `rename` processor will fail and this will terminate the entire pipeline.

If you use Logstash between Elastic Agent and Elasticsearch the field `event.original` will be added, and this ingest pipeline will fail in almost all messages.

I have just a couple of hosts at the moment, but today the `system.auth` dataset received more than 3k messages and just 90 of those messages didn't fail, the rest of them have the `error.message` field with the following value:

> field [message] already exists

I think that removing this `on_failure` processor and just working with `_temp.message` until the end of the pipeline would solve this issue.

Looking for similar issues, I found this one #4925 from January this year, so this is happening at least since version 1.20 of the integration.
