### ISSUE TITLE
[ Prisma Cloud ] Audit Pipeline does not create user.name field.

### ISSUE THREAD

**Issue by leandrojmp** [elastic/integrations#8311]
Hello,

The audit pipeline for the Prisma Cloud integration creates a field named `user.email`, but it does not create the `user.name` field that can be extracted from the user field.

The `user.email` is created by these two processors:

```
  - rename:
      field: json.user
      tag: rename_prisma_cloud_audit_user
      target_field: prisma_cloud.audit.user
      ignore_missing: true
  - set:
      field: user.email
      tag: set_prisma_cloud_audit_user
      copy_from: prisma_cloud.audit.user
      ignore_empty_value: true
```

The field `user.email` with the value `user@company.domain` could be used as a source to create `user.name` and `user.domain`.

I think that the following dissect processor could work:

```
  - dissect:
      field: user.email
      tag: create_user_name_and_user_domain
      pattern: "%{user.name}@%{user.domain}"
      ignore_missing: true
      if: ctx.user?.email != null
      on_failure:
        - append:
            field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
```

And also the `related.user` would need to be changed as well:

```
  - append:
      field: related.user
      tag: append_user_name_to_related_user
      value: '{{{user.name}}}'
      allow_duplicates: false
      if: ctx.user?.name != null
```

The `user.name` field is important because it is used to correlate with other data sources, it is more useful than `user.email`.

I could make a PR, but I'm not sure how to add the mappings to `user.name` and `user.domain`.
