### ISSUE TITLE
[etcd] Incorrect leader field definitions

### ISSUE THREAD

**Issue by gpop63** [elastic/integrations#8373]
## Overview

In our ongoing effort to enable TSDB for `etcd` data streams, we've observed that the `leader` data stream contains incorrect field definitions.

Issue can be replicated using etcd v2 by adding at least one member to the cluster.

```
etcdctl member add <name> <peerURL>
```

<b>Example of a leader event from beats:</b>

```json
"etcd": {
  "leader": {
    "follower": {
      "leader": "ce2a822cea30bfca",
      "latency": {
        "ms": 0
      },
      "failed_operations": 300,
      "id": "4ad9783cc83ba952",
      "success_operations": 0
    }
  },
  "api_version": "2"
}
```

<b>Field definitions should be (fields.yml):</b>

```yaml
- name: etcd.leader
  type: group
  fields:
  - name: follower
    type: group
    description: >
      Contains follower statistics.
    fields:
      - name: id
        type: keyword
        description: ID of follower
      - name: latency
        type: group
        description: >
          Latency to each peer in the cluster
        fields:
          - name: ms
            type: scaled_float
      - name: success_operations
        type: integer
        description: successful Raft RPC requests
      - name: failed_operations
        type: integer
        description: failed Raft RPC requests
      - name: leader
        type: keyword
        description: ID of actual leader
```
