### ISSUE TITLE
[elastic/integrations] [sonicwall] not visible in security app and some important ecs fields are missing.

### ISSUE THREAD

**Issue by StefanSa** [elastic/integrations#8533]
Hi there @chemamartinez 
In addition to several Sophos firewall appliances, we also have a number of Sonicwall appliances in use.
While the Sophos integration is well done, the Sonicwall integration lacks something.

1. Not visible due to necessary, missing ecs fields in the security app.
2. observer name is not always detected correctly.
3. host.name is completely missing

Can someone please customize this integration so that it is firstly visible in the security app and all necessary ecs fields are correctly created and displayed.

**Comment by efd6** [comment]
@StefanSa Can you expand on this please?

1. Which fields are missing?
2. Can you provide examples of events where you are not seeing what you expect, explaining what it is that you do expect?

**Comment by efd6** [comment]
@StefanSa thanks. Would you mind taking a look at #8547 and check whether you think that will address your concerns?

**Comment by StefanSa** [comment]
@efd6 Dan,
yes thanks, that works so far with this fix. 
```
  - grok:
      field: _temp_.header
      patterns: 
        - '^(?:<%{NUMBER:log.syslog.priority:long}>)?%{SYSLOGTIMESTAMP}?%{SPACE}%{DATA:_temp_.host}?$'
  - convert:
      field: _temp_.host
      type: ip
      target_field: host.ip
      if: ctx._temp_?.host != null
      ignore_failure: true
  - rename:
      field: _temp_.host
      target_field: host.name
      if: ctx.host?.ip == null && ctx._temp_?.host != null && ctx._temp_.host != ''
      ignore_failure: true
```
By the way, i have currently created a very similar customer pipeline, so all events from the Sonicwall have become visible in the Security App.

Thanks for your help
