### ISSUE TITLE
System integration problem when using Elasticsearch with Logstash and ECS-compatibility mode

### ISSUE THREAD

**Issue by samhop** [elastic/integrations#8543]
**Kibana version:**
8.9.0.

**Elasticsearch version:**
8.9.0

**Describe the bug:**
When using Logstash with ECS-compatibility mode Logstash populates some fields. One of the fields is event.original and this causes some of the built-in integrations to not work as intended. For example pipeline for syslogs (logs-system.syslog-1.41.0 pipeline) does not work as it should because the pipeline is configured assuming that there isn't already the event.original field.

Rename processors in logs-system.syslog-1.41.0 pipeline:
```
- rename:
      if: ctx.event?.original == null
      field: message
      target_field: event.original
      ignore_missing: true
  - rename:
      field: system.syslog.message
      target_field: message
      ignore_missing: true
```
When Logstash populates the event.original field the above renaming of the field _message_ is not done and the _message_ field still exists. This causes the next rename processor to fail when trying to rename the field _system.syslog.message_ as _message_ because there already is a _message_ field.

The same kind of problem exists with auth logs (logs-system.auth-1.41.0 pipeline):

```
  - rename:
      tag: rename_message
      if: ctx.event?.original == null
      field: message
      target_field: event.original
      ignore_missing: true
  - grok:
      if: ctx.log?.syslog == null
      description: Grok the message header.
      tag: grok-message-header
      field: event.original
      pattern_definitions:
        GREEDYMULTILINE: '(.|\n)*'
        TIMESTAMP: (?:%{TIMESTAMP_ISO8601}|%{SYSLOGTIMESTAMP})
      patterns:
        - '^<%{NONNEGINT:log.syslog.priority:int}>(?:%{NONNEGINT:system.auth.syslog.version} )?+(?:-|%{TIMESTAMP:system.auth.timestamp}) 
            +(?:-|%{IPORHOST:host.hostname}) +(?:-|%{SYSLOG5424PRINTASCII:process.name}) 
            +(?:-|%{POSINT:process.pid:long}) +(?:-|%{SYSLOG5424PRINTASCII:event.code}) 
            +(?:-|%{SYSLOG5424SD:syslog5424_sd})? 
            +%{GREEDYDATA:_temp.message}$'
        - '^%{TIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:host.hostname}? %{DATA:process.name}(?:\[%{POSINT:process.pid:long}\])?:%{SPACE}%{GREEDYMULTILINE:_temp.message}$'
        - '^<%{NONNEGINT:log.syslog.priority:int}>(?:%{NONNEGINT:system.auth.syslog.version} )?%{TIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:host.hostname}? %{DATA:process.name}(?:\[%{POSINT:process.pid:long}\])?:%{SPACE}%{GREEDYMULTILINE:_temp.message}$'
  - rename:
      tag: rename_message_tmp_message
      field: message
      target_field: _temp.message
      if: ctx.log?.syslog != null && ctx.message != null
  - grok:
      description: Grok specific auth messages.
      tag: grok-specific-messages
      field: _temp.message
      ignore_missing: true
      patterns:
        - '^%{DATA:system.auth.ssh.event} %{DATA:system.auth.ssh.method} for (invalid user)?%{DATA:user.name} from %{IPORHOST:source.address} port %{NUMBER:source.port:long} ssh2(: %{GREEDYDATA:system.auth.ssh.signature})?'
        - '^%{DATA:system.auth.ssh.event} user %{DATA:user.name} from %{IPORHOST:source.address}'
        - '^Did not receive identification string from %{IPORHOST:system.auth.ssh.dropped_ip}'
        - '^%{DATA:user.name} :( %{DATA:system.auth.sudo.error} ;)? TTY=%{DATA:system.auth.sudo.tty} ; PWD=%{DATA:system.auth.sudo.pwd} ; USER=%{DATA:system.auth.sudo.user} ; COMMAND=%{GREEDYDATA:system.auth.sudo.command}'
        - '^new group: name=%{DATA:group.name}, GID=%{NUMBER:group.id}'
        - '^new user: name=%{DATA:user.name}, UID=%{NUMBER:user.id}, GID=%{NUMBER:group.id}, home=%{DATA:system.auth.useradd.home}, shell=%{DATA:system.auth.useradd.shell}$'
      on_failure:
        - rename:
            description: Leave the unmatched content in message.
            field: _temp.message
            target_field: message
```
Logstash has already populated the _event.original_ field so the message field is not renamed and it still exists. Therefore later in the pipeline the renaming of __temp.message_ as _message_ will fail.

Perhaps at the beginning of the pipelines the field _message_ should be removed if _event.original_ field already exists?
