### ISSUE TITLE
[Cisco] Populating source.user.email field

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#8895]
Our ASA pipeline currently splits a user's email address into source.user and source.domain, but it can be valuable to also preserve the users email address. Can we populate source.user.email field, in addition to the user and domain fields?

Sample event:
```
<188>Jan 09 2024 08:58:42 HOST123 : %ASA-4-722051: Group <VPN-PROD-MSFT> User user.a@email.com IP <31.20.30.168> IPv4 Address <10.255.1.23> IPv6 address <::> assigned to session
```
Suggested pipeline modification:

```
  - set:
      field: source.user.email
      copy_from: source.user.name
      override: false
      if: 'ctx.source?.user?.name != null && ctx.source?.user?.name.contains("@")'
  # Support masked user value
  - grok:
      field: "source.user.name"
      if: 'ctx.source?.user?.name != null'
      tag: "grok_source_user_name"
      patterns:
        - (%{CISCO_DOMAIN})?%{CISCO_USER}
        - \*+
      pattern_definitions:
        CISCO_USER: "%{USERNAME:source.user.name}(@%{HOSTNAME:source.user.domain})?"
        CISCO_DOMAIN: (LOCAL\\)?(%{HOSTNAME:source.user.domain}\\)?
      on_failure:
        - append:
            field: error.message
            value: "fail-{{{ _ingest.on_failure_processor_tag }}}"
        - fail:
            message: "Processor {{ _ingest.on_failure_processor_type }} with tag {{ _ingest.on_failure_processor_tag }} in pipeline {{ _ingest.on_failure_pipeline }} failed with message: {{ _ingest.on_failure_message }}"
```
