### ISSUE TITLE
[cisco_ios] Setting time zone configuration has no affect on logs with no time zone

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/integrations#8998]
The integration configuration allows setting a time zone, which should allow a user to specify a time zone for logs without a time zone in the timestamp, which is the case for BSD-style timestamps. It looks like the if statement for the script processor that handles setting the time zone is at fault:

```yaml
  - script:
      lang: painless
      tag: script_timezone
      if: ctx._temp_?.tz != null && ctx._temp_?.tz != ''
```
`ctx._temp_.tz` is only set if a time zone was parsed from the log. Therefore, the script processor is skipped, and the next processor runs, which sets `event.timezone` to `UTC`.

```yaml
  - set:
      field: event.timezone
      value: UTC
      if: ctx.event?.timezone == null
```

This is observed during testing, where setting the time zone in the configuration to something like `+0200` still results in `event.timezone` being set to `UTC`.
