### ISSUE TITLE
[Cisco ASA] Parse 722022 and 722023 message id's

### ISSUE THREAD

**Issue by jamiehynds** [elastic/integrations#9012]
Our Cisco ASA does not currently parse message ID's 722022 and 722023, which contain valuable information when a TCP/UDP connection is established (722022) and a switched virtual connection is terminated (722023). 

Can we adjust our [ASA pipeline](https://github.com/elastic/integrations/blob/main/packages/cisco_asa/data_stream/log/elasticsearch/ingest_pipeline/default.yml) to correctly parse and map these events to ECS?

**Sample data**

<190>Jan 24 2024 15:24:40 XYZhost1 : %ASA-6-722022: Group User [src_user@myorg.com](mailto:src_user@myorg.com) IP <128.232.132.118> TCP SVC connection established without compression

<190>Jan 24 2024 15:25:23 XYZhost1 : %ASA-6-722023: Group User [src_user@myorg.com](mailto:src_user@myorg.com) IP <12.214.247.114> UDP SVC connection terminated without compression

Sample grok patterns shared by user:
```
  - grok:

      if: "ctx._temp_.cisco.message_id == '722022'"

      field: "message"

      description: "722022"

      patterns:

        - 'Group <%{NOTSPACE:source.user.group.name}> User <%{NOTSPACE:source.user.name}> IP <%{IP:source.address}> %{GREEDYDATA:event.reason}'

        - 'Group %{NOTSPACE:source.user.group.name} User %{NOTSPACE:source.user.name} IP %{IP:source.address} %{GREEDYDATA:event.reason}'

  - grok:

      if: "ctx._temp_.cisco.message_id == '722023'"

      field: "message"

      description: "722023"

      patterns:

        - 'Group <%{NOTSPACE:source.user.group.name}> User <%{NOTSPACE:source.user.name}> IP <%{IP:source.address}> %{GREEDYDATA:event.reason}'

        - 'Group %{NOTSPACE:source.user.group.name} User %{NOTSPACE:source.user.name} IP %{IP:source.address} %{GREEDYDATA:event.reason}'
```
