### ISSUE TITLE
Integration paging TAXII2 response

### ISSUE THREAD

**Issue by polakovicp** [elastic/integrations#9372]
Hi, in integration, I am paging over responses from TAXII2 server.
Each response returns JSON body, with more flag and _**X-TAXII-Date-Added-Last**_ header indicating timestamp of last added STIX object:
```json
{
    "more": false,
    "objects": [{...}]
}
```
Each request URL gets a query parameter _**added_after**_, which, initially is set to now - interval, and each subsequent paging request uses **_X-TAXII-Date-Added-Last_** header value from previous request. I want paging to stop, once **_X-TAXII-Date-Added-Last_** header is missing, or **_more_** is false.

What I have, does not work quite right and it generates request WITHOUT **_added_after_** query parameter.

httpjson.yml.hbs (some values were omitted for readability):
```yaml
request.transforms:
  - set:
      target: url.params.match[type]
      value: indicator
  - set:
      target: url.params.added_after

      #   Set added_after query param to initial value, or to the cursor timestamp
      value: >-
        [[ if not (index .cursor "timestamp") ]][[ formatDate (now (parseDuration "-{{initial_interval}}")) "2006-01-02T15:04:05.000Z" ]][[ end ]]

response.pagination:
  - set:
      # Page remote data collection using "X-TAXII-Date-Added-Last" header, if .last_response.body.more is true
      target: url.params.added_after
      value: >-
        [[ if .last_response.body.more ]]'[[ .last_response.header.Get "X-TAXII-Date-Added-Last" ]]'[[ end ]]
      fail_on_template_error: true

response.split:
  target: body.objects

cursor:
  # This value might not be set properly - set cursor.timestamp to "X-TAXII-Date-Added-Last ONLY IF it came in the latest response, otherwise use added_after
  timestamp:
    value: >-
      [[ if .last_response.header.Get "X-TAXII-Date-Added-Last" ]]'[[ .last_response.header.Get "X-TAXII-Date-Added-Last" ]]'[[ else ]]'[[.last_response.url.params.Get "added_after"]]'[[ end ]]
    ignore_empty_value: true
```

When checking requests, they do not look as expected - first request is OK, but subsequent ones (after **interval** time) does not contain **_added_after_**:
```
/?added_after=2024-03-13T08%3A29%3A23.742Z&match%5Btype%5D=indicator
/?match%5Btype%5D=indicator
/?match%5Btype%5D=indicator
...
```
