### ISSUE TITLE
Microsoft Defender for Endpoint - 400 Bad Request

### ISSUE THREAD

**Issue by NikoCosmico01** [elastic/integrations#9449]
Hi, I'm currently setting up my Elasticsearch version 8.12.2 but when I try to retrieve logs from Microsoft Defender for Endpoint v2.24.1 an error occurs. I have successfully created a new Azure Application having obtained Client ID, Client Tenant and Tenant ID. Those have been inserted into ELK integration that has been linked to an elastic agent but when I try ho make an API request from the edit-integration page this answer is shown

```
"statusCode": 400,
  "error": "Bad Request",
  "message": """[request body]: types that failed validation:
- [request body.0.inputs]: expected value of type [array] but got [Object]
- [request body.1.inputs.microsoft_defender_endpoint-httpjson.streams.microsoft_defender_endpoint.log.vars.client_secret]: types that failed validation:
 - [request body.0]: types that failed validation:
  - [request body.0]: expected value of type [boolean] but got [Object]
  - [request body.1]: expected value of type [string] but got [Object]
  - [request body.2]: expected value of type [number] but got [Object]
  - [request body.3]: expected value of type [array] but got [Object]
  - [request body.4]: expected value of type [array] but got [Object]
 - [request body.1]: expected value to equal [null]
```

That is weird because using the same integration with the above Client ID, Client Tenant and Tenant ID onto a different ELK stack version 8.7.0 and Microsoft Defender for Endpoint v2.9.0 a correct 200 code answer is shown.

The only difference I noted is in the console API request. In the ELK stack version 8.12.2 there is the following client_secret attribute
`"client_secret": {
              "id": "{RANDOM_ID}",
              "isSecretRef": true
            },`
while in the ELK stack version 8.7.0 the same attribute is shown in that functionally working form
`"client_id": "{ACTUAL_CLIENT_ID}",`
and moving the latter attribute definition into the ELK stack version 8.12.0 maked the API request working.

Could this be a cause for not receiving any logs from Microsoft Defender for Endpoint even if the elastic agent seems to be properly working? Do I have to check anything else rather than adding into elastic-agent.yaml the corresponding input?

**Comment by efd6** [comment]
@NikoCosmico01 Can you take a look at the diagnostic bundle to see what the `pre-config.yaml` looks like. When I look at a test config (stack v8.13.0, package v2.24.1), I see this
```
inputs:
    - data_stream:
        namespace: ep
      id: httpjson-microsoft_defender_endpoint-f34aff31-d757-42d5-b0bd-8028916d0fa1
      meta:
        package:
            name: microsoft_defender_endpoint
            version: 2.24.1
      name: microsoft_defender_endpoint-log
      package_policy_id: f34aff31-d757-42d5-b0bd-8028916d0fa1
      revision: 1
      streams:
        - auth.oauth2.azure.resource: https://api.securitycenter.windows.com/
          auth.oauth2.client.id: test-app-id
          auth.oauth2.client.secret: test-secret
          auth.oauth2.provider: azure
          auth.oauth2.token_url: http://elastic-package-service-microsoft-defender-mock-1:8080/tenant_id/oauth2/token
          config_version: "2"
          cursor:
            lastUpdateTime:
                value: '[[.last_response.body.lastUpdateTime]]'
          data_stream:
            dataset: microsoft_defender_endpoint.log
            type: logs
          id: httpjson-microsoft_defender_endpoint.log-f34aff31-d757-42d5-b0bd-8028916d0fa1
          interval: 5m
          publisher_pipeline.disable_host: true
          request.method: GET
          request.tracer.filename: ../../logs/httpjson/http-request-trace-*.ndjson
          request.tracer.maxbackups: 5
          request.transforms:
            - set:
                target: header.User-Agent
                value: MdatpPartner-Elastic-Filebeat/1.0.0
            - set:
                target: url.params.$expand
                value: evidence
            - set:
                default: lastUpdateTime gt [[formatDate (now (parseDuration "-5m")) "2006-01-02T15:04:05.9999999Z"]]
                target: url.params.$filter
                value: lastUpdateTime gt [[formatDate .cursor.lastUpdateTime "2006-01-02T15:04:05.9999999Z"]]
          request.url: http://elastic-package-service-microsoft-defender-mock-1:8080/api/alerts
          response:
            split:
                ignore_empty_value: true
                split:
                    keep_parent: true
                    target: body.evidence
                target: body.value
          tags:
            - microsoft-defender-endpoint
            - forwarded
      type: httpjson
      use_output: default
```
Note that the relevant configuration fields appear as expected
```
          auth.oauth2.client.id: test-app-id
          auth.oauth2.client.secret: test-secret
```
I've checked changes to the integration between v2.9.0 and now and there have been no changes there that would affect this.

It would be worth checking differences between v2.9.0 and v2.24.1 in this file, though I do not expect to see any differences that would bear on this.

**Comment by NikoCosmico01** [comment]
That is mine `pre-config.yaml`:
```
  - data_stream:
        namespace: default
      id: httpjson-microsoft_defender_endpoint-8e70e19d-c08d-4aeb-ab82-49460cec0165
      meta:
        package:
            name: microsoft_defender_endpoint
            version: 2.24.1
      name: microsoft_defender_EndPoint
      package_policy_id: 8e70e19d-c08d-4aeb-ab82-49460cec0165
      revision: 6
      streams:
        - auth.oauth2.azure.resource: https://api.securitycenter.windows.com/
          auth.oauth2.client.id: {CLIENT_ID}
          auth.oauth2.client.secret: {CLIENT_SECRET}
          auth.oauth2.provider: azure
          auth.oauth2.token_url: https://login.microsoftonline.com//{TENAND_ID}/oauth2/token
          config_version: "2"
          cursor:
            lastUpdateTime:
                value: '[[.last_response.body.lastUpdateTime]]'
          data_stream:
            dataset: microsoft_defender_endpoint.log
            type: logs
          id: httpjson-microsoft_defender_endpoint.log-8e70e19d-c08d-4aeb-ab82-49460cec0165
          interval: 1m
          publisher_pipeline.disable_host: true
          request.method: GET
          request.transforms:
            - set:
                target: header.User-Agent
                value: MdatpPartner-Elastic-Filebeat/1.0.0
            - set:
                target: url.params.$expand
                value: evidence
            - set:
                default: lastUpdateTime gt [[formatDate (now (parseDuration "-5m")) "2006-01-02T15:04:05.9999999Z"]]
                target: url.params.$filter
                value: lastUpdateTime gt [[formatDate .cursor.lastUpdateTime "2006-01-02T15:04:05.9999999Z"]]
          request.url: https://api.securitycenter.windows.com/api/alerts
          response:
            split:
                ignore_empty_value: true
                split:
                    keep_parent: true
                    target: body.evidence
                target: body.value
          tags:
            - preserve_original_event
            - microsoft-defender-endpoint
            - forwarded
      type: httpjson
      use_output: default
```
And as you said in this file, I clearly see the Client Secret. Do you think is there a reason for the 400 - Bad Request answer I get? Other than that, even if the Elastic Agent seems to work properly, I cannot see any log coming from Microsoft Defender for Endpoint in the Data Stream section.
![image](https://github.com/elastic/integrations/assets/84101958/0d18e1cd-e831-4bdd-9836-d15896909111)
