### ISSUE TITLE
[Bug] panw.panos pipeline is duplicating 'denied' in event.type

### ISSUE THREAD

**Issue by jvalente-salemstate** [elastic/integrations#9535]
The ingest pipeline is appending `denied` to `event.type` when the panos action is drop or deny, and then again when the sub_type is also drop or deny.

Within the default ingest pipeline `/panw/data_stream/panos/elasticsearch/ingest_pipelines/default.yml`

```yml
# Set event.category.
  - append:
      field: event.type
      value: allowed
      if: ctx.panw?.panos?.action != null && ['alert', 'allow', 'continue'].contains(ctx.panw.panos.action)
  - append:
      field: event.type
      value: denied
      if: ctx.panw?.panos?.action != null && ['deny', 'drop', 'reset-client', 'reset-server', 'reset-both', 'block-url', 'block-ip', 'random-drop', 'sinkhole', 'block'].contains(ctx.panw.panos.action)

...

  - set:
      field: event.action
      value: flow_dropped
      if: ctx.panw?.panos?.sub_type == 'drop'
  - append:
      field: event.type
      value:
        - denied
        - connection
      if: ctx.panw?.panos?.sub_type == 'drop'
  - set:
      field: event.action
      value: flow_denied
      if: ctx.panw?.panos?.sub_type == 'deny'
  - append:
      field: event.type
      value:
        - denied
        - connection
      if: ctx.panw?.panos?.sub_type == 'deny'

```

Sample Event
```json
{
    "event.type": [
      "denied",
      "denied",
      "connection"
    ],
    "panw.panos.action": [
      "drop"
    ],
    "panw.panos.sub_type": [
      "deny"
    ],

}

```

Looking through my logs, this occurs with the following combinations

`panw.panos.action`

* drop
* deny
* reset-both

`panw.panos.sub_type`

* drop
* deny

I am not seeing any duplication with any other actions or sub_types. I don't have any examples containing `reset-client` to see if this is duplicated or behaves like `reset-server`, which isn't duplicated (sub_type is exploit_detected)
