### ISSUE TITLE
Missing documentation for query metricset

### ISSUE THREAD

**Issue by masci** [elastic/integrations#964]
Current docs at https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-mysql-query.html don't show how the module is supposed to be configured, in particular users have a hard time finding out that:
- If the `query` metricset is enabled, the `queries` parameter is mandatory, otherwise you get the error `Error getting metricbeat modules: module initialization error: 1 error: missing required field accessing ‘0.queries’`
- the `queries` config param has to be an array, see the following example:
```
- module: mysql
  metricsets:
    - status
    - galera_status
    - performance
    - query
  period: 10s
  namespace: "my_namespace"
  queries:
    - query: "SELECT * FROM performance_schema.global_status"
      response_format: "variables"
      query_namespace: "my_first_query_namespace"
    - query: "SELECT * FROM performance_schema.global_status"
      response_format: "variables"
      query_namespace: "my_second_query_namespace"
```
- the `response_format` is the same as `sql_response_format` in the [SQL Module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-sql.html), documentation can be found there 🙈
