### ISSUE TITLE
[Microsoft M365 Defender]  Incorrect mapping initiating process to `process.parent`.

### ISSUE THREAD

**Issue by jvalente-salemstate** [elastic/integrations#9993]
The `event` dataset of this integration consists of around 20 tables from M365 Defender XDR, A large share of these are logs and telemetry from its EDR solution. The `DeviceEvents` has a several `event.action` values where the process that initiates the event is mapping as `process.parent.*` rather than `process.*`

Many of these actions are items such as getting clipboard data, or initiating an antivirus scan.  In the schema for the XDR table, there are two relevant properties

`InitiatingProcessFileName` -  "Name of the process that initiated the event:]"

`InitiatingProcessParentFileName` - "Name or full path of the parent process that spawned the process responsible for the event"

The pipeline sets the initiating process as the parent process, leaving no process captured and a conflict if both properties exist. 

```yml

 - set:
       field: process.parent.name
       copy_from: m365_defender.event.initiating_process.file_name
       ignore_empty_value: true
       tag: set_process_parent_name
       if: ctx.event?.category != null && (ctx.event.category.contains('process') || ctx.m365_defender.event.category.toLowerCase().contains('deviceevents'))

```

This can be verified with ES|QL to filter for all of the Device related events that have a parent process name, but no process name 

Note: I'm excluding process in the query because there is an open PR that does fix this for processes where `imageloadevent` also has this issue. 

  
```
from logs-*| where event.dataset == "m365_defender.event" and m365_defender.event.category like "AdvancedHunting-Device*" | where process.parent.name is not null and process.name is null | where event.category != "process"| stats Count = count() by event.action| sort Count desc
```

Over the last month, we've these 32 event.actions 

|Count|	event.action|
|---|---|
|4670156|	namedpipeevent|
|1809039|	dpapiaccessed|
|1237504|	ntallocatevirtualmemoryapicall|
|947841|	getclipboarddata|
|842777|	ntprotectvirtualmemoryapicall|
|494099|	browserlaunchedtoopenurl|
|462091|	processprimarytokenmodified|
|237420|	powershellcommand|
|167269|	clrunbackedmoduleloaded|
|38521|	ldapsearch|
|7634	|	dnsqueryresponse|
|5528|	ntallocatevirtualmemoryremoteapicall|
|5205|	memoryremoteprotect|
|4326|	screenshottaken|
|4188|	antivirusscancompleted|
|3984|	exploitguardwin32systemcallblocked|
|3091|	getasynckeystateapicall|
|2328|	appguardcreatecontainer|
|2193|	exploitguardacgenforced|
|805|		writetolsassprocessmemory|
|275|		antivirusscancancelled|
|265|		controlflowguardviolation|
|215|		appcontrolpolicyapplied|
|114|		createremotethreadapicall|
|110|		auditpolicymodification|
|101|		ntmapviewofsectionremoteapicall|
|15|	appguardlaunchedwithurl|
|11|	appguardresumecontainer|
|4|	smartscreenurlwarning|
|4|	appguardbrowsetourl|
|2|	otheralertrelatedactivity|
|1|	antivirusscanfailed| 

**Solution**

Two processors are required, such as 

```yml

 - set:
       field: process.name
       copy_from: m365_defender.event.initiating_process.file_name
# ...

 - set:
       field: process.parent.name
       copy_from: m365_defender.event.initiating_process.parent.file_name
...

```
